### ISSUE TITLE
Throw out stuff from com.artemis.utils thats not used by artemis

### ISSUE THREAD

**Issue by lopho** [junkdog/artemis-odb#14]
Utils
FastMath
TrigLUT
Timer

Why carry this stuff around? If a user needs these kind of utils they can get them everywhere.

Sure, it's convenient to have, let's say, fastmath for games, but still, you can get fastmath stuff about everywhere.
I'd say anything not used by artemis or directly related to artemis should not be in artermis.

anyways, too little sleep, too much LCD tan.
night.

**Comment by DaanVanYperen** [comment]
Het psst, @junkdog, 1.0 on the horizon, you can scratch this itch!
