### ISSUE TITLE
Request: Support nested @Wire on superclass.

### ISSUE THREAD

**Issue by pakoito** [junkdog/artemis-odb#162]
I have found that the functionality of Wire and Mapper is not available for my system, and I receive a NPE when trying to access the Component mapper that was supposed to be injected.

Line 30

https://github.com/pakoito/CardGameFramework/blob/master/cgfw-core/src/main/java/com/pacoworks/cardframework/systems/GameSystem.java

The world is created at lines 32+

https://github.com/pakoito/CardGameFramework/blob/master/cgfw-core/src/main/java/com/pacoworks/cardframework/framework/CardgameFramework.java

Does it have to do with the system being abstract and annotations not working on inheritance?

**Comment by DaanVanYperen** [comment]
Grooming issue. out of scope or in need of sponsor. Revisit later.

**Comment by DaanVanYperen** [comment]
Implemented ,`@Wire` is now default.

**Comment by festevezga** [comment]
Neato, thanks. I need to come back to libgdx and artemis one of these days. Too busy with work.
