### ISSUE TITLE
Save-load world instances

### ISSUE THREAD

**Issue by DaanVanYperen** [junkdog/artemis-odb#165]
or sufficient API access to support custom serialization solutions.

**Comment by junkdog** [comment]
We need a name for the world model (the agnostic data representation, common to all de/serializers):
- IntermediateGenesis
- WorldRecord (kinda like this one)
- WorldData (meh)
- PersistedWorld
- SerializedWorld

something else entirely?

**Comment by DaanVanYperen** [comment]
`WorldModel`

:dancer:

**Comment by Namek** [comment]
`WorldState` :hurtrealbad:

**Comment by DaanVanYperen** [comment]
Aren't entities the agnostic data representation of world in an ECS? XD
