### ISSUE TITLE
[weaving] forced pooling/packaging option for weaver

### ISSUE THREAD

**Issue by DaanVanYperen** [junkdog/artemis-odb#186]
Request for a plugin setting that forces pooled/packaging of non abstract components, to facilitate packaging of non-annotated library based components (optionally with a prefix filter?).

Edit: Possibly with forced exclusion annotation. (don't know if arrays are supported by packed, but entities with map data and the like will probably never benefit from packaging).

Nb. For the wiki: 
- Is there a limit in the flyweights of the same type I can access? (say when I'm comparing two pos components of different entities). 
- Pooled and packaged, mutually exclusive?
- What's the cost for each, is packed more or less memory efficient than plain?

**Comment by DaanVanYperen** [comment]
> because libgdx explodes all dependencies on desktop:dist! Which is something that can be done on maven as well, might be the cheap-solution-with-some-caveats.

Deprecated this approach in the new -quickstart, exploding is costly,  running weaving early in the build process now so you get to debug with options enabled. It's just build configuration though.

**Comment by junkdog** [comment]
Moving this to the future 1.x future.

**Comment by DaanVanYperen** [comment]
@junkdog I've since changed opinion, libraries should implement PooledComponent by default if it would be sensible / best practice for such a component. PackedComponent is currently not desirable. blanked conversion is probably not really desirable.

close ticket if you agree. ;)
