### ISSUE TITLE
Entity transmuters - step 2

### ISSUE THREAD

**Issue by junkdog** [junkdog/artemis-odb#209]
See #208

**Comment by junkdog** [comment]
Hmm, could use some input on this one... I'm thinking step 2 could entail adding optional components to entity factories?

**Comment by DaanVanYperen** [comment]
What would be some usecases? Haven't made any new games recently so my usage has been limited.

**Comment by junkdog** [comment]
Well, either make something akin to EntityFactories but for existing entities (implying an interface definition + annotation for removing components), or simply allow for optionally included componets in EntittyFactories (`@OptionalComponent`).

I think the second alternative offers more value, although the first one might be better... or it's too much of a corner-case to warrant dev time for the next release.

**Comment by DaanVanYperen** [comment]
Groomed issues worth revisiting later. Out of scope or in need of sponsor.
