### ISSUE TITLE
@PackedWeaver lacks synchronization during initialization

### ISSUE THREAD

**Issue by junkdog** [junkdog/artemis-odb#215]

**Comment by DaanVanYperen** [comment]
@junkdog could you elaborate a bit?

**Comment by junkdog** [comment]
https://github.com/junkdog/artemis-odb/blob/master/artemis-test/src/main/java/com/artemis/component/PackedWeaverReference.java#L23 - $store isn't accessed in a threadsafe manner.

**Comment by DaanVanYperen** [comment]
Groomed issues worth revisiting later. Out of scope or in need of sponsor.
