### ISSUE TITLE
Introduce annotation for non-finalized parts of the API

### ISSUE THREAD

**Issue by junkdog** [junkdog/artemis-odb#216]
`@EarlyAccess` or something...

**Comment by junkdog** [comment]
Yeah, primarily, I'm thinking about PackedComponent - which would be hard to rip out of core. Need to investigate how to optimize `@PackedWeaver`, will probably change the underlying implementation. More independent parts could definitely go into contrib though.

**Comment by DaanVanYperen** [comment]
Makes sense! Figure the lack of annotation is caused by devs keeping experimental features in snapshots.
