### ISSUE TITLE
[@Profile]: Support alternative system invocation strategy

### ISSUE THREAD

**Issue by DaanVanYperen** [junkdog/artemis-odb#221]
Tried adding some basic profiling unilaterally across all systems by extending World, but noticed a lot of the fields are currently private so can't really do that.

Could use ```@Profile``' but got a lot of systems and would prefer a less involved solution.

Wonder what you think of introducing SystemInvocationStrategy on World that'll process the systems. That way users can optionally replace system processing without invading World.

or instead just make fields like `rebuiltIndices` protected ;)

**Comment by DaanVanYperen** [comment]
Other uses would be opening up route to predictable event dispatching (pre process dispatch of subscribed events, comparable to polling, as opposed to synchronous ad-hoc). https://github.com/junkdog/artemis-odb/issues/17

If opening up the system invocation as a whole doesn't appeal, perhaps a pre/post listener?

**Comment by junkdog** [comment]
`rebuiltIndices` might be going away - going to do some perf testing, might not be necessary.

`SystemInvocationStrategy` isn't too bad though.

**Comment by junkdog** [comment]
Leaning towards the easy route on this on; will this suffice?

**Comment by DaanVanYperen** [comment]
Looks fine, gives options. can evolve it with time!

**Comment by junkdog** [comment]
Great, I declare this one closed then.
