### ISSUE TITLE
The octocat demands tribute!

### ISSUE THREAD

**Issue by DaanVanYperen** [junkdog/artemis-odb#222]
Our benevolent overlord (ALL HAIL THE OCTOCAT) has noticed your efforts at delivering him 90 stars and has asked me to bring you his holy purr!

I must reveal to you your personally tailored and highly classified sacrifice every github member is expected to perform upon reaching a project that approaches 100 stars. This is your DUTY!

At such time you reach 100 stars you are tasked to provide a trans-formative work based on ODB that will both revolutionize the ECS scene, and bring praise and new souls. Behold! The scope put forth by your master, Octocat!:
* Support for Teavm! For you must open up the path to Scala, and Scala will open up the path to his Divine Whiskers. All knowing be their tickle!
* Automatically maintained attribute based subsets, for such things as (spatial) partitioning. For may never those entities touch, separated by twice the length of his appendages. 
* JunkdogEntityQueryLanguage (JEQL) to assemble such subsets, for the devout prophets should put their names on at least one aspect of their creation.
* Perform an unholy merger of Akka and Artemis. Data, behaviour and performance driven aspects of ECS merged with the concurrent and distributed aspects of the actor model. ‘Are phones and browsers forever bereaved of Artemis concurrency? Will we forever have to process and render in the same threadless tapestry? NO!’ our lord proclaims! And so it shall be.
* And of course, one can of taurine-ated soda for each implemented strategy, flexible system flow or other tickets put forth by @DaanVanYperen, because our lord loves those.  https://github.com/junkdog/artemis-odb/issues/159 

You have one year. BLESSED BE HIS SUCKERED GRASP!

PS. Anyone else, feel free to provide additional scope. This is the way into the heart of the great Octocat.

**Comment by junkdog** [comment]
> At such time you reach 100 stars you are tasked to provide a trans-formative work based on ODB

Corners will be cut...

JEQL is actually something I've been entertaining... had a more complete implementation in a message-based component architecture I experimented with (it used the components-with-logic approach: a telnet component exposed a CLI-like interface - could be used for querying, instantiation and deletion of components, and sending messages).

**Comment by DaanVanYperen** [comment]
Sorry, you dropped to 89 stars. Lost your chance with Octocat!
