### ISSUE TITLE
GWT java 8 support (compile)

### ISSUE THREAD

**Issue by DaanVanYperen** [junkdog/artemis-odb#224]
See: 2030047f3ec89107249801f6524233697034aadd 

Release of GWT ~~3.0~~ 2.8 appears to be planned ~~early~~ may? 2015, which will provide support for Java 8.

**Comment by DaanVanYperen** [comment]
http://www.infoworld.com/article/2874861/application-development/google-web-toolkit-major-upgrades-no-backward-compatibility.html

**Comment by DaanVanYperen** [comment]
Java 7 went EOL. I assume more people will start using 1.8 syntax. GWT 2.8 or 3.0 still not arrived! https://groups.google.com/forum/#!topic/google-web-toolkit/JHJybu-mluU

**Comment by junkdog** [comment]
Hey! Hah, at work we're still in the process of migrating the test server infrastructure and updating it to run with java 8. Several weeks ahead of the EOL.

So, GWT are as bad as artemis-odb at releasing in a timely fashion. Still plowing unity land, thus artemis has been on hold for a while. Midway through de/serialization.

**Comment by DaanVanYperen** [comment]
Appearantly still no release. 2.8.0-SNAPSHOT is out there.

https://github.com/gwtproject/gwt/issues scares the living jeebies out of me.

**Comment by junkdog** [comment]
> https://github.com/gwtproject/gwt/issues scares the living jeebies out of me.

Google does have a [thing](https://code.google.com/p/android/issues/detail?id=3838) for randomly just giving up on stuff mere mortals thought were important to them.

**Comment by junkdog** [comment]
re-opening this when GWT 3.0 is released (and works)

**Comment by DaanVanYperen** [comment]
*gargl*

http://www.gwtproject.org/release-notes.html#Release_Notes_2_8_0_RC1

**Comment by junkdog** [comment]
ヾ(＾∇＾)

**Comment by junkdog** [comment]
> http://www.gwtproject.org/release-notes.html#Release_Notes_2_8_0_RC1

> Static and default methods in interfaces aren’t visible to generators. If you want to take advantage of those Java-8isms, you’re encouraged to switch to an annotation processor. This could break existing build if an interface is changed to turn a non-default method into a default method.

meth...

Looks like they have BitSet and a few other classes properly supported now though.

**Comment by DaanVanYperen** [comment]
Duplicate #483
