### ISSUE TITLE
[EntityFactory] Support for optional components.

### ISSUE THREAD

**Issue by DaanVanYperen** [junkdog/artemis-odb#228]
@junkdog: "Yo, nope, no optional components. It would require N^2 archetypes, which was the original reason it wasn't supported. However, with entity transmuters now implemented  - this might be feasible; simply have one transmuter per optional component. Probably post-1.0 work though."

**Comment by Namek** [comment]
A usecase, please?

**Comment by junkdog** [comment]
Hmm, I have a couple in the current project... some are as simple as having/not having a Touchable component, but the EntityFactory is otherwise identical.

**Comment by DaanVanYperen** [comment]
Grooming issue. out of scope or in need of sponsor. Revisit later.
