### ISSUE TITLE
Problems when using Two instances of World

### ISSUE THREAD

**Issue by jplorandi** [junkdog/artemis-odb#231]
I'm coding a client/server app with LibGdx and artemis-odb, where both client and server each keep an instance of World which is replicated/reconciliated between clients and server (server is authoritative). I'm completely unable to run an instance of each within the same JVM (for testing purposes) (the server version also runs with gdx-headless-backend). The appropiate stacktrace for trunk:

```
java.lang.NullPointerException
	at com.artemis.EntityManager.clean(EntityManager.java:245)
	at com.artemis.World.process(World.java:567)
``` 

This worries me to no end since I will want to run many such servers within a single JVM. Is this a known bug? I'll try to create a test case as soon as I can.

EDIT: basically the EntityManager's recyclingEntityFactory is null somehow.

**Comment by jplorandi** [comment]
Please Close, my mistake (I should have done the test case in the first place)

**Comment by junkdog** [comment]
Did you get it working? There should be nothing prohibiting multiple worlds instances to run within the same JVM. All static fields were removed some time ago.

**Comment by jplorandi** [comment]
Yes; unfortunately I refactored some things wrong when I migrated from 0.7.x to trunk in anticipation for 0.9.0 and some Exceptions weren't being printed. Can't waste a chance to make a fool of myself in public I guess :)

**Comment by junkdog** [comment]
You're in good company, we're all fools or somewhat crazy.

I just published the artifacts for 0.9.0 btw - they should be live within a couple of hours.

**Comment by jplorandi** [comment]
Brilliant. Is there anything needed to run the regular vs the fast version? Excuse my ignorance :$

**Comment by junkdog** [comment]
You can hook it into your buld process - check out [Weave Automation](https://github.com/junkdog/artemis-odb/wiki/Weave-Automation).

Some more background: https://github.com/junkdog/artemis-odb/wiki/Hotspot-Optimization
