### ISSUE TITLE
ComponentMapper#get(int entityId)

### ISSUE THREAD

**Issue by Namek** [junkdog/artemis-odb#233]
`ComponentMapper` lacks method `#get(int entityId)`. Can this be put in? I think it's reasonable since entity `flyweight` thing appeared in `EntitySystem`.

**Comment by junkdog** [comment]
Oops, I meant to put it in.

**Comment by Namek** [comment]
Any estimated time to complete? :pager:

**Comment by junkdog** [comment]
Need rewrite PackedComponents, but they're in a transitory state now anyway.

**Comment by Namek** [comment]
Thanks!
