### ISSUE TITLE
World#deleteEntity(int entityId)

### ISSUE THREAD

**Issue by Namek** [junkdog/artemis-odb#234]
Method `World#deleteEntity(int entityId)` doesn't exist.

Same reasoning as in #233.

We can do `world.getEntity(entityId).deleteFromWorld()` but it smells to me.

**Comment by DaanVanYperen** [comment]
It's so smelly in here @junkdog, do something about it already!

**Comment by junkdog** [comment]
:dog: :hankey:

**Comment by junkdog** [comment]
Fixed in https://github.com/junkdog/artemis-odb/commit/756f15bb6a8c61ce875c8f9e27b3426b1521121f
