### ISSUE TITLE
Unitialized World throws NPE

### ISSUE THREAD

**Issue by jplorandi** [junkdog/artemis-odb#237]
This may sound dumb, but I've found that not calling ```world.initialize()``` and then calling ```world.process()``` results in an NPE about ```EntityManager.recyclingEntityFactory```. Would it be possible to throw a more descriptive Exception the instance wasn't initialized?

**Comment by junkdog** [comment]
Yeah, it's something of an API sin that it's possible to call #process - and a few other methods - in an incomplete state.
