### ISSUE TITLE
Custom flyweight entity

### ISSUE THREAD

**Issue by Namek** [junkdog/artemis-odb#238]
Is there any way to create custom `flyweight` entity?

`Entity` constructors are hidden, calling `World#createEntity()` pollutes the world. I need this because I refactor renderer to use integer IDs instead of Entity `references`. I'm in place and moment where I need to get components of entity and I have 2 ugly options:
1. having an `Entity flyweight`
2. passing `World` directly

Second option is something I dislike because that's just renderer for given entity and it shouldn't have access to all entities (and having reference to `World` would mean this).

**Comment by Namek** [comment]
This is what I do, actually:
```java
public class KeyFrameAnimationsRenderer implements ILibgdxBatchRenderMethod {

	@Override
	public void draw(Entity entity, Batch batch, Camera camera) {
		KeyFrameAnimations animations = entity.getComponent(KeyFrameAnimations.class);
		AnimationLife animationLife = entity.getComponent(AnimationLife.class);
		
		Animation currentAnimation = animations.getCurrentAnimation();
		float stateTime = animationLife.stateTime;
		
		float x = -animations.originX * animations.width;
		float y = -animations.originY * animations.height;
		
		Position positionComponent = entity.getComponent(Position.class);
		if (positionComponent != null) {
			Vector2 position = positionComponent.current;
			Vector2 offset = positionComponent.graphicalOffset;
			
			x += position.x + offset.x;
			y += position.y + offset.y;
		}

		TextureRegion textureRegion = currentAnimation.getKeyFrame(stateTime, true);
		batch.draw(textureRegion, x, y);
	}

}
```
I want to change `Entity entity` to `int entityId`.

**Comment by DaanVanYperen** [comment]
@junkdog is reworking the system hierarchy. When that is done adding a
index based processingsystem to contrib should be easy and robust.
Op 15 feb. 2015 05:23 schreef "Namek" <notifications@github.com>:

**Comment by DaanVanYperen** [comment]
*edit* After re-reading, you want  `ComponentMapper#get(int entityId)`?

**Comment by Namek** [comment]
None of both. `ComponentMapper#get(int entityId)` is already in there. Ideally, I'd like to call `new Entity(this, -1)` but that constructor is protected and `Entity` class is `final`.

The problem is about that I pass `Entity` object into my function. It would be best to leave it as it is but internally I shouldn't save references to `Entity` objects but integers. Having an `integer` and wanting to pass `Entity` makes me to need `flyweight` object as is it is done in `EntitySystem` class already (look for `flyweight` variable).

I know that sounds hacky but I'm not sure about how to handle it better.

**Comment by DaanVanYperen** [comment]
What's the overarching architecture like that makes `KeyFrameAnimationsRenderer`unimplementable as a system? Is it like a subsystem to an overarching rendering pipeline?

**Comment by Namek** [comment]
Hmmmm, well... let's begin. Well, I'll describe it in a simplified manner because all details would blow that description up.

1. I have `RenderableSystem` which colllects all entities that have `Renderable` component and contains a list of `RenderLayer` objects.
2. Each `RenderLayer` contains entities that belong to that layer. Those entities are sorted by subLayer.
3. `RenderLayer` is half-abstract (it does have some methods), it's being implemented by `RenderLayerBatchImpl` which renders using `Batch` from LibGDX. 
4. `RenderLayerBatchImpl` renders all it's entities (remember, it's a layer).
5. **Now**, every entity can have a different method to be rendered. `RenderLayerBatchImpl` just checks for components like: `SpriteComponent`, `LibgdxBatchRenderMethod`. Some time ago list of these components was bigger but I have provided `LibgdxBatchRenderMethod` which decouples some things.
6. `LibgdxBatchRenderMethod` is a component which contains field `ILibgdxBatchRenderMethod renderMethod` which is an interface:

```java
public interface ILibgdxBatchRenderMethod {
	void draw(Entity entity, Batch batch, Camera camera);
}
```

seven. In the end some running Stick Man has following components needed to be rendered:

* `Renderable` - specifies `int layer`, `int subLayer`, `boolean visible`
* `LibgdxBatchRenderMethod` - specifies custom method, here it's reference to `KeyFrameAnimationsRenderer` which implements `ILibgdxBatchRenderMethod`
*  `KeyFrameAnimations` -down below it's basically `RandomAccessMap<String, Animation>`, Animation contains textures
* `AnimationLife` - basically it's a `stateTime` of animation


Whole system is being used like this:
```java
RenderLayersList renderLayers = new RenderLayersList();
OrthographicCamera camera = new OrthographicCamera();
camera.setToOrtho(false, Gdx.graphics.getWidth(), Gdx.graphics.getHeight());
renderLayers.add(RenderLayers.Game, new RenderLayerBatchImpl(Layers.MIN_GAME_LAYER, Layers.MAX_GAME_LAYER, camera, spriteBatch));
		
GuiRenderLayer guiLayer = new GuiRenderLayer(spriteBatch, camera, Layers.GUI_LAYER);
renderLayers.add(RenderLayers.GUI, guiLayer);


artemisWorld.setSystem(new RenderableSystem(renderLayers));
```

**Comment by DaanVanYperen** [comment]
I've been looking for a good way to do multiple passes on the same entities, your layer concept looks  like part of the puzzle. *ninja* ;)

I think your main pain is caused by having logic in components. I assume that's to avoid the lookup costs you'd otherwise incur, but wonder if it's worth the sacrifice of not having `ComponentMapper` in your tightest rendering logic. You could consider implementing `ILibgdxBatchRenderMethod` in passive systems instead, so you can use the CM and systems flyweight.

More advanced/flexible system invocation for Artemis is highest on my wishlist. ;)

**Comment by Namek** [comment]
Actually, I took this concept from [gemserk/common-gdx -> artemis](https://github.com/gemserk/commons-gdx/tree/master/commons-gdx-artemis/src/main/java/com/gemserk/commons/artemis) and I have improved it in some places, extended it further by those `RenderMethod` things and abstracting out layers so they could have different batches. I also made it easier to implement entirely custom layer too.

Layering is the core here. And as you said, drawback here is that the logic is put into components (through `RenderMethod`). But I don't dislike it here. Just take a look at Unity3D's architecture, omg.

> You could consider just using a flag/enum component and implementing ILibgdxBatchRenderMethod in passive systems instead, so you can use the CM and system's flyweight.

Having both ComponentMappers and entity flyweight makes it redundant. I just need one of those. Anyway, that would be almost same as passing reference to `World` along with `entityId` and even more hacky. Thanks for your input! I'll reconsider that change later.

**Comment by DaanVanYperen** [comment]
> Having both ComponentMappers and entity flyweight makes it redundant. I 

Just mentioning that option is there if your usecase calls for it. I would just use CM as well.

> that would be almost same as passing reference to World along with entityId and even more hacky.

Hey! Discrete and batched entity operations fit systems as a glove. I would argue it is less hacky to implement your rendering operation in a system. Component sided logic is causing your issues here. 

Then again, @junkdog could just make you that flyweight already. slacker.

**Comment by Namek** [comment]
Maybe I imagined it in a different way comparing to yours imagination ;) Whole thing was to have something common, to not implement that in every game. And until Entity pooling appeared everything was OK (besides render logic in components, I know!). I'll rethink that after acquiring some strength and power juices.

**Comment by DaanVanYperen** [comment]
You must join my religion! It is the purpose of the internet! Wrawawahwrah! :japanese_ogre:

**Comment by Namek** [comment]
Enterprisey religion? How do I do that?

**Comment by junkdog** [comment]
> Is there any way to create custom flyweight entity?

I'm not entirely happy with how the current flyweight approach works (public-ing id etc), so I'm a little reluctant committing something to the public API. To circumvent the restricted constructor, the most immediate approach would be a small utility class under com.artemis in your project:

```java
package com.artemis;

public final class EntityUtil {
	private EntityUtil() {}
	
	public static Entity createUnworldlyEntity(World world) {
		return new Entity(world, -1);
	}
}
```

**Comment by junkdog** [comment]
> But I don't dislike it here. Just take a look at Unity3D's architecture, omg.

Hehe

**Comment by Namek** [comment]
@junkdog Solution is similiar to reflection `setAccessible(true)` on `Constructor` :D

You're not happy with `flyweight`? Are you gonna change it somehow, possibly? Maybe I invest time in bad direction.

**Comment by junkdog** [comment]
Well, the flyweight is staying because of how efficient it is memorywise - might need to rethink the benchmarks now because all fit into L3, even at 65k entities. I'd just like a cleaner solution, that's all - feels like a hack.

I was actually trying to remove Entity entirely from the final classes, but it's semi-hard (and very messy) because of how Entity has a reference to world.
