### ISSUE TITLE
Apply for LibGDX third party external extension

### ISSUE THREAD

**Issue by DaanVanYperen** [junkdog/artemis-odb#239]
https://github.com/libgdx/libgdx/wiki/Third-Party-Extension-Support

Not so prominently featured in libgdx generator so less toe-stepping, we might have to do a PR to extend the extension support a bit for all the advanced configuration we need.

**Comment by junkdog** [comment]
Interesting, something for 1.0.0.

**Comment by DaanVanYperen** [comment]
Grooming issue. out of scope or in need of sponsor. Revisit later.
