### ISSUE TITLE
EntityFactory support for enum values

### ISSUE THREAD

**Issue by junkdog** [junkdog/artemis-odb#245]
reference: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/artemis-odb/YCkTlRXz3Q0/xXajmLW5cvUJ

Also investigate why objects as parameters aren't allowed, can't recall why atm.

**Comment by DaanVanYperen** [comment]
> Also investigate why objects as parameters aren't allowed, can't recall why atm.

Sticky values perhaps?
