### ISSUE TITLE
Extract BaseSystem from EntitySystem

### ISSUE THREAD

**Issue by junkdog** [junkdog/artemis-odb#247]
for reasons discussed elsewhere.

**Comment by junkdog** [comment]
Slight perf regression + API could use some cleanup, otherwise done.

**Comment by DaanVanYperen** [comment]
Yay!

**Comment by junkdog** [comment]
If you have time/energy, feel like taking a look at the API? If nothing to abhorrent stands out, we can close this one.

I think the perf degradation may come from introducing an extra parent class; during the optimization step, I'm going to see if extending BaseSystem instead of EntitySystem makes a difference. Better handled in a different issue though.

**Comment by DaanVanYperen** [comment]
Taking a look! *beep*

**Comment by DaanVanYperen** [comment]
Applying it on contrib, it's already cleaning up the more exotic stuff. awesome!

- `<extend-configuration-property name="artemis.reflect.include" value="com.artemis.BaseSystem" />`
- Missing `changed` listener lacks replacement. Don't know if has any relevant usecases though.
- Mutability of actives on subscription (probably want to make it immutable if it's shared just to be sure).
- `ProfiledSystemsTest` is giving some asserts.
- Report breaking changes: 
 - `VoidEntitySystem` no longer subclass of `EntitySystem`.
 - Alternative for `EntitySystem#processEntities`
 - Deprecated listener methods.

Plus some javadoc and wiki ofc. ;)

**Comment by junkdog** [comment]
Thanks for taking a look (:cookie:).

> - Missing changed listener lacks replacement. Don't know if has any relevant usecases though.

Right now we have both EntityObserver and SubscriptionListener; they're a bit different, yet confusingly similar. For SubscriptionListeners, it doesn't really make sense to have a changed event since it has nothing to do with the subscription; changed entities are either inserted or removed. 

Hmm, but yes, it might make sense to incorporate changed(Entity) with subscribers for managers.

> - Mutability of actives on subscription (probably want to make it immutable if it's shared amongst subscribers, just to help find bugs when users refactor).

I'm leaning towards just adding a javadoc warning to `entities` and `activeEntityIds`; I could ofc add an ImmutableIntBag interface, but BitSet would require a wrapping class.

**Comment by DaanVanYperen** [comment]
> Right now we have both EntityObserver and SubscriptionListener; they're a bit different, yet confusingly similar. For SubscriptionListeners, it doesn't really make sense to have a changed event since it has nothing to do with the subscription; changed entities are either inserted or removed.

imagine a system that subscribes to an aspect and needs to know when a tangentially related component gets added. no insert or removal there. Still No clue if that's a common occurrence.

Probably want to detail `EntityObserver` and `SubscriptionListener` usecases a bit more in javadoc.

> leaning towards just adding a javadoc warning

And breaking changes note ;)

**Comment by junkdog** [comment]
> imagine a system that subscribes to an aspect and needs to know when a tangentially related component gets added. no insert or removal there. Still No clue if that's a common occurrence.

Hmm, this was never exposed through the old EntitySystems (changed(Entity) just called check(Entity), and all EntityObserver methods were marked as final).

**Comment by DaanVanYperen** [comment]
awesome, no loss there then!

**Comment by junkdog** [comment]
Still some polish left, but for various definitions of done, I'm closing this one.

**Comment by Namek** [comment]
> Alternative for `EntitySystem#processEntities`

which is...?

**Comment by Namek** [comment]
@junkdog ^^
