### ISSUE TITLE
Out-dated artemis-odb version?

### ISSUE THREAD

**Issue by nikoliazekter** [junkdog/artemis-odb#264]
I use Gradle to add artemis-odb to my project. A lot of files that exist in GitHub repo are missing in donwloaded library. For example, I can't use EntitySubscription and AspectSubscriptionManager. Isn't it time to update artemis-odb to 0.9.1?

**Comment by junkdog** [comment]
Hi, the roadmap for 0.10.0/1.0.0 strayed off course - it should have been out by now, but there are still several [changes remaining](https://github.com/junkdog/artemis-odb/issues?q=is%3Aopen+is%3Aissue+milestone%3Aartemis-0.10.0) before it's ready. I'm hoping artemis-odb develop can resume now that things have calmed down (we live in interesting times).

**Comment by nikoliazekter** [comment]
I'm pretty sastisfied with current version but I need to get bag of entities that have specific components. Currently I'm using getActives() but it generates a lot of garbage and hence is deprecated. How can I use EntitySubscription now? Do I need manually download EntitySubscription and AspectSubscriptionManager and put somewhere in my project source?

**Comment by DaanVanYperen** [comment]
@junkdog that's one long list!

@nikoliazekter @junkdog typically pushes out snapshots to the sonatype repo fairly regularly. If you are not production yet you could always fall back to those (currently `0.9.1-SNAPSHOT`).

```maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }```

**Comment by DaanVanYperen** [comment]
Answered! No action remains.
