### ISSUE TITLE
artemis-odb-debug - guard against common programmer errors

### ISSUE THREAD

**Issue by junkdog** [junkdog/artemis-odb#269]
EntitySystems' flyweight entity instance must never be stored in a collection, but it's easy to add them by mistake (the proper way is to resolve the actual entity instance with `world.getEntity(int entityId)` or just persisting the entity id.

- [x] create separate artemis-odb artifact with some introspective capabilities
- [x] throw an error when flyweights are stored in any `Bag<Entity>`
- [ ] pre-allocate pool of entities - to trigger NPE:s when referenced entities are deleted. see #291

adds some overhead; meant for resolving entity identity errors, not release builds.

**Comment by DaanVanYperen** [comment]
Might consider a debug build perhaps? If there is an elegant way to do such a thing. where's mah '#ifdef'!

**Comment by junkdog** [comment]
a pre-processor would rock - even if they're evil.

I want something similar to:

```xml
<dependency>
    <groupId>net.onedaybeard.artemis</groupId>
    <artifactId>artemis-odb</artifactId>
    <version>0.11.0</version>
    <classifier>debug</classifier>
</dependency>
```

The dep would prob be handled by a profile: if default profile, go with standard artifact - otherwise use the debug-classified (!) artifact.

**Comment by junkdog** [comment]
Ideally, it could be automated somehow - I've seen a few projects which do some fancy things to ones projects, just using referenced pom:s. Can't remember which however...

**Comment by DaanVanYperen** [comment]
It probably ties in closely to @Namek's efforts at tooling the engine. Especially with your world-io efforts making snapshots in a profiling setting an option.

**Comment by junkdog** [comment]
doesn't pre-allocate pool, can add it later - i think just checking for flyweights gone astray will intercept the majority of bugs. feel free to re-open ticket though, or a new one.
