### ISSUE TITLE
world save/load

### ISSUE THREAD

**Issue by junkdog** [junkdog/artemis-odb#271]
scrapping the previous design due to unwarranted complexity...

#### At a glance
- [x] Open up enough of artemis to allow for convenient retrieval (may already be done)
- [x] deserilize/serialize interface, with two provided implementations:
  - [ ] [kryo](https://github.com/EsotericSoftware/kryo)
  - [x] [JsonBeans](https://github.com/EsotericSoftware/jsonbeans)
- [ ] save/load custom data
- [x] entity references as ints (`@EntityId`).
- [x] version format

Both implementations provide custom deserializers interacting directly with the world instance.

**Comment by DaanVanYperen** [comment]
:+1:

**Comment by junkdog** [comment]
gdx and kryo deps are temp - they'll be moved to separate modules later.

**Comment by DaanVanYperen** [comment]
@junkdog would be great if this allowed for more atomic sub-world io (single entity to json and back for example, without managers and systems).

**Comment by junkdog** [comment]
Something like https://github.com/junkdog/artemis-odb/blob/master/artemis/src/test/java/com/artemis/io/EntitySerializerTest.java - or something else?

Or what do you mean by "without managers and systems"?

**Comment by DaanVanYperen** [comment]
Yeah, perfect!

I was under the impression it would be a full world serialization, with extra metadata.

**Comment by junkdog** [comment]
Nope, not limited to full serialization, I'll elaborate:

[SaveFileFormat](https://github.com/junkdog/artemis-odb/blob/master/artemis/src/main/java/com/artemis/io/SaveFileFormat.java) can be extended, as mentioned before. The fields declared in SaveFileFormat serve to map the smallest viable scaffolding for saving/loading a generic **set of entities** (`public final IntBag entities` is is populated in the constructor, either from a subscription or an IntBag of entities).

#### Json from [serializer_save_load_with_groups_and_tags](https://github.com/junkdog/artemis-odb/blob/d1312bac933bb52cfbfd2e52a3fa12666034b4a7/artemis/src/test/java/com/artemis/managers/JsonWorldSerializationManagerTest.java#L120):
```json
{
"metadata": {
	"version": 1
},
"componentIdentifiers": {
	"com.artemis.component.ComponentY": "1_ComponentY",
	"com.artemis.component.ComponentX": "0_ComponentX",
	"com.artemis.component.ReusedComponent": "2_ReusedComponent"
},
"entities": {
	"0": {
		"tag": "tag1",
		"groups": [
			"group1",
			"group2"
		],
		"components": {
			"0_ComponentX": {
				"text": "hello"
			},
			"1_ComponentY": {
				"text": "whatever"
			},
			"2_ReusedComponent": {}
		}
	},
	"1": {
		"components": {
			"0_ComponentX": {
				"text": "hello 2"
			},
			"1_ComponentY": {
				"text": "whatever 2"
			},
			"2_ReusedComponent": {}
		}
	},
	"2": {
		"tag": "tag3",
		"groups": [
			"group1"
		],
		"components": {
			"0_ComponentX": {
				"text": "hello 3"
			},
			"1_ComponentY": {
				"text": "whatever 3"
			},
			"2_ReusedComponent": {}
		}
	}
}
}
```

`metadata/version` doesn't do anything atm, but it's important to have version in there from the start. It's up to individual type serializers to manager their own versioning.

`componentIdentifiers` is only a lookup map; it has no bearing on the world itself (well, it can implicitly register new componentTypes, if they aren't already present).

There's nothing preventing, say, world1:entities to json, then load json into world2.

Entity keys (effectively id:s at the time of saving) are relative to the json file. At the moment, entity references (`@EntityReference` or com.artemis.Entity) aren't maintained: but when it is, the serializer tracks serializer-mapped entityId:s to newly created world's entityId:s.

**Comment by kotcrab** [comment]
I had to do my own serialization system for my editor, I will share some thoughts on it.

How are you going to handle components with non serializable resources like Sprite? I see that you can add your own serializers but that may be not enough. Deserializing Sprite would require data about it's asset and it may be stored in `AssetComponent`. You can't access `AssetComponent` from serializer.

For my editor I came up with my own solution: `ProtoComponents` and inflater systems. Problematic components implements `UsesProtoComponent` interface with one method: `getProtoComponent()` that during serialization must create `ProtoComponent` with all necessary data that will be used later to create actual component. 

Here comes inflater systems. After deserialization inflater uses data from  `ProtoComponent` to create actual component, and here is the best part: inflater is standard `EntityProcessingSystem`, it can easily access `AssetComponent`.

Some source examples:
[MusicComponent](https://github.com/kotcrab/VisEditor/blob/master/Runtime/src/com/kotcrab/vis/runtime/component/MusicComponent.java#L40-L43) [MusicProtoComponent](https://github.com/kotcrab/VisEditor/blob/master/Runtime/src/com/kotcrab/vis/runtime/component/MusicProtoComponent.java) [MusicInflaterSystem](https://github.com/kotcrab/VisEditor/blob/master/Runtime/src/com/kotcrab/vis/runtime/system/MusicInflaterSystem.java)

**Comment by junkdog** [comment]
There's actually no need for custom seriallizers regarding *transient* components (that's what I call un-serializable component types). 

I tend to bootstrap these components using managers. I wrote briefly about it in [#128-comment](https://github.com/junkdog/artemis-odb/issues/128#issuecomment-52243456). My asset components can always be represented textually.

In the project I'm currently working on, this allows for simple <kbd>CTRL</kbd>+<kbd>C</kbd>/<kbd>CTRL</kbd>+<kbd>V</kbd> on any entity in the world during runtime: all transient components are excluded during copying (`Renderable` etc), but once pasted - they're recreated from the Asset component.

Since I don't have a full-fledged editor built into the game, being able to paste the entity into a text editor before pasting it into the world again is pretty useful too (but, ofc, it's a work-around, but a pretty easy one).

**Comment by junkdog** [comment]
do we need to handle component fields referencing multiple entities? Only single entities per field allowed atm, either an `@EntityId int` or plain `Entity`.

**Comment by Namek** [comment]
array of entities? Quad-tree?

**Comment by junkdog** [comment]
Yeah, you're right, need to support:

```java
Bag<Entity>
@EntityId IntBag
```

**Comment by implicit-invocation** [comment]
Correct me if I'm wrong, but after a glimpse of the serializer source code, I can't find any logic concerned with entity creation and destruction.
I'm talking about cases like:

- we save all entities, delete one and load
- or we save all entities, create some more and load

And does world copying belong to the scope of serialization?
AFAIK kryo has a deep copy feature (which is much faster than the byte array serialization-deserialization combo).
The state we want to send over network must be serialized anyway.
But if we want to keep it local, or use it to load multiple time, I think we can benefit from deep copying.

**Comment by junkdog** [comment]
A bit short on time atm - trying to wrap up things before I go to bed, so sorry for not going into details, but:

- The serialization feature is more for saving/loading state (full or partial). Automatic deep-copying can't be performed due to how artemis stores components and tracks entity references.
  - For instance: it;s possible to "segment" loading over several files - the id:s reported by the json file/stream most likely won't match the id:s of those entities once created by the World.
- Deleting entities is handled by the user.
- EntitySerializer [creates](https://github.com/junkdog/artemis-odb/blob/master/artemis-json/src/main/java/com/artemis/io/EntitySerializer.java#L146) entities.
- The current jsonbeans backend is not suited for networked games - unless you're fine with sending an - for network purposes - unoptimized chunk of data each time.
- Future releases will add Kryo as an additional serialization backend, but still geared towards saving/loading.
- Future releases will also open up the serialization API - it's mostly package local atm, as we want to make sure the API is sufficiently flexible-yet-simple before making stuff public.

**Comment by implicit-invocation** [comment]
I have found the deleting and creating entity code so I did edit my comment and remove that part :) Guess you still see that part in the email notification.
I understand that we cannot copy the artemis world directly, but just like the way you do the serialization, we can do it with the SaveFileFormat.
