### ISSUE TITLE
Change components to be an interface

### ISSUE THREAD

**Issue by xaguzman** [junkdog/artemis-odb#272]
Is there any reason as to why the components are a class rather than an interface?

Since they don't even have specific properties or anything, I think it would come handy to make them an interface.

The reason being is that, when using libgdx, there are plenty of components created that are pretty just a Vector2, but you can't take advantage of the libgdx's built in math library in a clean way.
Take VelocityComponent or PositionComponent from the wiki as an example, they only contain x and y values.

I think the following 

```java
class Movement extends Component{
   Vector2 direction;
}

Movement mov = //....
mov.direction.sub( mov2.direction )
```

is much clearer if you 
```java
class Movement extends Vector2 implements Component {

}

Movement mov = //
mov.sub(mov2);
```

**Comment by junkdog** [comment]
I've thought about it before, but in the end decided against it:

- it'd mess up existing codebases
- polymorphic access slower than direct: this is one of the reasons why packed components don't really perform that well.

**Comment by xaguzman** [comment]
Would it be feasible to have both, a base class and an interface?

Just the same way java usuallly provides a Listener interface and an Adapter, which has an empty implementation of that interface.

For smaller projects, it is more convenient to have convenience over performance anyways.

That way, depending on the amount of entities / components that you will have in your game, you are free to choose performance or convenience.

**Comment by junkdog** [comment]
> Would it be feasible to have both, a base class and an interface?

AFAIK not without taking the performance hit. The component base class is just a marker, so there's no way to provide a "component adapter".

Pretty much all my components tend to resemble:

```java
@PooledWeaver
public class Position extends Component {
    public Vector2 xy = new Vector2();
}
```

... and then I retrieve them like this:

```java
Vector2 pos = positionMapper.get(e).xy;
```

**Comment by Namek** [comment]
Extending external libs' classes pollutes your code by creating strong dependency. You should always decouple things when possible. I'm not against interfaces but I wouldn't use them (for extending other classes) anyway, probably.

**Comment by junkdog** [comment]
Yeah, but in this case there's already a reference in the component itself. I would have preferred some notion of multiple inheritance in this case, or even the interface approach - only because it makes the resulting code slightly cleaner - but not at the cost of an unavoidable perf hit.

Java syntax/semantics doesn't really lend itself to data-driven code. I'm not a fan of the noise java inherently produces.
