### ISSUE TITLE
Wire caching, reflection slow on android

### ISSUE THREAD

**Issue by junkdog** [junkdog/artemis-odb#273]
as per @snorrees observation,

**Comment by DaanVanYperen** [comment]
Relevant discussion

> a little headsup on Injector performace: injecting thousands of instances takes quite some time on > android (seconds): by using a reflection cache i've speed up wireing by a factor of 4 - it also is measurable on desktop
> i'm still astounded by how slow reflection is on android
> junkdog Jul 19 22:12
> damn - sounds like it should be a task for 0.11.0/1.0.0.
> what are you injecting btw?
> snorrees Jul 19 22:13
> my entity-templates
> mind you, if i was to start over i probably would do it a bit diffrently, but by now its all legacy code 
> junkdog Jul 19 22:13
> ah! hmm, where do you jack in the reflection cache, and where do you generate it (compile-time?).
> snorrees Jul 19 22:14
> by simply caching annotation & field lookups things speed up bigtime
> junkdog Jul 19 22:14
> hehe, I have a pretty simple save/load API in mind for 0.11.0
> oh dear... too bad reflection handles never made their way into android.
> snorrees Jul 19 22:15
> oc, a compile time cache for wire stuff would be the ultimate, but i simply introduced multiple class > maps
> custom injector with map<class,type> sort of stuff, also with relevant fields cached
> on android especially annotations are about 100-1000 times slower
> no joke
> junkdog Jul 19 22:17
> blergh. android. and this is recent androids? i know pre-ICS had problems parsing annotations.
> snorrees Jul 19 22:17
> no its been this way forever - i've used reflection caches for my xml loading for a long time, but just > recently profiled load times
> the 10 second lagspike after my intial loadscreen which i've handwaved to being garbagecollection > turned out to be wire-reflection
> junkdog Jul 19 22:18
> i was thinking before about restructuring entity factories: the idea was to generate the > implementations at compile-time, but still allow for runtime implementations on desktop (otherwise, > the dev side of things crumbles).
> shit... that's pretty hefty indeed.
> snorrees Jul 19 22:19
> well, i guess you never intended for it to be used on 4k instances
> junkdog Jul 19 22:19
> cont entity factories: while entity factories were a bad fit for runtime generation. - wire could have > compile-time "backend" with a runtime fallback (the fallback being how it works today).
> hehe, nope, but still
> snorrees Jul 19 22:20
> that would be pretty nifty
> in my case i dont use entity-templates from current generation of artemis
> junkdog Jul 19 22:20
> the save/load functionality would be reflection-based too, but not using wire (except for > deserializers)
> snorrees Jul 19 22:20
> im behind the times 
> if you do the boilerplate of caching the class-based stuff (especially annotations) things are pretty > quick
> i mean, kryo works fine on android
> junkdog Jul 19 22:21
> the current dev version introduces some breaking changes, but i try to throw the appropriate error > messages w.r.t. deprecation.
> snorrees Jul 19 22:22
> im still at archtypes, and i dont think i will upgrade before the next project - just want to get shit done
> the code stinks, so better get it done before it all rots away
> junkdog Jul 19 22:22

> (hmm, i didn't mean for the emoji to look *that* happy)
> snorrees Jul 19 22:22
> "ill just use a static field, just this once"
> junkdog Jul 19 22:23
> 2 weeks later:
> "it'd be awesome to run two parallel game instances!"
> snorrees Jul 19 22:23
> exactly - thats just where i am today
> now its all much too late - so im just hunkering down and ignoring the pain
> junkdog Jul 19 22:24
> you can get around it with... `@Wire` and WorldConfiguration#register to some degreee.
> i tend to inject world-bound utility classes with register.
> sometimes it can be very nice to just leave a codebase behind... depends on the state of > subsequent project ofc. i've been restructuring projects all day.
> snorrees Jul 19 22:27

**Comment by junkdog** [comment]
i'm thinking this could be post-poned until 1.1.0 or such... I want to have some benchmarks in place first. Getting save/load and 1.0.0 out is more important atm.

**Comment by Namek** [comment]
You should never reach `1.0`! Like libgdx for most of the time, hehe.

**Comment by junkdog** [comment]
But, but... all those deprecated methods need to die.

**Comment by snorrees** [comment]
Made a WiP pull-request for injection-cache.

**Comment by DaanVanYperen** [comment]
Fixed by #284
