### ISSUE TITLE
[WorldConfiguration] system/manager getters

### ISSUE THREAD

**Issue by DaanVanYperen** [junkdog/artemis-odb#275]
Missing some basic system/manager getters on worldconfiguration. Might be desirable for users that have a more spread out world initialization.

**Comment by junkdog** [comment]
prob good to add, but do you think it's necessary?

#### pro:
- getters make sense

#### con:
- i'm entertaining moving to a completely `.class` based system/manager initialization, it'd make it easier to serialize the world configuration. inject all resources with `@Wire` during world ctor.

**Comment by DaanVanYperen** [comment]
Smaller API maintainable API. Could leave it out for now.

Can you elaborate class based system/manager initialization? Given people mix/match based on context and preconditions, (screens, server/client, settings).

**Comment by junkdog** [comment]
```java
WorldConfiguration wc = ....
wc.setManager(TagManager.class); // etc
```

Instantiating everything from a clean state at World ctor would make stronger guarantees concerning saving/loading the entire WorldConfiguration (not possible atm) - but that might be hard to pull off in practice anyway.

During init we usually now which systems/managers are required anyway - calling getSomething seems like a rather circumstantial use-case.

**Comment by DaanVanYperen** [comment]
Do we need to save the WorldConfiguration? All state should be entity side of things.

Speaking for myself, there are some things that should probably not be system parameters (like camera object), but some others that probably should be (like network  strategy into marshal system, or relationships between modular system/subsystems).

**Comment by junkdog** [comment]
> Do we need to save the WorldConfiguration?

Yeah, not sure whether it makes sense, because - like you point out - camera's etc would still require registering with WC.

**Comment by DaanVanYperen** [comment]
Only reason I can think of would be for really high level implementations, like a game designer. It's fine leaving the developer /some/ responsibility ensuring a sane system state and storing any variance as a component.

**Comment by junkdog** [comment]
hmm.... WorldConfiguration doesn have core managers - they're fetched from the world.

#### SitRep:
- getSystems() and getSystem(Class) are easy
- getManagers() would return element 0, 1 and 2 as null
- getManager(Class) would work for all but ComponentManager, EntityManager and AspectSubscriptionManager.

So... is it worth it? We could refactor, but it feels like the use-case is rather limited.

**Comment by Namek** [comment]
woah, hey, don't kill access to my precious :gift_heart: `AspectSubscriptionManager`!

**Comment by junkdog** [comment]
don't worry, it's only during WorldConfiguration - once the world is initialized, you can get systems and world as usual. this only affects the moments before the world has been created (a holy act).

**Comment by DaanVanYperen** [comment]
On second thought, too much of an edge case, lets wait for actual use cases to surface! *boop*
