### ISSUE TITLE
EntitySubscription should deal with IntBag of entityIds, not Bag of Entities.

### ISSUE THREAD

**Issue by junkdog** [junkdog/artemis-odb#277]
Saves memory, makes certain checks easier/faster.

**Comment by Namek** [comment]
Even more performance!

**Comment by Namek** [comment]
:cookie:

**Comment by junkdog** [comment]
:exclamation: 
:hatched_chick:

**Comment by DaanVanYperen** [comment]
Are you dropping `Entity` eventually?

**Comment by junkdog** [comment]
That would be nice, but java doesn't really expose the necessary language constructs/semantics to make it feasible. I'm trying to replace Entity with int as much as possible behind the scenes.

If rebuilt from scratch, I'd completely skip the entity class.

**Comment by DaanVanYperen** [comment]
Ok. No opinion here either way, just polling!

**Comment by snorrees** [comment]
Just wait for Java 10 and project Valhalla.

**Comment by junkdog** [comment]
I was hoping it'd find its way into java 8... feels like value types have been in the experimentation phase for [quite some time](http://medianetwork.oracle.com/video/player/1785452137001) already.
