### ISSUE TITLE
Bump Entity.createFlyweight(world) visibility

### ISSUE THREAD

**Issue by DaanVanYperen** [junkdog/artemis-odb#278]
Cannot create flyweight in BaseSystem, not allowed due to package-private. Possibly intended to be public?

```java
Entity.createFlyweight(world);
```

**Comment by junkdog** [comment]
Ok, I got your use-case now - BaseSystems with multiple entity subscriptions (since many, extending EntitySystem) doesn't make sense. Am I right? I'll move it to BaseSystem in that case.

**Comment by DaanVanYperen** [comment]
Correct!

**Comment by junkdog** [comment]
Feel free to migrate the method; I'm in the middle of a spring planning session.

**Comment by junkdog** [comment]
:cookie: :smoking: :wine_glass:

**Comment by Namek** [comment]
How do I create flyweight in `Manager`? I have my own `TagManager`, since the current one stores `Entity` references instead of IDs.

**Comment by DaanVanYperen** [comment]
@Junkdog should just make it public really.

**Comment by Namek** [comment]
I think this one should be just public:
`static Entity createFlyweight(World world)`

Artemis isn't the only world when you may need store your ID.
