### ISSUE TITLE
Proposal: Hook into DI pass

### ISSUE THREAD

**Issue by DaanVanYperen** [junkdog/artemis-odb#283]
I would like to be able to extend Injector#injectField somehow so I can smart inject distinct loggers per system.  

Can make my own DI pass of course, prefer to piggyback to avoid loads of redundant reflection. Let me know what you prefer. (perhaps pass custom strategy on config, call on injectField fail?)

```java
private Logger logger = new Logger("VehicleEjectSystem", Logger.INFO);
```
to 
```java
@Wire
class VehicleEjectSystem {
        private Logger logger;
}
```

**Comment by junkdog** [comment]
why do you need distinct loggers per system?

So, basically: another approach to injecting named wireables. How do we deal with different logging frameworks?

**Comment by DaanVanYperen** [comment]
Well this is just this usecase, which isn't going to have common application, I'm mainly looking for an  extensible solution where I can get too smart for my own good.

**Comment by DaanVanYperen** [comment]
Another example use case would be: FlavoredComponentMapper<Cheese>

**Comment by junkdog** [comment]
> I'm mainly looking for an extensible

Yeah, that's what I meant.

**Comment by DaanVanYperen** [comment]
> Yeah, that's what I meant.

well code it already! SLACKER!

**Comment by junkdog** [comment]
but i don't have any CONCRETE SPECS!!!11!1one

optionally bind a typed instance (Logger) to instances of an artemis-injected  typed (SpriteSystem)? sub-classes are doable, but maybe a bit difficult to get right.

**Comment by DaanVanYperen** [comment]
Who needs specs.

![](http://i2.wp.com/tamingdata.com/wp-content/uploads/2010/07/tree-swing-project-management-large.png)

**Comment by DaanVanYperen** [comment]
Covered by #284
