### ISSUE TITLE
Responding to component data changes

### ISSUE THREAD

**Issue by mtsr** [junkdog/artemis-odb#292]
How would you deal with the following?

For a mouse picking system with lots of pickables, I want to keep the entities in a quad-tree by their position as an optimisation. The quad-tree needs to be updated when the position component changes. Ideally I would like to not check every entity during every update, but only check those with a dirty position component.

My ideas so far:
* keeping a dirty flag on the position component that gets set by a setter and reset by the quad tree update;
* making the component 'Observable' (custom, because Observable is a class, not an interface) and making the quad tree an observer.

Any suggestions?

**Comment by junkdog** [comment]
> How would you deal with the following?

Depending on how often entities change position, either play it simple and always check whether the positon has been updated, or - cleaner - toggle a component (DirtyPosition.class - no fields). Possibly toggle position with a pair of [EntityTransmuters](https://github.com/junkdog/artemis-odb/wiki/Entity#entity-transmuters).

PS. I'll attend to #291 after work.

**Comment by DaanVanYperen** [comment]
If you implement an odb quad tree solution I'd love a PR to https://github.com/daanVanYperen/artemis-odb-contrib.

Alternatively to @junkdog's suggestion you could consider delegating collision checking to a framework like box2d.

**Comment by mtsr** [comment]
I guess you've likely seen it in the gitter, but I still want to link it for reference, @piotr-j made this:
https://github.com/piotr-j/libgdxplayground/tree/master/core/src/io/piotrjastrzebski/playground/ecs/quadtreetest

**Comment by piotr-j** [comment]
Ill PR something once im happy with implementation. Comments welcome.

**Comment by DaanVanYperen** [comment]
@piotr-j system implementations are best PRed to artemis-odb-contrib.

Users probably want to use their own pos/etc components, if you could make an abstract system with no forced components that would be preferred!

**Comment by piotr-j** [comment]
Of course, just need to get it to work nicely first. Im not certain specialized system is required, at best it calls just a few methods. Perhaps a quad tree that works with entity ids would be enough.

**Comment by DaanVanYperen** [comment]
@piotr-j awesome!

**Comment by DaanVanYperen** [comment]
Closing since no further odb specific action remaining. Feel free to bump if needed.
