### ISSUE TITLE
public and extensible serialization API

### ISSUE THREAD

**Issue by junkdog** [junkdog/artemis-odb#304]

**Comment by SacWebDeveloper** [comment]
Is there any reason why the [Json Serialization](https://github.com/junkdog/artemis-odb/wiki/Json-Serialization) documentation is missing a reference to **WorldSerializationManager#setSerializer()**?  Without an **ArtemisSerializer**, I was getting a NullPointerException.

```
WorldConfiguration worldConfig = new WorldConfigurationBuilder()
				.with(new WorldSerializationManager()).build();

world = new World(worldConfig);

worldSerializationManager.setSerializer(new JsonArtemisSerializer(world));
```

It should be noted that **WorldSerializationManager#setSerializer()** must be called before **WorldSerializationManager#save()**. If you want, I could add this.

I'm not working with GWT, only Desktop and Android at the moment, so if this is not needed in GWT, the difference should be noted.

**Comment by junkdog** [comment]
> By the way, that should be changed to "see #setSerializer."

Oops, lingering from an earlier implementation.

Hmm, I thought it was documented, but it seems I was wrong. Setting the serializer is a prerequisite, and should be documented.

**Comment by SacWebDeveloper** [comment]
There, I added the documentation for registering the serializer and I clarified the setup for basic setup vs. GWT.

**Comment by junkdog** [comment]
Awesome, thanks! ;)
