### ISSUE TITLE
EntitySubscription-centric manager for bootstrapping transient components

### ISSUE THREAD

**Issue by junkdog** [junkdog/artemis-odb#306]

**Comment by DaanVanYperen** [comment]
Shouldn't a users systems/managers already do this by means of the existing create/update/delete callbacks? (populate transient aspects of component model?)

**Comment by junkdog** [comment]
More of a utility manager to cut down on some boilerplate. I think I had something more specific in mind, but can't remember what atm...

**Comment by DaanVanYperen** [comment]
Something like https://github.com/DaanVanYperen/artemis-odb-contrib/blob/develop/contrib-core/src/main/java/net/mostlyoriginal/api/manager/AssetManager.java
?

**Comment by junkdog** [comment]
yes, something similar - or go with DI.

I tend to keep the assets reference components. they're handy to keep when serializing.

**Comment by junkdog** [comment]
closing this as it's too easy to roll in project code; not all use-cases necessarily fit it, so I'll just leave it be. This is what I'm doing in the current project:

```java
        util.subscription( // util = EntityUtil extends Manager
            all(Size.class, TextureReference.class),
            new SubscriptionAdapter(world) {
                @Override
                protected void inserted(Entity e) {
                    assignSprite(e, textureReferenceMapper.get(e));
                }
            });
```
