### ISSUE TITLE
@PooledWeaver and @PackedWeaver on one component

### ISSUE THREAD

**Issue by DaanVanYperen** [junkdog/artemis-odb#307]
Should not be allowed.

**Comment by antag99** [comment]
These annotations could be replaced by something like `@Weave(Taxonomy.POOLED)`; this would implicitly disallow multiple weavers.

**Comment by DaanVanYperen** [comment]
Torn! Single word annotations more intuitive and legible at a glance, but I like the elegance.

**Comment by antag99** [comment]
Yet another idea is to annotate the weavers with `@Weave`;

```java
@WeaverTaxonomy(Taxonomy.PACKED)
public @interface PackedWeaver {
}
```

But then it's probably better to just make the weaver use maps of annotation type -> weaver class & metadata.
Those implementation details are however only the business of  @junkdog; no public API changes there.
I just think we should generalize the idea; who knows when some new magic component types are invented?

**Comment by DaanVanYperen** [comment]
Got to keep in mind public API changes like this are a pain in the butt for users, Might be nice for 1.0 though, people'll have to bite the bullet there anyway.

**Comment by junkdog** [comment]
Isn't it better if we instead can automate(/force) weaving, even w/o the weaver annotations? Pooled/Packed can be resolved automatically. `@PackedWeaver` and `@PooledWeaver` can be used to override the automatic resolver - as suggested in another issue. It's the least invasive approach imo.

The WeaverTaxonomy on PooledWeaver/PackedWeaver is pretty nice too, but it's unlikely that we'll end up with more component types in the near future.

**Comment by DaanVanYperen** [comment]
Only use case of per-component configuration I know is feature detection like in quickstart. Packed is a bit of a non feature now anyway. Build configuration then?

**Comment by DaanVanYperen** [comment]
Covered by #186

**Comment by DaanVanYperen** [comment]
Out of scope or in need of sponsor.
