### ISSUE TITLE
Strip entity counters out of EntityManager

### ISSUE THREAD

**Issue by DaanVanYperen** [junkdog/artemis-odb#311]
Replace with specialized manager.

https://github.com/junkdog/artemis-odb/commit/e1492ccb0b193609c06cbc720b47de18377e8a9f#commitcomment-12599417

**Comment by junkdog** [comment]
Do we really need the specialized manager for tracking entity counts? Feels like it's trivial to roll your own, while not really ever needed by anyone. Thoughts?

**Comment by DaanVanYperen** [comment]
Suggestion in breaking changes would suffice I'd say.
