### ISSUE TITLE
GWT world-io

### ISSUE THREAD

**Issue by junkdog** [junkdog/artemis-odb#316]

**Comment by DaanVanYperen** [comment]
I'll take a look at it after work.

**Comment by junkdog** [comment]
:+1: - with promises of :cookie: :cookie: :cookie: 

Does the llbgdx gwt backend even expose writing to local storage? Can still use a webservice for saving/loading ofc.

**Comment by DaanVanYperen** [comment]
We can provide javascript if needed. It's likely we'll need to do some work though unless you've encapsulated all the reflection in the json framework.

**Comment by DaanVanYperen** [comment]
For anyone reading along, world-io GWT support currently nonexistent, when io api is a bit more mature  will have to make gwt specific solution.

**Comment by junkdog** [comment]
well, yeah, GWT maybe wasn'texpected to work - but shit, java.io support sucks. apart from having another gwt module, comforting to have some better coverage (dual-edged sword, I suppose).

I've thought about ditching junit 4, but... GWT... get your annotations in order.

**Comment by DaanVanYperen** [comment]
Any constraints for implementing this? Did you happen to make any high level notes or sketches about the io system for work?

Concerning GWT coverage, reflection and io related is all we really need. Beyond that not too worried about the rest, any other issues typically show up compile time for me.

**Comment by junkdog** [comment]
No notes. I think it can be tricky to emulate jsonbeans fully; I'm thinking about the [custom type serializers](https://github.com/junkdog/artemis-odb/blob/d9d7421fe370ff92f37b05db24feab5e76f41eff/artemis-json/src/main/java/com/artemis/io/JsonArtemisSerializer.java#L49) mainly.

The existing [type serializers](https://github.com/junkdog/artemis-odb/tree/d9d7421fe370ff92f37b05db24feab5e76f41eff/artemis-json/src/main/java/com/artemis/io) cover many use-cases - but don't really integrate all that well with libgdx (Array), so expect user-defined serializers. Could be tricky to pull off - but awesome if it's feasible.

**Comment by DaanVanYperen** [comment]
LibGDX Json supports GWT right? Isn't that basically Jsonbeans equivalent? Same story as GWT support, could just clone it.

**Comment by junkdog** [comment]
Ah... lucid thinking. Yes, I believe/hope that to be the case.

**Comment by DaanVanYperen** [comment]
Can take a stab at it after work, gives me a chance to peek at the new cogs and sprockets.

**Comment by junkdog** [comment]
Aight! I'm pushing 0.11.2 - turns we had duplicate ComponentNameComparator class in world-io-json. Breaks android builds.. meh.

**Comment by DaanVanYperen** [comment]
don't forget to knit your PGP info into a sock for when things break during your vacation. ;)

**Comment by junkdog** [comment]
I'm sure I can ask NSA for a copy, should I need it.

**Comment by DaanVanYperen** [comment]
covered by #319
