### ISSUE TITLE
IntervalEntitySystem with empty aspect

### ISSUE THREAD

**Issue by edvorg** [junkdog/artemis-odb#318]
There is no way to create this kind of system, because Aspect.getEmpty() is deprecated.
We solved it in our project by creating IntervalBaseSystem with same functionality as IntervalEntitySystem, but it breaks dry principle.

**Comment by junkdog** [comment]
Empty aspect would match *all* entities though: in effect the same as instantiating an aspect without providing any types for all/one/exclude (it's a bit promiscuous like that).

If you want to run the system on all entities, do pass `Aspect.all()` to the parent ctor. You could of course go with `Aspect.exclude()` or `Aspect.one()` too - but it's a bit awkward to read.

**Comment by DaanVanYperen** [comment]
@edvorg would you mind give some background info, I'm interested to know what the practical use case is for such a system!

**Comment by edvorg** [comment]
We use IntervalEntitySystem for some global state like game timer or entity spawner.
Thank you for your answer!
