### ISSUE TITLE
Provide alternative json serializer via libgdx

### ISSUE THREAD

**Issue by junkdog** [junkdog/artemis-odb#319]
Most of us use libgdx anyway. The current implementation doesn't provide default type serializers for some common libgdx classes - we'd get those for free if we also have a artemis-json-libgdx module. Mostly a matter of copy-pasting and updating packages and a few class names.

- [x] create `artemis-serializer-backends` module - hosts all backends (json, json-libgdx, kryo etc)
- [x] move `artemis-json` to  `artemis-serializer-backends`
- [x] copy-paste, update-rename classes from `artemis-json`
- [x] working gwt integration tests

**Comment by DaanVanYperen** [comment]
Probably want to keep it one backend per module, to avoid dependency soup.

**Comment by DaanVanYperen** [comment]
Picking this up. Important side-note though is that users will have to register their classes with LibGDX reflection.

**Comment by DaanVanYperen** [comment]
found some gwt emu's of io classes. :D

**Comment by DaanVanYperen** [comment]
Waiting for #329

**Comment by DaanVanYperen** [comment]
Closed via #342
