### ISSUE TITLE
Resolve schism with libgdx

### ISSUE THREAD

**Issue by DaanVanYperen** [junkdog/artemis-odb#321]
The double reflection cache is really undesirable on GWT, goal being small games. (4 MiB java file per cache easily, not certain about the JS side of things). Given all the confusion it might cause io users maybe we could brainstorm a bit about a solution,

**Comment by junkdog** [comment]
damn - where are all those bytes coming from - text? Could proguard be convinced to do reflection-safe obfuscation; as in, shortening all class and method names, but correctly intercepting reflection calls? Probably not.

**Comment by DaanVanYperen** [comment]
It's just really verbose. Should probably figure out how big it gets on the JS side, imagine there might be some packing going on there.I'd really love giving the GWT reflection generator a refactor,

**Comment by junkdog** [comment]
> I'd really **love** giving the GWT reflection generator a refactor,

You feeling ok?

**Comment by DaanVanYperen** [comment]
uh. I should say, it would be really fulfilling when finally done.  ;)

**Comment by DaanVanYperen** [comment]
Know of any way we can create artifacts with/without libgdx? There must be reference projects out there that do something like that.

**Comment by junkdog** [comment]
classifiers - the problem is, i guess, creating them; selecting the correct resources etc: what do we need to change in the artifact when jacking into libgdx dirdctly - an alternate gwt.xml and a provided libgdx dependency?

**Comment by DaanVanYperen** [comment]
In that case we'd replace our duplicate code with libgdx and package a libgdx-minimal module with the features we reuse. on Artemis side it would be stable. Just an extra artemis-faux-libgdx dep for libgdxless users.

Still not a big fan, already feel our package structure is getting complicated. We'd also have to keep in step with libgdx.

Alternatively
- pulling libgdx's json into the fold so we can use our own reflection. You could drop json beans vanilla since it's basically the same implementation.
- Smart reflection cache generator that produces gdx refcache adapter if gdx on classpath? 
- just leaving it. ;)

**Comment by junkdog** [comment]
> Still not a big fan, already feel our package structure is getting complicated.

You mean modules/artifacts, right - not packages per se?

Yeah, might hide some modules under sub-modules/folders, but it's not ideal. Building separate artifacts based around classifiers may keep the module count down, but we're still making it slightly more complicated for end-users.

> You could drop json beans vanilla since it's basically the same implementation.

But not quite - we'd force libgdx down people throats if we go that route. Some interfaces/classes are slightly different - aside from the package names.

> Smart reflection cache generator that produces gdx refcache adapter if gdx on classpath?

Doable, or just a lot of extra work? I can see that go either way.

I'm rambling.

**Comment by DaanVanYperen** [comment]
> You mean modules/artifacts, right - not packages per se?

sorry, yes, modules/artifacts.

> But not quite - we'd force libgdx down people throats if we go that route. Some interfaces/classes are slightly different - aside from the package names.

I'm not against keeping both implementations, just thinking about the effort better spent ;) 

We'd provide cross platform json, cross platform being one of odb's selling points, It would be decoupled from libgdx? We already force people to use libgdx reflection.

> Doable, or just a lot of extra work? I can see that go either way.

I would call it deceptively easy, with a high chance of gotcha.

**Comment by junkdog** [comment]
> We'd provide cross platform json, cross platform being one of odb's selling points, It would be decoupled from libgdx? We already force people to use libgdx reflection.

Only on GWT though - does it work with PlayN?

Main point of not coupling with libgdx is to not deter any lwjgl, jmonkeyengine and PlayN users - by giving the impression that it's tightly coupled with libgdx (though I think that 5% or something).

Good thing about jsonbeans/libgdx's json impl is the fact that it's fairly stable. Code hasn't changed much over the past few years. Keeping two separate copy-pastas shouldn't add much overhead.

> I would call it deceptively easy, with a high chance of gotcha.

Good thing GWT is so straight forward!

**Comment by DaanVanYperen** [comment]
> Only on GWT though - does it work with PlayN?

Yes. https://github.com/DaanVanYperen/playn-artemis-quickstart

> Main point of not coupling with libgdx is to not deter any lwjgl, jmonkeyengine and PlayN users - by giving the impression that it's tightly coupled with libgdx (though I think that 5% or something).

We use minimal parts to obtain cross-platform capability. Doubt non-libgdx users even realize the reflection code stems from libgdx? 

We could manually integrate our reflection layer with jsonbeans, but then we'd end up close to the libgdx' implementation anyway.

> Good thing GWT is so straight forward!

1 point for a working delegate, 21 points for reliably detecting existence of libgdx reflectioncache and configuring the package. ;)

**Comment by DaanVanYperen** [comment]
> Yes. https://github.com/DaanVanYperen/playn-artemis-quickstart

Also notice the huge number of stars. Sometimes I wonder if i'm the only GWT user. :p

**Comment by junkdog** [comment]
I get the feeling PlayN has a very different audience? I never "see" PlayN devs, yet they used to have plenty of stars on google code - [only 43](https://github.com/playn/playn) on gh thus far though.

**Comment by DaanVanYperen** [comment]
Where have the GWT warriors of old gone *wink* @Flet

**Comment by DaanVanYperen** [comment]
> I never "see" PlayN devs, yet they used to have plenty of stars on google code

I wonder what motivates people in selection of their java game framework nowadays.

**Comment by junkdog** [comment]
Most seem to divide between jmonkey, libgdx and lwjgl - at least that's the feeling I get.

From what I understand, they're pretty similar - libgdx and playn, but I haven't looked closer.

**Comment by DaanVanYperen** [comment]
I agree having Artemis decoupled makes sense. Having the json-libgdx implementation in core breaks the impartiality a bit, but I'd hate to not have full coverage.

Btw figured we might be worth exploring GWT version of @PooledWeaver, see if pooled affects performance on that platform.

**Comment by Namek** [comment]
@junkdog http://playn.io/gallery/ -> 404

**Comment by junkdog** [comment]
Pooled on GWT - interesting! I have no idea about how GC usually works with JS. We need a benchmark - how's your space-looking thing coming along?

@Namek I know ;( - they had ~2k stars on google IIRC.

**Comment by DaanVanYperen** [comment]
still seems to be a trickle https://groups.google.com/forum/#!forum/playn

> how's your space-looking thing coming along?

waiting idly for some love!

**Comment by DaanVanYperen** [comment]
Groomed issues worth revisiting later. Out of scope or in need of sponsor.
