### ISSUE TITLE
Artemis 0.10.1 does not @Wire in abstact systems

### ISSUE THREAD

**Issue by edvorg** [junkdog/artemis-odb#322]
I have an abstract class derived from BaseSystem with some common logic for few systems in our project. This abstract class tries to wire some fields, but it doesn't work, because artemis injector gets only declared fields of class but doesn't look at superclass.

**Comment by DaanVanYperen** [comment]
You are looking for `@Wire(injectInherited=true)` perhaps?

**Comment by edvorg** [comment]
Yes it works, thank you!

**Comment by DaanVanYperen** [comment]
Awesome! good luck.
