### ISSUE TITLE
@Wire as convention

### ISSUE THREAD

**Issue by DaanVanYperen** [junkdog/artemis-odb#328]
`@Wire` has become convention. It enables one of the core selling points of ODB. For 1.0, perhaps its time to remove the requirement and add an inverse annotation instead.

- [x] default to `@Wire` for odb (and plugin managed, contrib `M<Pos>` example) types.
- [x] flip precedence of `@SkipWire` when `@Wire` becomes the default, right now Wire supersedes.

**Comment by nikoliazekter** [comment]
What do you mean by inverse annotation? Google doesn't give any results.

**Comment by antag99** [comment]
@nikoliazekter Something like an `@Ignore` annotation, that excludes a field/whole class.

**Comment by Namek** [comment]
`@DoNOTWireArtemisHereOrIWillFeelBadAboutYou` - this one would be pretty noticable.

**Comment by antag99** [comment]
Why not "@Namek"? (@Wire has suffered enough.)

**Comment by Namek** [comment]
Because :copyright:

**Comment by DaanVanYperen** [comment]
Are you suggesting @Namek is not wired? :P

**Comment by junkdog** [comment]
So, we'd still need `@Wire` for non-artemis types, but otherwise, everything is automatic? I'd like some perf profiling on android - if the hit isn't too big, let's go with it.

**Comment by snorrees** [comment]
I think it will be fine. As long as the number of instances injected are in the amount of 10-100 there should be no problems. Its when you start doing injection for everything these things matter.

I can take this for a spin on my current codebase and report back later if you want? I still have systems with @Mapper annotations o_O, so I think I represent the legacy users.

**Comment by junkdog** [comment]
hehe, `@Mapper` will go away with 1.0.0

**Comment by junkdog** [comment]
Hmm, i'll attend to this tomorrow.
