### ISSUE TITLE
GWT error while non-draft compiling a game with 0.11.4

### ISSUE THREAD

**Issue by DaanVanYperen** [junkdog/artemis-odb#329]
```
      [ERROR] Errors in 'jar:file:/C:/Users/Daan/.gradle/caches/modules-2/files-2.1/net.onedaybeard.artemis/artemis-odb/0.11.4/23077fd03ef9a294e85396756df15e9af157c719/artemis-odb-0.11.4-sources.jar!/com/artemis/managers/WorldSerializationManager.java'
         [ERROR] Line 30: The method markSupported() is undefined for the type InputStream
```

**Comment by antag99** [comment]
*mandatory GWT hate goes here*

**Comment by DaanVanYperen** [comment]
Came across this at 02:30 while trying to final build for LD XD

**Comment by DaanVanYperen** [comment]
Would be great if we can push this as a bug release when fixed.

**Comment by junkdog** [comment]
I'll have a look at it today - any easy way to trigger it? I'm assuming this happens even though serialization isn't used, as the GWT backend isn't complete yet.

**Comment by junkdog** [comment]
> Would be great if we can push this as a bug release when fixed.

Will do.

**Comment by DaanVanYperen** [comment]
https://github.com/DaanVanYperen/libgdx-artemis-quickstart/releases
`compile html:dist`

is the easiest probably. Only need to set it to snapshot in the main gradle.

**Comment by junkdog** [comment]
We'll just emu it for now and send a PR on libgdx. they have a bug in their file handles too.

**Comment by DaanVanYperen** [comment]
Not sure how GWT handles clashes in emu classes, or I'd PR a corrected InputStream ;)

**Comment by DaanVanYperen** [comment]
Resolved, thanks!
