### ISSUE TITLE
recycle entities in FIFO order

### ISSUE THREAD

**Issue by junkdog** [junkdog/artemis-odb#331]

**Comment by snorrees** [comment]
Perhaps you could walk me through these changes; might spark some insight into why its breaking stuff on my end.

**Comment by DaanVanYperen** [comment]
Looks like odb now revives longest dead entities first, instead of shortest dead. 

IntDeque has a bit of a smell in that regard, might be wrong but what happens when the round robin begin index is near the tail of the array and it grows? will it start popping nulls?

**Comment by snorrees** [comment]
I'll do a trace on entityids coming out of my entityFactory and report back.

**Comment by snorrees** [comment]
Spawning: rotatingGunBase
id: 120
MazeEntityCreator: Creating obstacles for group: com.tank.maze.group.RandomizedGroupTemplate
Spawning: rotatingGunBase
id: 107
MazeEntityCreator: Creating obstacles for group: com.tank.maze.group.RandomizedGroupTemplate
MazeEntityCreator: Creating obstacles for group: com.tank.maze.group.RandomizedGroupTemplate
MazeEntityCreator: Creating obstacles for group: com.tank.maze.group.RandomizedGroupTemplate
MazeEntityCreator: Creating obstacles for group: com.tank.maze.group.RandomizedGroupTemplate
Spawning: mid_block_box
id: 118
Spawning: mid_block_box
id: 43
Spawning: mid_block_box
id: 0
Spawning: mid_block_box
id: 0
Spawning: mid_block_box
id: 0
MazeEntityCreator: Creating obstacles for group: com.tank.maze.group.RandomizedGroupTemplate
MazeEntityCreator: Creating obstacles for group: com.tank.maze.group.RandomizedGroupTemplate
MazeEntityCreator: Creating obstacles for group: com.tank.maze.group.RandomizedGroupTemplate
Spawning: box
Spawning: box
Loading: Populating level...
Loading: Creating user interface...
Loading: Initializing AI...

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
id: 0
id: 0

**Comment by DaanVanYperen** [comment]
Yeah looks like it's returning empty part of the graveyard. XD

**Comment by snorrees** [comment]
Modified 0.13.0-SNAPSHOT to report directly:

> MazeEntityCreator: Creating obstacles for group: com.tank.maze.group.RandomizedGroupTemplate
Spawning: rotatingGunBase
popping limbo - entity id: 100
Spawning: rotatingGunBase
popping limbo - entity id: 128
Spawning: rotatingGunBase
popping limbo - entity id: 142
MazeEntityCreator: Creating obstacles for group: com.tank.maze.group.RandomizedGroupTemplate
MazeEntityCreator: Creating obstacles for group: com.tank.maze.group.RandomizedGroupTemplate
MazeEntityCreator: Creating obstacles for group: com.tank.maze.group.RandomizedGroupTemplate
MazeEntityCreator: Creating obstacles for group: com.tank.maze.group.RandomizedGroupTemplate
Spawning: mid_block_box
popping limbo empty - entity id: 10
Spawning: mid_block_box
popping limbo - entity id: 0
Spawning: mid_block_box
popping limbo - entity id: 0
Spawning: mid_block_box
popping limbo - entity id: 0
MazeEntityCreator: Creating obstacles for group: com.tank.maze.group.RandomizedGroupTemplate
Loading: Populating level...
Loading: Creating user interface...
Loading: Initializing AI...
popping limbo - entity id: 0
popping limbo - entity id: 0

**Comment by snorrees** [comment]
Entities with id 0 are being returned to the queue.

**Comment by DaanVanYperen** [comment]
Yeah, graveyard is a round robin queue like:

`100, 128 (head), 142`, size=3

Then it gets resized

`100, 128 (head), 142, 0, 0, 0`, size=3

Causing zeros to be dequeued eventually. and probably id's lost as well.

**Comment by snorrees** [comment]
Yup, there are big strips of 0's in the middle of the queue.

**Comment by DaanVanYperen** [comment]
this queue works like bag really, seems like missed case due to RR.

**Comment by snorrees** [comment]
Gtg - but at least we have identified the problem.

**Comment by junkdog** [comment]
pushed a snapshot to sonatype. I gtg too, but i'll make sure to release a 0.12.1 build sometime later today/tonight.

**Comment by snorrees** [comment]
Tested the snapshot, and I can confirm that this fixes the problem at my end. 

:cookie: :cookie: :cookie:

**Comment by junkdog** [comment]
awesome! 0.12.1 is published too.

**Comment by snorrees** [comment]
Thanks! Imagine if enterprise turnaround was this quick!

**Comment by junkdog** [comment]
> Imagine if enterprise turnaround was this quick! 

Not before stacktraces fit on a single screen... (I could have said "not until the heat death of the universe", but I went with something equally outlandish).
