### ISSUE TITLE
Allow non-zero-arg ctor on components

### ISSUE THREAD

**Issue by junkdog** [junkdog/artemis-odb#337]
- default to using zero-arg ctor (as it currently works)
- otherwise match first reported ctor (this is somewhat prone to error, but unless we want to introduce another annotation, it's the only way)
- ctors with parameters are invoked with default values: null, 0, and false.

This affects `EntityEdit#create` and deserialization.

**Comment by antag99** [comment]
Have you taken a look at objenesis? Could be a better choice, at least under desktop/android.

**Comment by junkdog** [comment]
Heard of it before, but I don't want to introduce a dependency on core. Our use-case is simple enough anyway as it is; more effort to evaluate objenesis than roll it from scratch.

**Comment by junkdog** [comment]
ice-boxing
