### ISSUE TITLE
New game gallery entries

### ISSUE THREAD

**Issue by DaanVanYperen** [junkdog/artemis-odb#338]
Make sure entries are sufficiently complete + screenshot.

- [x] https://github.com/rtroncoso/MobClient   MMORPG Argentum Online client
- [x] https://github.com/davidbecker/taloonerrl  roguelike prototype 
- [x] https://github.com/epayet/KingdomWar    Free cross platform turn-based tactical RPG
- [x] https://github.com/lunias/shoot-back A 3d JavaFX sample which I'd like to evolve into a shooter game
- [x] https://github.com/lunias/headhoncho A networked JavaFX card game for two players
- [x] http://mini2dx.org/2015/08/22/mini2dx-1-2-0-released/
- [x] https://github.com/RossKinsella/Drop-Powered-By-Artemis-Odb

**Comment by junkdog** [comment]
http://mini2dx.org/2015/08/22/mini2dx-1-2-0-released/

**Comment by DaanVanYperen** [comment]
https://github.com/RossKinsella/Drop-Powered-By-Artemis-Odb

**Comment by DaanVanYperen** [comment]
Didn't add the JavaFX examples due to maturity and lack of screenies.
