### ISSUE TITLE
RoboVM 1.7 Released

### ISSUE THREAD

**Issue by DaanVanYperen** [junkdog/artemis-odb#341]
Check if this changes anything for core, contrib or quickstart.

**Comment by junkdog** [comment]
awesome - compat with libgdx? I'm actually trying to pinpoint a memory leak which only affects the iOS build.

**Comment by DaanVanYperen** [comment]
1.6.5
- Updated to RoboVM 1.6

So still behind, I'm not certain if gdx provides any precompiled native stuff in their artifacts. You could just run your project through 1.7 and see if it magically solves things? ;)

**Comment by junkdog** [comment]
yeah, will have to do that.

**Comment by junkdog** [comment]
btw, built with robovm 1.6 - appears to work fine.

**Comment by junkdog** [comment]
re-open if we run into any new issues.
