### ISSUE TITLE
update documentation 1.0.0

### ISSUE THREAD

**Issue by DaanVanYperen** [junkdog/artemis-odb#350]
- [x] wiki (+clear out legacy stuff)
- [x] changelog (+clear out legacy stuff)
- [x]  migration guides 
- [x] javadoc

**Comment by gjroelofs** [comment]
The code itself is in desperate need of documentation. Various classes haven't even got any variable  documentation, let alone class documentation.

**Comment by DaanVanYperen** [comment]
*glares at Junkdog*

**Comment by gjroelofs** [comment]
It's a team effort :-)

**Comment by DaanVanYperen** [comment]
Just teasing! It's great having some more eyes on the core.

**Comment by DaanVanYperen** [comment]
Boop!
