### ISSUE TITLE
Candidates for deprecation?

### ISSUE THREAD

**Issue by DaanVanYperen** [junkdog/artemis-odb#351]
To simplify API and guide users, perhaps time to deprecate some aspects that simply do not function as advertised or lack practical utility?

- [ ] ~~Archers typing~~
- [ ] Entity Factory
- [ ] Struct Emulation

Deprecation could also mean discourage use at this time in documentation.

**Comment by DaanVanYperen** [comment]
Not sure about archetype, it might just be a case of advertising it as a feature for API devs, Only reason I've used it myself is as a particle stencil.

**Comment by Namek** [comment]
EntityFactory interfaces remind me OOP. It would be better to have those methods in `Entity` or in some `EntityFactoryAdapter`, but components would have to be optional (added when a method is called). This probably brings us to partially to #348.

Archetypes are OK, leave them alone!

**Comment by DaanVanYperen** [comment]
> Archetypes are OK, leave them alone

Henceforth strikethroughed!

**Comment by Namek** [comment]
This is madness! :scream_cat:

**Comment by DaanVanYperen** [comment]
> This is madness!

I mean removed from the deprecation list. XD

**Comment by Namek** [comment]
I'm rather disappointed by the level of discussion:
- let's remove Archetypes
- no!
- OK.

But yeah, let's not touch them this way.

**Comment by DaanVanYperen** [comment]
Teehee! Less noise will benefit users trying to board odb. Could be these features are highly applicable to some of you.

**Comment by junkdog** [comment]
Maybe migrate EntityFactories to contrib? They're so circumstantial, too much for core imo.

Struct shoule be deprecated & disabled until it works as it should.

**Comment by junkdog** [comment]
> Only reason I've used it myself is as a particle stencil.

That's basically where they shine.

**Comment by DaanVanYperen** [comment]
Maybe EntityFactories can become a stepping stone towards #348? How is the interface driven generation working for you in practice?

**Comment by snorrees** [comment]
Wait what? I just started using archetypes! All my xml gets mapped to archetypes via archetypebuilder. Vote for keeping!

**Comment by junkdog** [comment]
@DaanVanYperen See what you did!!!!

**Comment by DaanVanYperen** [comment]
:D Yeah I can't draw more stripes through it.

**Comment by DaanVanYperen** [comment]
You clearly misread, it doesn't say Archetype.
