### ISSUE TITLE
Port candidate: ComponentMapper create/remove/fallback

### ISSUE THREAD

**Issue by DaanVanYperen** [junkdog/artemis-odb#352]
While we want to keep core lean, Following aspects from extended component mappers have very high utility.

`ComponentMapper#create(entity)` Creates component, or returns existing.
`ComponentMapper#remove(entity)` Removes component, does nothing when already removed.
`ComponentMapper#getSafe(entity,fallback)` Returns component, or fallback if missing.

@junkdog port yes/no?

**Comment by Namek** [comment]
(say `yes`)

**Comment by junkdog** [comment]
:dog: barks `yes`.

**Comment by Namek** [comment]
:heart: :church: :notes: :children_crossing: :shipit:

**Comment by DaanVanYperen** [comment]
pending review #360
