### ISSUE TITLE
Merge system/manager 

### ISSUE THREAD

**Issue by DaanVanYperen** [junkdog/artemis-odb#354]
Oh lord of Great Reshuffling Of 1.0 That Will Never Happen Again Until 2.0, can we take one last look at integrating manager/system hierarchies? 

Managers are now functionally no more than Systems with matching-all aspects and lacking a `process()`. It would simplify the API a lot on both core and contrib if we `Manager extends BaseSystem` and cleanup `World` footprint/internals. Cheap too!

**Comment by DaanVanYperen** [comment]
ping @junkdog

**Comment by junkdog** [comment]
I agree, better do it now than wait for 2.0. I'd say, in the process, any system (therefore, managers too) implementing entity observer should be informed of entity state changes.
