### ISSUE TITLE
component mappers sometimes return null after a complete save/load

### ISSUE THREAD

**Issue by junkdog** [junkdog/artemis-odb#357]
@snorrees has similar issues

worked fine in 0.11.4

**Comment by snorrees** [comment]
Just gonna leave this here for now - I have yet to consistently reproduce. 

I see that prior to the EntityProcessSystem mapper returning null, a entity id is deleted and created in the same between two calls to world.process().

Notice that the breakpoint for inserted method has NOT triggered.

![null mapper](https://dl.dropboxusercontent.com/u/11931599/null_components.PNG)

---------PROCESS----------
entity created: 165
(....) lots of creations (not **48**, entity 48 is created quite a while prior to this)
entity created: 464
___________DELETE SYSTEM____________
delete: **48**
delete: 69
delete: 88
delete: 90
delete: 107
delete: 111
delete: 177
delete: 184
delete: 244
delete: 361
delete: 369
delete: 392
delete: 511
entity created: 501
entity created: **48**
---------PROCESS----------
**Breakpoint triggers, entity 48 has null components, see above screenshot of entity state**

**Comment by snorrees** [comment]
Rebase lies. It lies!

**Comment by snorrees** [comment]
Ref linked test:
In world:
```
public void process() {
    updateEntityStates();
    cm.clean(); //After this the entity which is still active in the mapper has no components
    invocationStrategy.process(systemsBag);
}
```

**Comment by snorrees** [comment]
Dunno what this fix will do with the benchmarks, or if there could be more side-effects not covered by test.
