### ISSUE TITLE
entities not properly deleted from world

### ISSUE THREAD

**Issue by junkdog** [junkdog/artemis-odb#359]
not entirely sure when... *isolating...*

**Comment by DaanVanYperen** [comment]
define not properly deleted.

**Comment by junkdog** [comment]
I didn't manage to completely isolate it - I had a an epiphany at onset of hypnagogia, but can't recall it now.

I suspected an error in deserialization, but I can trigger it by just deleting all entities in the world (in our game). Entities are seemingly naked (all components are null), but the composition id stays the same.

**Comment by snorrees** [comment]
Null components with composition id is the same symphom I saw in my case.

**Comment by junkdog** [comment]
What happens when you delete all entities? Fetching the all() aspect and deleting all entities does it for me.

**Comment by snorrees** [comment]
I do full world reuse, but to be honest I was so happy about getting a failing testcase, that I made the test go green and went to bed. TODO: test the actual game! :blush:

**Comment by junkdog** [comment]
It appears `World#updateEntityStates` isn't called, but the entities are registered in `EntityEditPool#addToPerformer`

**Comment by junkdog** [comment]
Fixed it - turned out to be #333 - revered back to old order.
