### ISSUE TITLE
Run 1.0.0-SNAPSHOT through benchmark and fix degr.

### ISSUE THREAD

**Issue by DaanVanYperen** [junkdog/artemis-odb#367]

**Comment by junkdog** [comment]
Did you run the benchmarks or are you referring to existing perf? I think there's a polymorphic field access in component mapper - I made a mental note about checking implications.

**Comment by DaanVanYperen** [comment]
Just precautionary, We're refactoring a lot.

**Comment by junkdog** [comment]
#### Preliminary results

![img](https://files.gitter.im/junkdog/vLT8/blob)

**1.0.0 with entities:** 5-10% slower iteration benchmarks than before, but also a lot safer. insert/transmuter perform marginally slower
**1.0.0 with int ids:** ~10% faster iteration benchmarks, EntityEdit/Transmuter ~25% faster

May still be room for improvement in ComponentMappers

**Comment by junkdog** [comment]
looks good for the time being. did some experiments, no improvements.
