### ISSUE TITLE
Testing for deleted in AspectSubscriptionManager

### ISSUE THREAD

**Issue by DaanVanYperen** [junkdog/artemis-odb#368]
Shouldn't below test deleted as well? from `AspectSubscriptionManager`. It seems purposeful.

```java
		// the first block is for entities with precalculated compositionIds,
		// such as those affected by EntityTransmuters, Archetypes
		// and EntityFactories.
		while (added.cardinality() > 0 || changed.cardinality() > 0) {
			am.process(added, changed, deleted);
		}
```

**Comment by junkdog** [comment]
no need to check for deleted - only added/changed can happen at that stage; all archetypes and transmuters. 

removed teh cardinality checks on master though.
