### ISSUE TITLE
Discussion world#inject

### ISSUE THREAD

**Issue by DaanVanYperen** [junkdog/artemis-odb#375]
@junkdog is there a use case for having `failIfWireAnnotationIsMissing` on inject? Since `@Wire` is now the default and users are explicitly feeding into inject makes sense dropping this variant.

Edit: name is a bit ambiguous as well, could mean 'inject this into world' or  'inject into this'. maybe name it like guava does, '#injectMembers(o)'

**Comment by DaanVanYperen** [comment]
Looking at the implications, it will now check for @SkipWire instead to determine non inject ability, works for me. Updating javadoc! Let me know about the name.

**Comment by junkdog** [comment]
Yeah, `failIfWireAnnotationIsMissing` can go to the history books.

**Comment by DaanVanYperen** [comment]
Altered javadoc covers this for now, no need for further action.
