### ISSUE TITLE
Restore API usability

### ISSUE THREAD

**Issue by DaanVanYperen** [junkdog/artemis-odb#380]
We have decided to provide long term entity reference support to keep 1.x boardable for Ashley and odb 0.9 users, while providing a lean int core for the performance purists.

- [x] Restore entity reference based API close to 0.9 design. (no flyweights/ints)
- [x] Fix practical implications (by porting contrib + 1 game)
- [x] Throw changes at Gitter crowd, resolve resulting complaints.

**Comment by junkdog** [comment]
Entity part of the API mostly restored - EntityObserver removed. EntityManager/ComponentManager/AspectSubscriptionManager are now base systems. `Entity.id` reverted to `Entity.getId()`

**Comment by junkdog** [comment]
>  Consider packaging as separate artifact.

I get the feeling this would be impractical. Skip, yea?

> Lean core (int).

If we cheat, it's done-ish.

> primitive maps.

can wait - want to benchmark a few different implementations before we chose one anway.

**Comment by DaanVanYperen** [comment]
> I get the feeling this would be impractical. Skip, yea?
> primitive maps.

`ack`!

**Comment by junkdog** [comment]
contrib remaining
