### ISSUE TITLE
Prefab solution for stale entity reference

### ISSUE THREAD

**Issue by DaanVanYperen** [junkdog/artemis-odb#385]
Be it a proper uid or pool compatible EntityReference implementation. No weaving.

#### junkdog's edit
- [x] EntityLinkManager
  - [x] register `LinkListener`: link state change callback
  - [x] `@LinkPolicy(Strategy)` on fields
  - [x] handle single link field per component
  - [x] handle multiple link fields per component
  - [x] ctor bool param: enable/disable processing LinkSites lacking a link listener
  - [x] intercept ASM-bred field mutators, enclosed as static classes on woven components
- [x] LinkSites
  - [x] UniLinkSite
  - [x] MultiLinkSite
- [x] FieildMutators: mutate component fields reflexively
  - [x] int/Entity
  - [x] IntBag/Bag-of-Entity
- [x] ASM: generate FieldMutators (invoked via plugin)
  - [x] transplant method from template class
    - [x] ... (update IteratingSystem rewriting)
  - [x] int/Entity
    - [x] test
  - [x] IntBag/Bag-of-Entity
    - [x] test
  - [x] update orig component inner class
- [x] copy tests to gwt
- [x] write wiki entry (usage, tips, listeners, some technobabble)

**Comment by nikoliazekter** [comment]
Could you please explain this?

**Comment by junkdog** [comment]
@DaanVanYperen got any ideas on how to best go forward with this? something non-invasive? easiest would probably be to wire them up with a base system; register deletion listeners - but it doesn't really solve stale references.

**Comment by DaanVanYperen** [comment]
You get the whole system managed reference object solution. Not certain if that specific solution will be valuable to many users, Is it really convenient enough to warrant the time investment?

References are arguable part of the odb lifecycle so ideally odb would null entities and `@EntityId` annotated ints with magical weaving. ;)

**Comment by junkdog** [comment]
- re-use `@EntityId` for tracking references between entities.

#### Optional system, `EntityLinkManager`
- necessary for entity links to work
  - checks all component types for `@EntityId` on a valid fields
- maintains all parent and child relationships for all entities
- register add/remove listeners on a per-entity basis
- state contained in system; can be re-created from scratch when needed.
