### ISSUE TITLE
Weaving IteratingSystem breaks Android (art)

### ISSUE THREAD

**Issue by snorrees** [junkdog/artemis-odb#387]
IteratingSystems breaks on Android (art) when it undergoes weaving:

>java.lang.IncompatibleClassChangeError: The method 'void com.tank.entity.physics.PhysicsSystem.process(int)' was expected to be of type direct but instead was found to be of type virtual (declaration of 'java.lang.reflect.ArtMethod' appears in /system/framework/core-libart.jar)

Here PhysiscsSystem implements IteratingSystem.

Built without weaving everything seems to work fine.

Note to self: Test apk-build before uploading to playstore :cry:

**Comment by Namek** [comment]
Is that right after tapping on Play from the menu?

**Comment by snorrees** [comment]
yup

**Comment by junkdog** [comment]
think i've found the error... a couple of tests had escaped migration efforts.

**Comment by junkdog** [comment]
i'm deploying a new snapshot - could you have a quick look if it works, if so I'll push 1.0.1

**Comment by snorrees** [comment]
Will do.

**Comment by junkdog** [comment]
1.1.0-SNAPSHOT

**Comment by snorrees** [comment]
Fixed :) 
Tested with a locally build version of lastest master commit.

I debugged the process method to make sure the stack had int entity as well.

**Comment by junkdog** [comment]
Awesome, I'm releasing 1.0.1 then.

**Comment by snorrees** [comment]
:heart:

**Comment by junkdog** [comment]
:blush: 

Now we wait:
```
Remote staged 1 repositories, finished with success.
```

**Comment by snorrees** [comment]
This was a good remainder for me anyway - gotta replace most of my stuff with IteratingSystems for dat performance.
