### ISSUE TITLE
TagManager stores Entity references, not ids

### ISSUE THREAD

**Issue by nikoliazekter** [junkdog/artemis-odb#388]
Since artemis-odb is moving towards int entity system, it would be more logical to make TagManager store integers, not Entity references.

**Comment by junkdog** [comment]
it's coming - need a few more collections before it makes sense making the move though: some sort of performant IntObjectMap. The idea is that core shouldn't retain any Entity instances (except for EntityManager).

**Comment by nikoliazekter** [comment]
libGDX has ObjectIntMap https://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/utils/ObjectIntMap.html

**Comment by junkdog** [comment]
Planning on benchmarking it against [fastutil](http://fastutil.di.unimi.it/) and [Koloboke](http://chronicle.software/products/koloboke-collections/) - I'm not sure libgdx's collection classes have ever been benchmarked, having found any ones either way.

**Comment by sreich** [comment]
this would be great..but in the meantime, and more trivially..could we have an overload for retrieving an int entity for a tag? having to call an extra .getId() each time, in addition to an already long statement (usually) is getting rather old :)

**Comment by junkdog** [comment]
> .could we have an overload for retrieving an int entity for a tag?

noted, I'll add it to the next release.

**Comment by junkdog** [comment]
> .could we have an overload

added in latest 2.0.0-SNAPSHOT.

ice-boxing issue for now.
