### ISSUE TITLE
Entity id can't be 64

### ISSUE THREAD

**Issue by nikoliazekter** [junkdog/artemis-odb#407]
100% reproducible issue. It looks like components `Bag` never grows.
```java
Exception in thread "LWJGL Application" java.lang.ArrayIndexOutOfBoundsException: 64
	at com.artemis.utils.Bag.get(Bag.java:181)
	at com.artemis.BasicComponentMapper.get(BasicComponentMapper.java:42)
```
This code causes the issue:
```java
Component component = ComponentMapper.getFor(componentClass, world).get(entityId);
```

**Comment by junkdog** [comment]
`ComponentMapper#get` assumes there's a component, `getSafe` never throws due to OOB.

From BasicComponentMapper:
```java
	@Override
	public A getSafe(int entityId) {
		if(components.isIndexWithinBounds(entityId)) {
			return (A) components.get(entityId);
		}
		return null;
	}
```

**Comment by nikoliazekter** [comment]
But still. The entity exists. So why do I get an exception when I try to access its components?

**Comment by junkdog** [comment]
A component of that type has never been assigned to an entity with id <= 64.

I've thought about growing all component bags at the same time (when entityIds reach certain thresholds): bigger perf hit when growing, but opens up for some more optimizations. It'll probably happen within the next couple of releases.
