### ISSUE TITLE
expected range of entity id (docs do not mention)

### ISSUE THREAD

**Issue by sreich** [junkdog/artemis-odb#409]
what's the expected range of the entity id (int). it isn't mentioned..and there are some cases where i need to specify if..e.g. an inventory slot has an item in it presently, or if it is "null". i'm assuming that valid entities range from 0-INT_MAX, so could i safely use -1?

could we also mention this in the docs..there's no mention of it, not even in the Entity class, or World or any of its methods that create/delete entities.

**Comment by junkdog** [comment]
I'll add it to the docs.

Yup, entity ids are 0 or greater, entityId:s serve as indices in various arrays.

**Comment by sreich** [comment]
ok, thanks.
