### ISSUE TITLE
Make aspects an annotation instead of a parameter to the constructor

### ISSUE THREAD

**Issue by ogregoire** [junkdog/artemis-odb#412]
Systems are absolutely illegible when they define aspects. It's also highly unintuitive to write them in the constructor. Also, the SDL is really weak, enforcing absolutely no rule.

    public class MovementSystem extends EntityProcessingSystem {
      public MoveEntitiesSystem() {
        super(Aspect.all(Position.class, Velocity.class));
      }
    }

Compared to this:

    @Aspect(
      all={Position.class, Velocity.class}
    )
    public class MovementSystem extends EntityProcessingSystem {
    }

Aspects are defined once, early at runtime. Both approaches do that, but the annotation-way is much cleaner IMO. The real advantage comes from the compilation time where you can, at compilation-time with the right processor, enforce rules like `Position` can't be in `all` and in `exclude` (yeah, I've actually seen that already).

**Comment by piotr-j** [comment]
I would't call it unintuitive, but an annotation wouldn't hurt.

**Comment by junkdog** [comment]
[agrotera](https://github.com/junkdog/agrotera) had a similar approach. I haven't touched it in a few years, and it only works with Eclipse (if you want IDE support). IIRC it reported erroneous aspect configurations. 

I've thought about including an aspect annotation for artemis-odb, as it could be used for Archetypes, free-floating Aspects and, possibly, transmuters. I want to get a better feel for it first - I'm not sure it'd add much value; some value, yes, but much? The syntax is already quite concise. I'll play around with anyway.

> The real advantage comes from the compilation time where you can, at compilation-time with the right processor,

Annotation processors are a [real pain to setup](https://github.com/junkdog/artemis-odb/wiki/Annotation-Processor ) though; as far as mature java features go: maven, Eclipse and Intellij have pretty terrible support for wiring up annotation processors.

It works fine when working in a team, but as a framework feature, they're not worth the effort.

**Comment by ogregoire** [comment]
Annotation processing isn't hard anymore: a processor, @AutoService and it's done. I know, I use it everyday.

**Comment by junkdog** [comment]
I'm not sure I agree, but I'm not familiar with `@AutoService`.  What is it and how does it solve poor IDE support? Not really an option if it requires IDE plugins - from a framework POV.

**Comment by ogregoire** [comment]
Oh, you mean regarding IDE? Sorry, I code in IDE, but I build using the command line.

Well, I'm using NetBeans and indeed I had just one or two checkboxes to apply, but that's not hard: it's what I call configuring my IDE.

Anyways, I put the proposition on the table, I personally find it barely legible. I'm not enforcing anyone to agree with me and go ahead with annotation. It's a suggestion. And if it's rejected, so be it.

**Comment by piotr-j** [comment]
Regardless of annotation, I'm sure that error checking could be built-in in the ```Aspect``` itself.

**Comment by ogregoire** [comment]
Yes, at run-time. But why do things at runtime when you can do them at compile-time? That makes the run-time faster. Also with the weaving, you can preprocess your aspect to have the rules hard-compiled if you want, for more speed gain.

**Comment by gjroelofs** [comment]
The convolution of the build process for performance isn't something to be done lightly.
Especially if the use case (System constructor) isn't something that isn't on anyones radar in terms of performance overhead. (You don't initialize a World/System every frame)

**Comment by DaanVanYperen** [comment]
This feature request makes some assumptions how legacy users are actually using the existing API.  In my case it would need to handle `@Aspect` on superclasses as well, on classes sourced in third party deps. 

Overal seems like a nice idea for a [plugin](https://github.com/junkdog/artemis-odb/wiki/Writing-Plugins), at least initially. If it gains enough momentum can always absorb it into core.

**Comment by junkdog** [comment]
iceboxed
