### ISSUE TITLE
IntervalEntitySystem IntervalDelta glitch: when_world_step_is_bigger_than_system_interval

### ISSUE THREAD

**Issue by nanonull** [junkdog/artemis-odb#416]
I found IntervalEntitySystemTest and created locally such [test](https://gist.github.com/nanonull/b56b3d71779b6c62aa52) in local copy of artemis odb.

Given:
World delta is 2
System interval is 1
1. Run 4 steps in World
Expected:
intervalSystem Total IntervalTime == 2 * 4
Actual:
intervalSystemTotalIntervalTime == 10 (when world is alive only for 8 seconds)

Test log:
processSystem
intervalSystem.getIntervalDelta(): 2.0
processSystem
intervalSystem.getIntervalDelta(): 2.0
processSystem
intervalSystem.getIntervalDelta(): 3.0
processSystem
intervalSystem.getIntervalDelta(): 3.0

java.lang.AssertionError: 
Expected :10.0
Actual   :8.0

**Comment by junkdog** [comment]
sorry for not attending this sooner; slipped my mind... 

I can't access the gist (404) - could you make it availlable again?

**Comment by nanonull** [comment]
now gist should be available

**Comment by junkdog** [comment]
Thanks, I'll have a look tomorrow - have another bug I'm working on atm, plan is to get 1.3.2 out this week.

**Comment by junkdog** [comment]
There. Thanks for reporting :)

**Comment by junkdog** [comment]
1.4.0 is released - incl this fix.
