### ISSUE TITLE
Quick voting test

### ISSUE THREAD

**Issue by DaanVanYperen** [junkdog/artemis-odb#417]
I like my own issues!

**Comment by DaanVanYperen** [comment]
Does this even show up in the list? D:

**Comment by junkdog** [comment]
what the... for all comments/issues?

**Comment by DaanVanYperen** [comment]
Strange isn't it. Apparently big traffic repo's have issues with loads of :+1 spam.

**Comment by junkdog** [comment]
Heh, I misread - I thought you said popular repo:s were flooded with emojis.

**Comment by junkdog** [comment]
also: :hankey::dog:  says hi!

**Comment by JesseTG** [comment]
I am dissapoint

**Comment by piotr-j** [comment]
+1

**Comment by junkdog** [comment]
:lock: :key:
