### ISSUE TITLE
Documentation on Component Types is unclear

### ISSUE THREAD

**Issue by jwang1919** [junkdog/artemis-odb#420]
The wiki page on Component Types: https://github.com/junkdog/artemis-odb/wiki/Component-Types
explains that PooledComponent and PackedComponent must use `Entity#createComponent(Class<Compoment>)`

I'm on version 1.4.0 and I can't find any such method.

**Comment by piotr-j** [comment]
Just outdated, like docs tend to be. You can't edit entities directly, EntityEdit must be used. ```Entity#edit#add/create``` ```World#edit(int eid)``` ```ComponentMapper<Component>#create(int eid)```

**Comment by jwang1919** [comment]
Sounds good, updated the wiki so that PackedComponent also follows this rule.
