### ISSUE TITLE
artemis-odb 2.0.0 - getting rid of PackedComponents

### ISSUE THREAD

**Issue by junkdog** [junkdog/artemis-odb#422]
not as dramatic as it sounds; I'm retiring PackedComponent/PackedWeaver - it shouldn't affect anyone's code. so, if anyone depends on packed components, let me know. but overall, they're problematic, even if we solve the performance problems. It's wiser to focus on what works.

**Comment by junkdog** [comment]
work is ongoing on the inaptly named branch, [why-play-it-safe](https://github.com/junkdog/artemis-odb/tree/why-play-it-safe). (it started off as something else)

**Comment by junkdog** [comment]
> work is ongoing on the inaptly named branch, why-play-it-safe. (it started off as something else)

merged with master

**Comment by JesseTG** [comment]
Will there still be some way to do singleton components (e.g. as a sort of tag)?

**Comment by junkdog** [comment]
Best you can do is:

```java
@PooledWeaver
public final class Culled extends Component {
}
```

It's ~20 bytes per entity, but it's memory which is never read.
