### ISSUE TITLE
Accessing entities from a system possible after removal

### ISSUE THREAD

**Issue by timtips** [junkdog/artemis-odb#424]
Accessing entities in a system via getEntityIds().get(int x) will return references to entites even if the system isn't subscribed to those entities any more.
Complete code at: http://www.timtips.com/artemisDeleteTest.zip (somehow github didn't allow me to upload the zip file but suggested to zip it ...)
Here's the relevant part:

        SystemA systemA = new SystemA();
        WorldConfiguration worldConfiguration = new WorldConfigurationBuilder()
                .with(systemA)
                .build();
        World world = new World(worldConfiguration);

        //Create entities with componentA that SystemA will subscribe to
        int entityA = world.createEntity().edit().add(new CompA()).getEntityId();
        System.out.println("Created entity with id: "+entityA);

        int entityA2 = world.createEntity().edit().add(new CompA()).getEntityId();
        System.out.println("Created entity with id: "+entityA2);

        world.process();
        systemA.removeComponentA(entityA);
        systemA.removeComponentA(entityA2);
        world.process();

        int size = systemA.getEntityIds().size();
        System.out.println("systemA.getEntityIds().size() = " + size);

        //Maybe this should throw an exception?
        int i0 = systemA.getEntityIds().get(0);
        System.out.println("i = " + i0);
        int i1 = systemA.getEntityIds().get(1);
        System.out.println("i = " + i1);
        //this should throw an even bigger exception?
        int i2 = systemA.getEntityIds().get(2);
        System.out.println("i = " + i2);

        //OUTPUT
        //        Created entity with id: 0
        //        Created entity with id: 1
        //        systemA.getEntityIds().size() = 0
        //        i = 0
        //        i = 1
        //        i = 0

**Comment by timtips** [comment]
Just realized this is basically a duplicate of #410 .
I have completely lost track of how artemis-odb handles stuff under the hood. So if it's too much of a performance impact I understand that.

Cost me quiet some time to track down a bug I introduced because of this behavior during last weekends ludum dare.
Sorry for the duplicate.

**Comment by junkdog** [comment]
hmm... I'll have a look at usage - I agree it's not the most elegant solution. internally, artemis is mostly acting on the the raw int array. i'll see about fixing it.

 (ping #410)

**Comment by junkdog** [comment]
fixed in #410 

(deploy 2.0.0-SNAPSHOT now)
