### ISSUE TITLE
Q to the community: Remove EntityFactory with 2.0.0?

### ISSUE THREAD

**Issue by junkdog** [junkdog/artemis-odb#427]
Is anyone using [entity factories](https://github.com/junkdog/artemis-odb/wiki/EntityFactory)? They're being deprecated - does anyone want to keep them around for 2.0.0?

**Comment by JesseTG** [comment]
I never used this anyway, I just load all my stuff from a file.  I'd rather see serialization fleshed out instead.

**Comment by Namek** [comment]
Does this hinder maintainability?

**Comment by junkdog** [comment]
> Does this hinder maintainability?

There are many problems with current entity factories:
- entity factory definitions are still verbose
- no default way of attaching logic to entity factory instances (onCreate etc).
- they deal with single entities; in my experience, a _conceptual entity_ that we want to express in entity factories, in fact, span multiple entities. (current project; 38 prefabs, of which only 2 deal with a single entity)
- type-erasure lures behind extended interfaces, requiring the developer to organize their method calls according to interface hierarchy
- no default and automatic way of attaching annotation processors to IDE:s, gradle and maven + interop between IDE+gradle/maven.
- annotation processors have limited introspective capabilities

**Comment by junkdog** [comment]
> I'd rather see serialization fleshed out instead.

Thinking about anything specific? Something factory-like is coming - possibly generated from serialized json or kryo blobs - this way; they'd perform fast, work with multiple entities, and no allocations from parsing json. It'd be pretty easy to wrap it in a prefab class too.  Still some time away however.

**Comment by junkdog** [comment]
done
