### ISSUE TITLE
artemis-odb 2.0.0-RC1 - ComponentMapper and Mockito

### ISSUE THREAD

**Issue by ThaBalla1148** [junkdog/artemis-odb#428]
Hi,

After updating to artemis-odb 2.0.0-RC1, all unit test that mock ComponentMapper are now broken since you can't mock final classes.

**Comment by junkdog** [comment]
Oops, it wasn't meant to stick - left-over from getting rid of packed components. I'll remove it in the next RC.

> you can't mock final classes,

Not being able to extend final classes is a good thing, when you're not testing. [PowerMock](https://github.com/jayway/powermock) - or something similar using runtime bytecode instrumentation - can massage classes into working with various mock/test frameworks.

**Comment by ThaBalla1148** [comment]
Thanks for the response. I am aware of PowerMock, I didn't think it was ideal for everyone to have to update all unit test that uses Mockito to mock ComponentMappers.

**Comment by junkdog** [comment]
RC2 was just released, so closing this one. shout if i missed something.
