### ISSUE TITLE
Bag.getData() leads to ClassCastException

### ISSUE THREAD

**Issue by ThaBalla1148** [junkdog/artemis-odb#432]
With recent changes, it seems that Bag.getDate() used to return Object[], now it returns E[]. After running the test case below, a ClassCastException occurs due to the underlying array actually being an Object[] when the type is not specified through the constructor.

**Cause**
```java
	public Bag(int capacity) {
		data = (E[])ArrayReflection.newInstance(Object.class, capacity);
	}
```

**Test Case**
```java
public class BagTest {

	private Bag<Integer> intBag;
	
	@Before
	public void setup() {
		intBag = new Bag<Integer>();
		
		intBag.add(Integer.valueOf(1));
	}
	
	@Test
	public void test_getData() {
		Integer[] intArray = intBag.getData(); // <-- Exception happens here
		
		for(Integer i : intArray) {
			System.out.println(i);
		}
	}
}
```

**Result**

java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Ljava.lang.Integer;
	at com.artemis.utils.BagTest.test_getData(BagTest.java:26)

**Comment by junkdog** [comment]
Hi, hmm, yes - type-erasure kicks in, but arrays are reifiable(?). I'll add a note about it to the javadoc and see if I can do something about the exception, but - afaik - we have no way of resolving the generic type in this case, when instantiating the backing array.

**Comment by ThaBalla1148** [comment]
Yeah, I figured as much. The only thing I could come up with last night was to just change the return type back to Object[] and force the user to cast, in that case it works fine.

**Comment by junkdog** [comment]
I had another look at libgdx's [Array](https://github.com/libgdx/libgdx/blob/aea33cf80531fbc95d83ef0f4210415b9698a255/gdx/src/com/badlogic/gdx/utils/Array.java#L32) - they made the array field public, but you still get the classcast exc when you  assign it to a local variable.

The work-around requiring no changes to artemis, like you mention, is to pass the type in the ctor; but there may be good reasons for reverting back to Object[], or disallow `#getData` when we don't have the actual type.

Thing with `getData` is that it's a low-level hack to make the syntax a bit lighter and add some safety to pooling. Code ends up looking a little more elegant if can avoid what life was like before java 1.5.0. 

I'll throw a more communicative exception for now, and then - think about the future.

**Comment by junkdog** [comment]
what am I doing, that was a terrible idea... reverting previously attempted fix

**Comment by ThaBalla1148** [comment]
It doesn't seem to be a good idea to throw the exception on `#getData`, this seems to break existing code from other libraries that use it like:

```java
Object[] someArray = someBag.getData();
```

**Comment by ThaBalla1148** [comment]
#434

**Comment by junkdog** [comment]
Yeah, much better, merging.

**Comment by ThaBalla1148** [comment]
Cool.
