### ISSUE TITLE
WorldConfigurationBuilder.Priority sorting issue

### ISSUE THREAD

**Issue by ThaBalla1148** [junkdog/artemis-odb#435]
Using the WorldConfigurationBuilder's ```Priority.LOWEST``` and ```Priority.HIGHEST``` causes ```ConfigurationElement<T>``` ordering issues due to comparison with ```Integer.MIN_VALUE``` and/or ```Integer.MAX_VALUE```.

The issue is at ```ConfigurationElement<T>.compareTo(ConfigurationElement<T> o)```:
```java
@Override
	public int compareTo(ConfigurationElement<T> o) {
		// Sort by priority descending.
		return o.priority - priority;
	}
```

Maybe a ```long``` could be used instead of ```int``` for the priority field:
```java
public final long priority;
```

But....then we would have a casting issue.....

**Comment by piotr-j** [comment]
It could just be delegated to ```Integer.compare()```

**Comment by ThaBalla1148** [comment]
Good idea. I've replaced it and tested it. This seems to work.

Pull Request: #436

**Comment by junkdog** [comment]
Sorry for taking so long to merge, slipped my mind, as usual. Heh.
