### ISSUE TITLE
Small things before 2.0.0

### ISSUE THREAD

**Issue by junkdog** [junkdog/artemis-odb#440]
#### code
- [x] `@AspectDescriptor` should work for Archetypes too
- [x] EntityLinks should maybe/optionally receive the events for all entities at the point of registration
- [x] ThreadLocal injection cache?
#### wiki
- [x] kryo serialization
- [x] page describing all annotations
- [ ] remove (or mark with a notice) defunct pages

**Comment by Namek** [comment]
`kryo serialization` yeah small thing. Inbetween those small things you could as well add https://github.com/DaanVanYperen/artemis-odb-contrib/issues/5 or #103 (Namek joking around)

**Comment by junkdog** [comment]
Hehe, it's only the wiki for the kryo backend - we already have [kryo support] (https://github.com/junkdog/artemis-odb/blob/master/artemis-kryo/src/test/java/com/artemis/managers/KryoWorldSerializationManagerTest.java) - @piotr-j made it in time for 2.0.0-RC1.

**Comment by junkdog** [comment]
> `@ArchetypeDescriptor` works on Archetypes too

ArchetypeDescriptor? I meant,  `@AspectDescriptor`

**Comment by DaanVanYperen** [comment]
Close enough!
