### ISSUE TITLE
Injecting dependencies to custom classes?

### ISSUE THREAD

**Issue by manabreak** [junkdog/artemis-odb#441]
I was wondering, is it possible to use Wire to inject dependencies to custom classes? For instance, if I have a class `Weapon`:

    public class Weapon {
        private BulletSystem bulletSystem;

        public Weapon(BulletSystem bulletSystem) {
            this.bulletSystem = bulletSystem;
        }

        public void shoot() {
            bulletSystem.spawn();
        }
    }

Is it possible to inject the `BulletSystem` using Wire and to get rid of the constructor parameter?

**Comment by junkdog** [comment]
```java
public class Weapon {
    private BulletSystem bulletSystem;

    public Weapon(World world) {
        world.inject(this);
    }

    public void shoot() {
        bulletSystem.spawn();
    }
}
```

You can also call it from outside the class, if you rather not pass the World instance, ie

```java
Weapon weapon = new Weapon(); // assuming default ctor
world.inject(weapon);
```

**Comment by manabreak** [comment]
Thanks for your quick reply! This will definitely help. :)
