### ISSUE TITLE
Question: Is there any example implementation of DelayedEntityProcessingSystem ?

### ISSUE THREAD

**Issue by sonirico** [junkdog/artemis-odb#442]
I am writing a WeaponSystem whose task is to determine if an Actor can fire a weapon, considering there is an interval of time between shots. If I've understood correctly, this sort of system is supposed to run at a delayed time in the future for a certain entity so I can save some CPU cycles. What I don't know for sure is if that just applies for a single entity or for everyone composed by my WeaponComponent. Considering that intervals of time between shots can (and will) be variable, would this system be the best approach? In that case, is out there any example of how to extend this class?

Thank you!

**Comment by nanonull** [comment]
@sonirico maybe like this https://github.com/nanonull/Feed-the-space/blob/master/spashole-game/src/main/conversion7/spashole/game/artemis_odb/systems/time/SchedulingSystem.java

**Comment by piotr-j** [comment]
There is point in doing that in this case. Ill assume that you have more then one Actor, they all can fire at arbitrary time with arbitrary delay, you cant really schedule entire system to just run when next random Actor wants to fire. Keep track of the timings in relevant component. Interval systems are useful for larger things, like updating physics x times a seconds, independent from frame rate.

**Comment by sonirico** [comment]
So, the delay applies to the entire system then? I thought it could delay the processing of each entity as much time as specified for it. In that case, the sole difference between IntervalEntityProcessingSystem and DelayedEntityProcessingSystem lies on the time, which would be variable and asjustable in the latter?

**Comment by piotr-j** [comment]
Looks like it is per entity after all cant say i bothered to look before. Looks quite convoluted for what it offers. Just look at the source, its like 200 lines and 3/4 of that is comments. Im not convinced any cpu saving it offers are worth the effort. I would do something like that https://github.com/piotr-j/tastyjam/blob/master/jam/src/io/piotrjastrzebski/jam/ecs/processors/Deleter.java simple and clear.

**Comment by nanonull** [comment]
Given example system (https://github.com/nanonull/Feed-the-space/blob/master/spashole-game/src/main/conversion7/spashole/game/artemis_odb/systems/time/SchedulingSystem.java) runs at fixed interval to check 'if delay expires for each scheduled entity' (please refer to line 'if (schedulingComponent.collectedTimeMillis >= schedulingComponent.delayTimeMillis)')

**Comment by sonirico** [comment]
But of course that extending IntervalSystem and some logic does the task, but isn't DelayedEntityProcessingSystem intended to do the same automatically? I mean, according the documentation (v1.4.0):

> ...Tracks cooldown per entity, processing entity when its timer runs out...

In my case, my WeaponComponent has a boolean attribute "triggerable" that should be switched to true when its "delayTmp" attribute -a temporary one- reaches zero. Otherwise, it should value false. Maybe I have to subtract from "delayTmp" the delta time parametrized DelayedEntityProcessingSystem.processDelta, and set that boolean to true in DelayedEntityProcessingSystem.processExpired? 

I am currently working on that. As soon as I figure out the how, I will post my example code for others to see.

**Comment by sonirico** [comment]
Well, I finally got it. The System class.
````java

public class WeaponSystem extends DelayedEntityProcessingSystem {

    private ComponentMapper<ArmedComponent> armedComponentComponentMapper;
    private ComponentMapper<ActorComponent> actorComponentComponentMapper;

    // TODO: Fix this horror
    final ShootemUp game;

    public WeaponSystem (ShootemUp game) {
        super(Aspect.all(ArmedComponent.class, ActorComponent.class));
        this.game = game;
    }


    @Override
    protected float getRemainingDelay(Entity e) {

        ArmedComponent armedComponent = armedComponentComponentMapper.get(e);
        System.out.println("AC Delay: " + armedComponent.getActionDelay());
        return armedComponent.getActionDelay();
    }

    @Override
    protected void processDelta(Entity e, float accumulatedDelta) {
        ArmedComponent armedComponent = armedComponentComponentMapper.get(e);
        armedComponent.tick(accumulatedDelta);
    }

    @Override
    protected void processExpired(Entity e) {
        ArmedComponent armedComponent = armedComponentComponentMapper.get(e);
        if (armedComponent.isActionRequested()) {
            ActorComponent triggerer = actorComponentComponentMapper.get(e);

            // [Insert boring code for spawning bullets code here]
        }

        armedComponent.clearActionRequest();
        this.offerDelay(armedComponent.getActionDelay());
    }
}

```

On the other hand, the component class:

```java
public class ArmedComponent extends PooledComponent{

    private float actionDelay;

    private boolean actionRequested;

    public Weapon currentWeapon;

    public ArmedComponent () {
    }

    public void tick ( float dt ) {
        actionDelay -= dt;
    }

    public float getActionDelay() {
        return actionDelay;
    }

    public void requestAction() {
        actionRequested = true;
    }

    public boolean isActionRequested() {
        return actionRequested;
    }

    public void clearActionRequest() {
        actionRequested = false;
        this.actionDelay = currentWeapon.getDelayBetweenShots();
    }

    public void setCurrentWeapon (Weapon weapon) {
        currentWeapon = weapon;
        this.actionDelay = currentWeapon.getDelayBetweenShots();
    }

    @Override
    public void reset () {
        this.actionDelay = 0f;
        this.actionRequested = false;
        this.currentWeapon = null;
    }
}
```

Unfortunately, I realized that the achieved effect is not what I expected. Somehow, the user input and bullet spawning does not feel synchronized at all. I will extend an IteratingSystem which I find handier for now. Guess this kind of system (DelayedEntityProcessingSystem) is more suitable for bigger and predictable tasks as both the documentation an manual display. 

Thank you both @nanonull and @piotr-j for the help!
