### ISSUE TITLE
Question: How to store temporary entities

### ISSUE THREAD

**Issue by sonirico** [junkdog/artemis-odb#443]
Right now I am working in my SpawnSystem, which is in charge of checking how much distance the world has scrolled in order to spawn new enemies. I chose this approach because runs independently of the time or speed of the scroll. Plus, I am loading a JSON in which I have serialized entities as specified [here](https://github.com/junkdog/artemis-odb/wiki/libgdx-json#save-to-local-storage).  That method automatically adds entities to the world, but I do not want that since I need to check certain conditions before, e.g if each entity's "distanceTravelledForBeingSpawned" attribute has been surpassed. In that case, the enemy would be spawned, in other words, added to the world.

A solution that comes to mind as I am writing this lies on excluding the SpawnComponent.class in every related System. However, it does not feel right somehow. There has to be a way of retrieving a Bag of entities and their components from the json without being appended to the world in the process, hasn't there? Then, I just had to iterate through each one of them in a separate system. I think of this as a much cleaner solution. 

Set the context already, is there a way of retrieving json serialized entities in a data structure for further processing?

**Comment by junkdog** [comment]
Can you spawn all entities at once - or is it more dynamic? If the former, I'd say try spawning all entities at once - and only process entities which aren't culled by the camera. We currently have a GridSystem backing a CullingSystem/`Culled` component, which some systems `exclude` on. This approach needs some refinement if entities can act independently when outside the camera - but if it's only a couple of cases, artificially extending the bounds of the entity may be an option.

In practice, few systems tend to require the `exclude`-d component(s).

There's always going to be some work building up for the GC when spawning entities during gameplay. It's possible to te-use the JsonValue - which avoids the string-to-JsonValue parsing - when using the Json-serializer directly.

> Set the context already, is there a way of retrieving json serialized entities in a data structure for further processing?

The `SaveFileFormat` instance returned when loading has all the entities; use [SerializationTag](https://github.com/junkdog/artemis-odb/blob/master/artemis/src/main/java/com/artemis/components/SerializationTag.java) to retrieve entities by name.

It tends to wrap up pretty neatly when each json blob is wrapped in a typed Prefab/Template class.

**Comment by junkdog** [comment]
re: template class - maybe something like:

```java
public abstract class Prefab {
    protected final World world;
    private final JsonValue json;

    public Prefab(World world, JsonValue json) {
        this.world = world;
        this.json = json;

        world.inject(this);
    }

    protected final SaveFileFormat create() {
        return serializationManager(world).load(json, SaveFileFormat.class);
    }

    private JsonArtemisSerializer serializationManager(World world) {
        WorldSerializationManager wsm = world.getSystem(WorldSerializationManager.class);
        JsonArtemisSerializer serializer = wsm.getSerializer();
        return serializer;
    }
}
```

With `world.inject` in the ctor, concrete implementations can use component mappers, systems etc.

**Comment by sonirico** [comment]
Enemies, as well as assets and tilemaps are going to be loaded in a separate screen, LoadingScreen.java. So yes, all enemies are spawned at once. However, since they share a lot of components with other entities which are visible and processed since the first moment (speak about the player, etc), I thought of adding to them the SpawnableComponent in other to exclude them until their moment to appear is reached, calculated in SpawnSystem.

Reading your answer I realized that by doing this
```java
SaveFileFormat sff = world.getSystem(WorldSerializationManager.class).load(is,SaveFileFormat.class);
sff.entities...
```
I can access all those entities loaded from the json. Nonetheless, wouldn't they be loaded to the world already? In that case, I will be needing to exclude them anyway.

I am probably asking rather silly questions, I run into this framework just a week ago and I still have a lot to learn.

**Comment by junkdog** [comment]
> Nonetheless, wouldn't they be loaded to the world already? In that case, I will be needing to exclude them anyway.

Yes, but in practice - I don't think you need to `exclude` on that many systems. I've never had more than 3-5 systems - unless something happens in those systems, little work is propagated to subsequent systems.

If you don't already have a per-System profiler, rolling your own [SystemInvocationStrategy](https://github.com/junkdog/artemis-odb/blob/master/artemis/src/main/java/com/artemis/SystemInvocationStrategy.java) is [pretty convenient](http://i.imgur.com/C85Ssbn.png); I wouldn't worry about entities being processed prematurely unless they turn out to be a CPU hog. 

There are many ways to go about it - recent projects tend to look like:
- Each screen is backed by a World
  - including the loading screen; it only loads assets for subsequent screens; it's up to the actual screens to create the entities. (A tip is to write a JsonValue [AssetLoader](https://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/assets/loaders/AssetLoader.html) for the prefabs).
- GridSystem: divides all entities into a *dynamic* and *fixed* grid. The *dynamic* grid is rebuilt each frame. If `DynamicTransform`  component is present, it ends up in the *dynamic* grid.
- CullingSystem: sets `Culled` component on any entity outside the camera's view
  - relies on GridSystem for quick look-ups
  - A couple of components (`HudRenderable`, `ForceNoCulling`) overrides automatic behavior; necessary for UI and off-screen things.

For us, it's been sufficient to just `exclude` on `Culled` where necessary - the renderer being the most obvious choice, but AI and movement come to mind as well. 


> I am probably asking rather silly questions,

And I am probably writing silly answers; feel free to ask away ;)

**Comment by sonirico** [comment]
Wow, I don't think I deserve such a thorough answer. Well, in fact, I have counted how many systems actually needed the `exclude` call. They turned out to be 5 of the main systems. Unfortunately, there also is a package `systems.movements` in which I put together different systems for different movements, such a `AcceleratedMovementSystem` and `SinusoidalMovementSystem`. Those systems calculate the velocity `Vector2D` of each  `MotionComponent`, and finally position and velocity are summed in the main `MotionSystem`. I have just realized that, despite the fact that I am excluding SpawnableComponents - I will keep using "spawn" until I fully understand that GridSystem stuff- in the `MotionSystem`, their velocity attributes are still modified in every system under `systems.movements`. So, do you mean that by implementing my own SystemInvocationStrategy I would be able to avoid -somehow- proccesing any spawnable entity excepting the SpawnSystem? 

PS: Nice image. Shall I assume thats part of your DebugSystem? XD

**Comment by junkdog** [comment]
> package `systems.movements` in which I put together different systems for different movements,

Have you looked at [artemis-odb-orion](https://github.com/FEOMedia/artemis-odb-orion)? It's a mini-framework for modelling ad-hoc systems as composable operations (think: libgdx's actions api for scene2d): simple movement behavior would end up looking something like

```java
sequence(
	blockWhileHaving(SpawnableComponent.class), // just an example 
	moveBy(xy(-10, 2)), // move in from right side
	sinusoidalMovement(radius, seconds(5f)), // sinus movement for 5s
	parallel( // then in parallel, accelerate and move off-screen 
		accelerateTo(xy(0, -5f), seconds(1.2f)),
		moveBy(xy(0, -40))
	)
).register(world, entityId);
```

It was made with your use-case in mind + works pretty well for UI interaction/animation too.

about grids and spatial partitioning in general: http://gameprogrammingpatterns.com/spatial-partition.html

> SystemInvocationStrategy I would be able to avoid -somehow- proccesing any spawnable entity excepting the SpawnSystem?

No, sorry, i misled you. I thought your concern in part was wasting resources. But if you do opt for operations instead of specialized systems, you'd only need to trigger the behavior when the entities are supposed to spawn. (It's possible to store operations on component fields and then register them - need to make a `.copy()` of operations you need to reuse, as operations are "consumed" upon registering).


> PS: Nice image. Shall I assume thats part of your DebugSystem? XD

Yup, editor/debug :) We have a slightly customized [vis-ui](https://github.com/kotcrab/vis-editor/wiki/VisUI) skin. Code in part salvaged from [dominatrix-odb](https://github.com/junkdog/dominatrix-odb). I like having it built-in/on top of the game - good-to-have/fun-to-have introspective capabilities on phone/tablet devices.

**Comment by sonirico** [comment]
I will take a look at [artemis-odb-orion](https://github.com/FEOMedia/artemis-odb-orion) , it seems really promising and up to the task, as you said. What troubles me, is the fact of serializing entities with their components  for loading. It is not totally mandatory since I could code a monolithic class for each stage, but for once I would like to do things as more professionally  as I can. On the other hand, I never expected I would be needing that many libraries and frameworks besides what the plain Libgdx provides. 

I will give all of this a try -although this little game was supposed to be a quick production for the summer XD - and be back with more doubts for sure. By the way, for you to know, [this is what is rolling in my mind](https://twitter.com/sonir1c0/status/748926318700625920).

**Comment by junkdog** [comment]
> What troubles me, is the fact of serializing entities with their components for loading.

Why is it a problem? You can mark components with `@Transient`, and they won't be included in the output.

We have have pairs of asset-reference, and asset-blob components. The asset-referencing ones can be serialized, while the components holding the assets (Sprite and whatnot) are `@Transient`.

```java
@PooledWeaver
public final class TextureReference extends Component {
	public String path;
	public String atlas;

	public TextureReference(String path, String atlas) {
		init(path, atlas);
	}

	public TextureReference() {
	}

	public TextureReference init(String path, String atlas) {
		this.path = path;
		this.atlas = atlas;
		return this;
	}

	@Override
	public String toString() {
		return "TextureReference{" +
			"path='" + path + '\'' +
			", atlas='" + atlas + '\'' +
			'}';
	}
}

@Transient
public class Renderable extends Component {
	public Sprite sprite;
}

```

And then a system/entity subscription for each pair; the above component pair have the aspect `all(Size.class, TextureReference.class).exclude(Renderable.class)`;  sprite assignment is dealt with in`SubscriptionListener::inserted(IntBag)`. 


> this little game was supposed to be a quick production

f e a t u r e   c r e e p :wink: 

> for you to know, this is what is rolling in my mind.

nice, i'll keep an eye on it.

**Comment by sonirico** [comment]
To start with, I added the line
`compile "se.feomedia.orion:artemis-odb-orion:0.1.0-SNAPSHOT"`
to my core module in the project, then tried to refresh but it failed. I am just using Gradle, what can be heppening?

**Comment by junkdog** [comment]
Hmm, have you done?:
1. clone the repo and run `mvn install` to install it into the local maven repository.
2. add `mavenLocal()` to your main `build.gradle`, repositories section.

**Comment by sonirico** [comment]
Ok, it's working now. I didn't know that maven had anything to do. Is there anything like "forever" operation? I am unable to find any in the Javadocs. Maybe a subclassing of RepeatedOperation could do the task?

**Comment by junkdog** [comment]
> I didn't know that maven had anything to do

Only until the first version is published. Hopefully I can get around to it sometime soon.

Nope, I tend to use Integer.MAX_VALUE. You could wrap it in a method, simpler than subclassing:

```java
public static Operation forever(Operation operation) {
	return repeat(Integer.MAX_VALUE, operation);
}
```

I should probably add it to orion's OperationFactory too though.

**Comment by junkdog** [comment]
Added the above method to OperationFactory. You need to rebuild with `mvn install` after pulling.

**Comment by sonirico** [comment]
Great! Another thing that caught my eye is the following fact:

1. I have a CollisionSystem which readjusts every entity position if they have collided.
2. I set some operations to a single entity (the player) as the example (moveBy). The others are just moved in a separate standard system.
3. Collisions between the world an the player are not handled, it passes through walls.
4. I set the collision system priority to NORMAL + 1 and now everything works, but I am afraid this issue could be happen again.

**Comment by junkdog** [comment]
Hmm I tend to manually set up my systems (as in, not using the WorldConfigurationBuilder). Which version are you on? There was a fix related to priorities in [2.0.0-RC3](https://github.com/junkdog/artemis-odb/blob/master/CHANGELOG.md#version-200-rc3---2016-06-21).

If that isn't the culprit, what's the set priority of OperationsSystem and your collision system?

**Comment by sonirico** [comment]
I'm on Artemis 1.4.0 (stable version, isn't it?). When the issue was happening, both systems priority were set to default. I will upgrade to 2.0.0 and let you know.

**Comment by sonirico** [comment]
I am sorry it took me so long to reply. I created a new branch of my game in which I set up everything using just Scene2D. I added `Actions.moveBy(...)` to the player as I did in the artemis-odb branch and collisions work as expected. Unfortunately, I couldn't get the MoveByOperator example to work as expected. 

On the other hand I thought in adding a Test case but since there are too much code involved...

**Comment by junkdog** [comment]
Is `OperationSystem` added, and have you otherwise confirmed if it works?

```
OperationFactory.run(new Runnable() {
    @Override
    public void run() {
        System.out.println("hrmm... he-..hello?");
    }
}).register(world);
```

**Comment by sonirico** [comment]
Hi! Yes, that indeed works. `OperationSystem` is always set. 

This issue is not related with orion but with the ECS pattern or smth. Let me explain. The facts are:

- Using Scene2D collisions are handled as expected.
- Using Orion, aren't. Since artemis-odb-orion uses ECS...
- I merged Scene2D and Artemis, by creating both `ActorComponent` (holds an Actor object) and `ActorSystem` (subclasses `EntityProcessingSystem`) which calls `Actor.act(float dt)` method. I added some Actions in sequence and collisions are not handled anymore.

Moreover, I tried every possible combination of priorities

- CollisionSystem with HIGHEST, ActorSystem with LOWEST
- CollisionSystem with LOWEST, ActorSystem with HIGHEST,
- So on...

This eliminates the possibility the entities position get overriden, I think.

**Comment by junkdog** [comment]
This is with 2.0.0-RC?

I'd try manually setting up the world, without using the WorldConfigurationBuilder - just add systems etc to the WorldConfiguration directly. At least that way we can narrow down the error (unless you're still on 1.4.0).

What are you using scene2d for, besides collisions?

**Comment by sonirico** [comment]
From my `build.gradle`:

- gdxVersion = '1.9.3'
- roboVMVersion = '2.1.0'
- box2DLightsVersion = '1.4'
- aiVersion = '1.8.0'
- artemisVersion = '2.0.0-RC4'
- artemisOrionVersion = '0.1.0-SNAPSHOT' 

I am using and  `Actor.class` object which scende2d provides inside an ActorComponent.class because it actually wraps much data and logic which I need almost in every part of the game. Just for holding data, not even for actions nor stages etc.

**Comment by sonirico** [comment]
I think I have finally isolated the problem. Here it is my `CollisionSystem`:
```java
package com.katodia.shootemup.systems;


import com.artemis.Aspect;
import com.artemis.ComponentMapper;
import com.artemis.Entity;
import com.artemis.managers.GroupManager;
import com.artemis.systems.IntervalEntitySystem;
import com.artemis.utils.Bag;
import com.artemis.utils.ImmutableBag;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.graphics.Color;
import com.badlogic.gdx.graphics.glutils.ShapeRenderer;
import com.badlogic.gdx.math.Intersector;
import com.badlogic.gdx.math.Rectangle;
import com.katodia.shootemup.Constants;
import com.katodia.shootemup.components.ActorComponent;
import com.katodia.shootemup.components.PlayableComponent;

/**
 * @author Flet https://github.com/Flet
 * Partially stolen from https://github.com/Flet/spaceship-warrior-gradle/blob/master/core/src/net/brokenspork/systems/CollisionSystem.java
 */

public class CollisionSystem extends IntervalEntitySystem {

    private ComponentMapper<ActorComponent> actorComponentComponentMapper;

    private Bag<CollisionPair> collisionPairs;

    ShapeRenderer renderer;

    public CollisionSystem() {
        super(
            Aspect.all(PlayableComponent.class),
            Constants.INGAME.CHECK_COLLISIONS_DELTA
        );

        renderer = new ShapeRenderer();
    }

    @Override
    public void initialize () {
        collisionPairs = new Bag<CollisionPair>();

        // Bullets kill enemies

        collisionPairs.add(new CollisionPair(
            Constants.GROUPS.BULLET_FRIEND,
            Constants.GROUPS.ENEMY,
            new CollisionHandler() {
            @Override
            public void handleCollision(Entity e1, Entity e2) {
                getWorld().delete(e1.getId());
            }

            @Override
            public boolean collisionExists(Entity e1, Entity e2) {
                ActorComponent e1ActorComponent = actorComponentComponentMapper.get(e1);
                ActorComponent e2ActorComponent = actorComponentComponentMapper.get(e2);

                Rectangle bulletRectangle = e1ActorComponent.getBounds();
                Rectangle objectRectangle = e2ActorComponent.getBounds();

                return Intersector.overlaps(bulletRectangle, objectRectangle);
            }
        }
        ));

        // Bullets collide with the world

        collisionPairs.add(new CollisionPair(
                Constants.GROUPS.BULLET,
                Constants.GROUPS.COLLIDABLE_ELEMENT,
                new CollisionHandler() {
                    @Override
                    public void handleCollision(Entity e1, Entity e2) {
                        getWorld().delete(e1.getId());
                    }

                    @Override
                    public boolean collisionExists(Entity e1, Entity e2) {
                        ActorComponent e1ActorComponent = actorComponentComponentMapper.get(e1);
                        ActorComponent e2ActorComponent = actorComponentComponentMapper.get(e2);

                        Rectangle bulletRectangle = e1ActorComponent.getBounds();
                        Rectangle objectRectangle = e2ActorComponent.getBounds();

                        return Intersector.overlaps(bulletRectangle, objectRectangle);
                    }
                }
        ));

        // Dynamic entities vs world static elements

        collisionPairs.add(new CollisionPair(
                Constants.GROUPS.COLLIDABLE_ACTOR,
                Constants.GROUPS.COLLIDABLE_ELEMENT,
                new CollisionHandler() {

                    /**
                     * Adjusts e1 coordinates so as not to overlap static elements and impede movement
                     * @param e1 A dynamic entity
                     * @param e2 The static one
                     */
                    @Override
                    public void handleCollision(Entity e1, Entity e2) {
                        // For better performance, handling is done in collisionExists
                        return;
                    }

                    @Override
                    public boolean collisionExists(Entity e1, Entity e2) {
                        ActorComponent e1ActorComponent = actorComponentComponentMapper.get(e1);
                        ActorComponent e2ActorComponent = actorComponentComponentMapper.get(e2);

                        Rectangle entityRectangle = e1ActorComponent.getBounds();
                        Rectangle objectRectangle = e2ActorComponent.getBounds();

                        Rectangle intersection = new Rectangle();



                        if  ( Intersector.intersectRectangles(entityRectangle, objectRectangle, intersection) ) {
                            System.out.println("Collision detected");
                            // The logic beneath is as improvable as unreadable if improved
                            boolean xAxis = false, yAxis = false;
                            if (intersection.width < intersection.height ) {
                                // We can assume we were moving over the X axis
                                xAxis = true;
                            } else if ( intersection.height < intersection.width ) {
                                // We can assume we were moving over the Y axis
                                yAxis = true;
                            } else {
                                // Have we hit a corner while traveling in 45 degrees?
                                xAxis = yAxis = true;
                            }

                            if (xAxis)
                            if(intersection.x  > entityRectangle.x) {
                                // Intersects with right side
                                e1ActorComponent.setX(objectRectangle.x - entityRectangle.width);
                            } else {
                                // Intersects with left side
                                e1ActorComponent.setX(objectRectangle.x + objectRectangle.width);
                            }

                            if (yAxis)
                            if(intersection.y > entityRectangle.y){
                                // Intersects with top side
                                e1ActorComponent.setY(objectRectangle.y - entityRectangle.height);
                            } else {
                                // Intersects with bottom side
                                e1ActorComponent.setY(objectRectangle.y + objectRectangle.height);
                            }

                            if (Constants.DEBUG) {
                                renderer.begin(ShapeRenderer.ShapeType.Filled);
                                renderer.setColor(Color.PINK);
                                renderer.rect(intersection.getX(), intersection.getY(), intersection.getWidth(), intersection.height);
                                renderer.end();
                            }
                            System.out.println("Collision rearranged to " + e1ActorComponent.getPosition().toString());
                            return true;
                        } else { return false; }
                    }
                }
        ));
    }

    @Override
    protected void processSystem() {
        for (CollisionPair cPair: collisionPairs) {
            cPair.checkForCollisions();
        }
    }

    private class CollisionPair {

        private ImmutableBag<Entity> groupEntitiesA;
        private ImmutableBag<Entity> groupEntitiesB;
        private CollisionHandler collisionHandler;

        public CollisionPair(String group1, String group2, CollisionHandler handler) {
            groupEntitiesA = world.getSystem(GroupManager.class).getEntities(group1);
            groupEntitiesB = world.getSystem(GroupManager.class).getEntities(group2);
            collisionHandler = handler;
        }


        public void checkForCollisions() {
            for(Entity entityA : groupEntitiesA) {
                for(Entity entityB : groupEntitiesB) {
                    if(collisionHandler.collisionExists(entityA, entityB)) {
                        collisionHandler.handleCollision(entityA, entityB);
                    }
                }
            }
        }


    } // End of CollisionPair.class

    private interface CollisionHandler {

        void handleCollision (Entity e1, Entity e2);

        boolean collisionExists (Entity e1, Entity e2);

    }
}

```

I am using the `GroupManager` to retrieve entities tagged as "collidable" in order to wrap all types of collision handling in the same class. `CollisionPair` is intended to link two kinds of collidable entities for different purposes thanks to CollisionHandler which I defined in the inline form. **If I move the logic to `process` or `processSystem` collisions work as expected, why would that be?**

**Comment by sonirico** [comment]
I have finally identified the problem. In my `CollisionSystem.processSystem` I was using the `GroupManager` to handle every kind of collision in the game instead of using several CollisionSystem classes within the proper Aspect attached to it. To sum up:

- Retrieving entities as `ImmutableBag` by calling `GroupManager.getEntities(String)` does not work.
- Calling  `EntitySystem.getEntities()` does.

In both cases after retrieving the Entity I get their Components for handling the collision.

**Comment by sonirico** [comment]
Multiple times I thought I had solved the problem and I were wrong (that's why I deleted previous comments). Well, the short explanation is: I didn't fully understood how interpolated operations worked. 

The long one is that `MoveByOpertaion` keeps the vector growing no matter my other logic, since it uses percents and Interpolation. In my `CollisionSystem` I checked via `Intersector.intersectRectangles` whether there was collision, method which returns an intersection rectangle if that's the case. By comparing that rectangle width and height, I could check where my entity came from and readjust its position. The problem is that as the operation vector kept growing, the entity ended up *inside* the collision object so there were no way of calculating an adjustment. Another possibility was calling `OperationSystem.clear(Entity.getID()) ` however, I am not sure if that method would erase every registered operation for that entity. Finally, I ended up writing an Operation like this: 
```java
package com.katodia.shootemup.operations;

import com.artemis.ComponentMapper;
import com.artemis.annotations.Wire;
import com.badlogic.gdx.math.Vector2;
import com.katodia.shootemup.components.ActorComponent;
import se.feomedia.orion.Executor;
import se.feomedia.orion.OperationTree;
import se.feomedia.orion.operation.TemporalOperation;

public class MoveByRelativeOperation extends TemporalOperation {

    public Vector2 vel = new Vector2();

    @Override
    public Class<? extends Executor> executorType() {
        return MoveByExecutor.class;
    }

    @Override
    public void reset() {
        super.reset();
        vel.setZero();
    }

    @Wire
    public static class MoveByExecutor
            extends TemporalExecutor<MoveByRelativeOperation> {

        private ComponentMapper<ActorComponent> actorComponentComponentMapper;

        @Override
        protected void begin(MoveByRelativeOperation op, OperationTree node) {
            super.begin(op, node);
            op.vel.set(new Vector2(op.vel.x /op.duration, op.vel.y / op.duration));
        }

        @Override
        protected void act(
            float delta,
            float percent,
            MoveByRelativeOperation op,
            OperationTree node
        ) {

            ActorComponent actorComponent = actorComponentComponentMapper.get(op.entityId);
            Vector2 pos = actorComponent.getPosition();
            pos.x += delta * op.vel.x;
            pos.y += delta * op.vel.y;
            actorComponent.setPosition(pos);
        }
    }
}
```
By basing the movement in velocity rather in destiny,  I can work always in the same Position vector. It ignores interpolation, though :-1: . Here you have two GIFs which ilustrate the problem. The intersection rectangle is pink colored.

Through `MoveByOperation`. (Gave in the example in [orion wiki](https://github.com/FEOMedia/artemis-odb-orion/wiki/Primer#a-minimal-operations-factory))

![screencast_25-07-16_18_47_30](https://cloud.githubusercontent.com/assets/9306588/17109589/e476ed48-5298-11e6-8fec-bd9de25a3e14.gif)

And through `MoveByRelativeOperation`. (Embedded above)

![screencast_25-07-16_18_46_41](https://cloud.githubusercontent.com/assets/9306588/17109606/f8d9911e-5298-11e6-83df-abb56edf1cea.gif)

@junkdog Sorry for the trouble, there is no problem with orion. Although it would be great and built-in collision-aware operation :P

**Comment by junkdog** [comment]
(sry, forgot to answer, i'll write a reply tomorrow)

**Comment by sonirico** [comment]
Looking at the gdx-ai documentation, I bumped into something called [**finite state machines**](https://github.com/libgdx/gdx-ai/wiki/State-Machine) which seemed to me pretty attractive in terms of code structure. The bad news are that it appears to be intended to work for [objects](https://github.com/libgdx/gdx-ai/blob/master/tests/src/com/badlogic/gdx/ai/tests/fsm/Bob.java) -like actors- rather than along with ECS. I thought of creating something like `AIComponent` or `StateMachineComponent`. However, since states are [handled inside an enumeration](https://github.com/libgdx/gdx-ai/blob/master/tests/src/com/badlogic/gdx/ai/tests/fsm/BobState.java) retrieving other systems to interact with the entity seems complicated and given to entangled code. Have you ever tried to merge these two systems? If not , I think I stop reading APIs XD

**Comment by piotr-j** [comment]
Enumeration is just an example, you can use a bunch of classes. Enum is used as its a convenient way of doing essentially singletons for the states.

**Comment by junkdog** [comment]
closing issue as there hasn't been any activity/discussion in some time.
