### ISSUE TITLE
Convert Component abstract classes to Interfaces

### ISSUE THREAD

**Issue by CreamyCookie** [junkdog/artemis-odb#445]
There is no good reason why `Component` should be an abstract class. It has no methods implementations.

Making it an interface would allow one to create components that inherit from existing classes:

```java
public class Position extends Vector2 implements PooledComponent {
    public Position() {}
    public Position(Vector2 v) {set(v);}
    public Position(float x, float y) {
        this.x = x;
        this.y = y;
    }

    /**
     * Called whenever the component is recycled. Implementation should reset component to
     * pristine state.
     */
    @Override
    protected void reset() {
        setZero();
    }

    public float chebyshevDistanceTo(Vector2 other) {
        return Math.max(Math.abs(x - other.x), Math.abs(y - other.y));
    }
}
```

Currently one would have to either
* set an instance of the existing class as a public attribute of the `Position` component and use it this way. As a result the code becomes harder to read and write: `pos_comp.vec2.x` /  `pos_comp.vec2.limit(2f)` instead of `pos_comp.x` / `pos_comp.limit(2f)`
* or wrap the whole existing class, thus creating lots of boilerplate code.

Besides these problems, there's also a minor but unnecessary performance impact for both workarounds.

Of course, since this change breaks backwards compatibility, it should happen in a major release.

**Comment by junkdog** [comment]
> There is no good reason why Component should be an abstract class.

Existing projects are the primary reason for keeping it as an abstract class.

I was going to run some benchmarks, but I'm pretty sure that there is some overhead of doing

```java
public class Position extends Vector2 implements Component {}
```
vs

```java
public class Position extends Component {
    public final Vector2 xy = new Vector2();
}
```

I do believe that keeping it as an abstract class mitigates potential programmers woes when learning artemis or ECS in general - as we don't have multiple inheritance. OOP and component-based architectures (aka Unity3d's) might give the idea that sometimes combining a system and component in a single class is a good thing;

```java
public class SingletonSomething extends IteratingSystem implements Component {
```


> Currently one would have to either
> set an instance of the existing class as a public attribute of the Position component and use it this way.

This is the idiomatic way. Whenever possible, I tend to grab the value directly - as in `Vector2 pos = positionMapper.get(e).xy;`. This solves your example, though I admit it doesn't always work, depending on the component. I personally haven't encountered a situation where boilerplate explodes due to `extends Component`, rather than `implements Component`.

**Comment by CreamyCookie** [comment]
> I was going to run some benchmarks, but I'm pretty sure that there is some overhead of doing
> public class Position extends Vector2 implements Component {}

Seems like you're right (or my benchmark is flawed):

https://gist.github.com/CreamyCookie/8b36e8959be0aebeb94b26952febb13c
```
PositionImpl: 211193636
PositionAttr: 137783635
```

I really wouldn't have expected this. Do you know why this happens? (It even happens if I change `xy` to be of a new type that `extends Vector2`.)

> I do believe that keeping it as an abstract class mitigates potential programmers woes when learning artemis or ECS in general - as we don't have multiple inheritance.

Although I understand your concern, I'd argue that it's more important that the tool isn't in the way of people that are experienced with ECS. If you think combining a system and a component is a good idea, that's clearly your fault, because you haven't read enough. 

> This is the idiomatic way. Whenever possible, I tend to grab the value directly - as in Vector2 pos = positionMapper.get(e).xy;. This solves your example, though I admit it doesn't always work, depending on the component.

Yeah, it does work. However, for me at least, the code is less readable. And one of the most important things about writing code is readability. "Code is read much more often than it is written," And as far as I can see, the current situation impairs readability.

```java
position.xy.limit(position.xy.dot(someVec))
```

Yes, you can save `position.xy` in a new variable, but I think it would be much nicer, if one wouldn't be required to do it this way.

**Comment by junkdog** [comment]
> Seems like you're right (or my benchmark is flawed):

Perf numbers are tricky in java - I wouldn't trust it unless wrapped in a framework like [jmh](http://openjdk.java.net/projects/code-tools/jmh/).

> I really wouldn't have expected this. Do you know why this happens?

Theories, but most certainly incorrect. There is some overhead to polymorphism however. Perhaps something to do with `GETFIELD` and `INVOKE_VIRTUAL` acting on the child type (incurring some sort of look-up)? 

> If you think combining a system and a component is a good idea, that's clearly your fault, because you haven't read enough. Others shouldn't be slowed down just because you not able to safely drive a fast vehicle.

If only people had time to read documentation  :wink:  

I don't think there's a compelling reason for changing from abstract class to interface:
- it only really pays off in the ideal case; eg `Position extends Vector2 impl Component`, or the class design becomes contrived.
- lots of existing code in various projects
- possibly some sort of performance degradation with interface-and-extends approach

**Comment by CreamyCookie** [comment]
> it only really pays off in the ideal case; eg Position extends Vector2 impl Component, or the class design becomes contrived.

.. which is optional. You don't need to inherit from any class. You can keep using `position.xy`.

> lots of existing code in various projects

But for the user the change is simple, isn't it? You just need to replace `extends Component` with `implements Component`. With an IDE this will literally take less than 1 minute. Or am I missing something?

> possibly some sort of performance degradation with interface-and-extends approach

Okay, but as you said, we don't really know. My benchmark might be flawed. And the degradation might not even happen if you keep using another object as an attribute (e.g. `velocity.xy`).  Furthermore, I don't think the performance impact is drastic enough to warrant the readability / usability issue.

Anyway, feel free to close this issue, if you still disagree.

Oh.. and before I forget: **Thank you for artemis-odb! :smiley:**

**Comment by Namek** [comment]
If you feel like the code is more complicated because of `pos.xy` instead of `pos` then I suggest to look for less boilerplate code by coding in [Xtend](http://www.eclipse.org/xtend/) in place of Java. Problem solved.

**Comment by CreamyCookie** [comment]
@Namek Actually I am using another JVM language: [Kotlin](https://kotlinlang.org/docs/reference/basic-syntax.html) =)

It's by the developers of IntelliJ IDEA and thus has great support in their IDE. (However, there's also an Eclipse plugin.) There's even a Java to Kotlin converter. The new version of LWJGL, the library that is used by Minecraft and LibGDX, is written mostly in Kotlin.

Out of interest, how would you solve the readability issues I was talking about in Xtend?

**Comment by Namek** [comment]
Sorry, I can't help you.

**Comment by junkdog** [comment]
(closing issue, but feel free to continue discussion)
