### ISSUE TITLE
Wrong test in EntityManagerTest.java

### ISSUE THREAD

**Issue by herki18** [junkdog/artemis-odb#446]
public void reset_entity_cache() {
		World w = new World(new WorldConfiguration()
			.setSystem(TagManager.class)
		);
		int[] ids = new int[] { w.create(), w.create(), w.create() };

		assertArrayEquals(new int[] {0, 1, 2}, ids);

		w.process();

		w.delete(2);
		w.delete(1);
		w.delete(0);

		boolean successfullReset = world.getEntityManager().reset();
		assertTrue(successfullReset);

		w.process();

		ids = new int[] { w.create(), w.create(), w.create() };
		assertArrayEquals(new int[] {0, 1, 2}, ids);
	}

After w.delete(0); You should be calling w.Process().

And boolean successfullReset = world.getEntityManager().reset(); should be boolean successfullReset = w.getEntityManager().reset();

At the moment you just resetting world which doesn't have any entities at all.

Or just go other way and don't create new World inside method. And use World that is defined in Setup.

**Comment by junkdog** [comment]
Thanks, good catch! How did you find it? It was pretty deviously concealed...

**Comment by herki18** [comment]
I did convert this library do C#. So I can learn about ECS and plus I learn little bit Java again.
Plus i have changed a lots of things. So I am constantly breaking tests.

I have some ideas how you can make things faster and more easier do understand the library. But first I need do test those things out my self.

**Comment by junkdog** [comment]
Ah, cool - are you open-sourcing it too or is it for internal use?

> faster and more easier

I'm all ears :)

**Comment by herki18** [comment]
Yes that is the plan. But first need do create some tutorials specific for c#. And for Unity3D.

And I will write down all things that I have implemented or I m planning to do. If you want I can give you access to repository. Then you can see what i have done.

But next biggest thing will be self learning algorithm. So when you run game once it will mark down how big arrays are and so on. So next time when you start running it will use those values or average. I still need do test it more. And plan is do use it some other places. 

I have question about Benchmark have you tried do run it on Windows OS.

**Comment by junkdog** [comment]
Nope, haven't run it on windows, only linux. Don't they work?

**Comment by junkdog** [comment]
(closing issue, but feel free to continue discussion)
