### ISSUE TITLE
Wire ignoreInherited ignored during explicit injection 

### ISSUE THREAD

**Issue by junkdog** [junkdog/artemis-odb#447]
(possibly due to explicit injection = not an artemis type)

**Comment by DaanVanYperen** [comment]
Assuming this means `@Wire(injectinherited=false)` on POJO, `world.inject` with other POJO, and somehow injection still happening on superclass.

if so, can't reproduce, see new test: `WireTest#When_explicit_inject_pojo_into_wire_injectinherited_false_annotated_pojo_Then_should_NOT_inject_into_superclass_fields`

Though the @Wire requirement for pojo fields threw me off a bit. 

Please re-open and provide a MCVE if above isn't what you wanted fixed. ;)
