### ISSUE TITLE
remove WorldConfigurationBuilder.withPassive

### ISSUE THREAD

**Issue by CreamyCookie** [junkdog/artemis-odb#449]
`WorldConfigurationBuilder.with` is identical to `WorldConfigurationBuilder.withPassive` and passive systems have been removed.

``` java
public WorldConfigurationBuilder withPassive(int priority, BaseSystem... systems) {
```

btw. Why were passive systems removed and how can I achieve the same now?

**Comment by junkdog** [comment]
> WorldConfigurationBuilder.with is identical to WorldConfigurationBuilder.withPassive and passive systems have been removed.

oops, that shouldn't be there anymore.

> btw. Why were passive systems removed and how can I achieve the same now?

[SystemInvocationStrategy](https://github.com/junkdog/artemis-odb/wiki/InvocationStrategy) allows more sophisticated execution flows.  why do you want passive systems?

**Comment by CreamyCookie** [comment]
> SystemInvocationStrategy allows more sophisticated execution flows. why do you want passive systems?

Basically I want to seperate logic and render systems so I can implement something like 
[deWiTTERS Game Loop](
http://www.koonsolo.com/news/dewitters-gameloop/). I've seen [TomGrill/logic-render-game-loop](https://github.com/TomGrill/logic-render-game-loop), but I'm not too happy to have my game loop inside an InvocationStrategy subclass. I'd rather let my LibGDX game loop control artemis, but I guess I can do everything inside a system instead of in the screen class.

How do you pass context like the `Game` managing the screens to the systems? A singleton or just an interface containing a `setContext` method, that systems implement?

**Comment by junkdog** [comment]
Well, you could write an InvocationStrategy so that it's only explicitly invoked.

> Another question: How do you pass context like the Game managing the screens to the systems?

Register the object with the DI:

```java
Director director = ...;
WorldConfiguration wc = new WorldConfiguration();
wc.register(director);

// and so on
```

then, in your systems:

```java
@Wire
private Director director;
```

**Comment by CreamyCookie** [comment]
> Well, you could write an InvocationStrategy so that it's only explicitly invoked.

Yeah, that's true. I try to keep that in mind if issues arise.

> Register the object with the DI:

Ah.. good idea. Thank you! :)

**Comment by junkdog** [comment]
you can also name instance, if you to register multiple instances: https://github.com/junkdog/artemis-odb/wiki/@Wire

**Comment by junkdog** [comment]
(feel free to re-open if you have more questions)

**Comment by CreamyCookie** [comment]
@junkdog Cool, thanks, but isn't `withPassive` still there? (Also it seems like I couldn't reopen it, even if I wanted, weirdly enough.. I'm pretty sure that worked in the past though.)
