### ISSUE TITLE
WorldSerializationManager is gone?

### ISSUE THREAD

**Issue by agrock86** [junkdog/artemis-odb#450]
By using

compile "net.onedaybeard.artemis:artemis-odb:**2.0.0**"
compile "net.onedaybeard.artemis:artemis-odb-serializer-json-libgdx:1.3.1"

instead of

compile "net.onedaybeard.artemis:artemis-odb:**1.4.0**"
compile "net.onedaybeard.artemis:artemis-odb-serializer-json-libgdx:1.3.1"

I get many new classes, but WorldSerializationManager and SaveFileFormat are is missing from their respective packages. Should I move to new classes or it's a release error?

**Comment by piotr-j** [comment]
You probably should be using same version for both.

**Comment by agrock86** [comment]
you are right! using 2.0.0 for both references made the trick. Thanks
