### ISSUE TITLE
Beardscaping

### ISSUE THREAD

**Issue by DaanVanYperen** [junkdog/artemis-odb#454]
That photo scares me.

**Comment by junkdog** [comment]
which photo!?!?

**Comment by DaanVanYperen** [comment]
https://avatars1.githubusercontent.com/u/804039?v=3&s=460

I am also struggling with managing a tiny beard. :D

**Comment by sonirico** [comment]
HAHAHA

**Comment by junkdog** [comment]
bottom head hair is shorter now, its sometimes removed with the top head hair (synchronized cycles at different frequencies).

**Comment by DaanVanYperen** [comment]
I've used my lunch break to spy on you through the window. Hair claims validated!

**Comment by junkdog** [comment]
WHERE!?!??11 Guess I'm closing the window...

![where](https://cloud.githubusercontent.com/assets/804039/18203747/273b7b32-7119-11e6-97b6-540e099ad5de.jpg)

**Comment by DaanVanYperen** [comment]
i'm a great climber.
