### ISSUE TITLE
32bit word BitVector implementation for GWT

### ISSUE THREAD

**Issue by junkdog** [junkdog/artemis-odb#457]
Current GWT implementation is sloooow.

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators

**Comment by DaanVanYperen** [comment]
Noticed no significant slowdown on GWT, do we have some benchmarks to back this up?

**Comment by DaanVanYperen** [comment]
@junkdog can you close if not something that requires attention?

**Comment by DaanVanYperen** [comment]
Closing this as will not do. GWT performance is fine.
