### ISSUE TITLE
Shotgun development: fluid entities

### ISSUE THREAD

**Issue by DaanVanYperen** [junkdog/artemis-odb#458]
# Fluid entities API

Sketch up of proposed entitas like API discussion between @junkdog and @DaanVanYperen! Salvaged parts from #348/@gjroelofs. Bit of a brain dump, so this will change over time!

changelog:
- Moved advanced items to ticket #461
- Added From #348: Flag component. `::invisible(false)` `::isInvisible()`
- Added Json convenience.
- Clarified generic setter.

## Goal
Basically facilitate shotgun prototyping. Convenient assembly, accessing and transformation of entities, with a focus on quick and dirty prototyping and code by convention, with performance a secondary concern.  

We are willing to accept some IDE limitations and extra configuration.

## Basic API

We start by generating a fluid interface composite component mapper, which we expose using a static import `E(entityId)`. Generation via compile time plugin or annotation processor.

**Assemble/Transform entity**

```java
E(entityId).scale(5).pos(10,10).posZ(5).tag("banana").fuelType(JUNKDOG).invisible();
```

Conventions:
- missing components are created.
- Public fields are exposed using distinct setter automatically `pos::z` -> `E::posZ(z)`, the user explicitly defines generic setters on the component `pos::set(x,y)` -> `E::pos(x,y)`. This avoids `E::pos()` contract to unexpectedly change when the component does.
- methods will return the fluid interface for chaining.

**Access component**

```java
Pos pos = E(id)._pos();
```

Conventions:
- exposes all components in project.
- missing components are NOT created.

**Access component fields**

Instead of directly through `_pos()`, you could:

given `Pos .. { Vector2 getXY() .. } ` and `Anim .. { public Cell cell; }`

Getting:
```java
e = E(Id);
Vector v2 = e.posXY();
Cell cell = e.animCell();
```

Conventions:
- Missing components are created before interacting with fields to avoid NPE checks.
- See internals below for conventions generating field getters/setters.

**Component exists?**

```java
E(id).hasPos()
```

**Remove component**

```java
E(id).removePos()
E(id).remove(type)
```

**Convenience methods**

```java
E(id).tag("boss").groups("enemies", "rockets");
```

## Internals

**Conventions for components**

| on component | Exposed as | if missing | comments |
|------------------|-------------|------------|---|
| `Pos` | `E ::pos()` | create | chainable |
| `Pos` | `E ::pos(E e2)` | mirror `e2` | chainable |
| `Pos` | `Pos E::_pos()` | null | Getter. Could expose as `Pos E::pos` field, but doesn't scale very well and has some lifecycle issues. Having that many fields in a class means that you're all over the place, cache-wise` |
| `Pos.x` | `int E::posX()` | create | chainable |
| `Pos.x` | `E E::posX(x)` | create | getter |
| `public` `Pos::set(x,y)` | `E E::pos(x,y)` | create | chainable |
| `public` `Pos::clear()` | `E E::posClear()` | create | chainable |
| `public` `Pos::setX(x)` | `E E::posX(x)` | create | chainable |
| `public` `int Pos::getX()` | `int E::posX()` | create | getter |
| `public` `Pos::setDepth(z)` | `E E::posDepth(z)` | create | chainable |
| `public` `float Pos::getDepth()` | `float E::posDepth()` | create | getter |
| Flag (empty) `Invisible` | `E ::invisible(boolean create)` | see parameter | components with no fields are treated as flags. Additional to `E::invisible()`  |
| Flag (empty) `Invisible` | `E ::isInvisible()` | - | Returns `true` if has component `false if not.  |

- code-gen introspection:
 -  find and expose all components (https://github.com/ronmamo/reflections)
 - short-circuited methods to allow for concise things like E(id1).pos(E(id2))
 - Hard wire some common convenience, like tags(..), groups(..).
 - Stack on any custom methods supplied by the user pehaps?
 - Any ambiguity -> fail early

**E(id) internals**

- every `E(id)` obtains the next instance of the fluid interface (pooled).
   - automatically reclaim after each world process cycle.
- Using static world set in process cycle combined with `ThreadLocal` to achieve multi world support.
- Assemble all mappers for a world in a single object, use that object for all instances of E(id) within that world to `::has` and `::create`.

**Comment by shatterboom** [comment]
I'm new to Artemis (and Java to some extent) but I have experience with Entitas. A fluent Api is indeed very nice to use and greatly increases readability.

- One concern I have with `E E::pos(x,y)` is refactoring.

	1. The order of the setter parameters depends on the order of the fields in the component. It is dangerous to reorder fields, especially if they have the same type.
	2. After adding/removing fields to a component, you need to modify all the calls to this "general" setter. 

C# has optional and named parameters. That's the [solution I proposed](https://github.com/sschmid/Entitas-CSharp/pull/150) for Entitas. 

```
public class Person:IComponent {
	public string firstname;
	public string lastname;
	public int age;
}
e.AddPerson(firstname="Jeff",age=30);
```

I'm not familiar enough with Java but I don't think you could easily do something similar. Regarding ii., you could generate overloaded setters. ``E E::pos(x)` `E E::pos(y)` `E E::pos(z)` `E E::pos(x,y)` `E E::pos(x,y,z)` 

- Entitas handles flag/empty component elegantly :
```

public class MovableComponent : IComponent {}

[CustomPrefix("flag")]
public class DestroyComponent : IComponent {}

var movable = e.isMovable;
movable = true;
e.flagDestroy = true;
```

**Comment by DaanVanYperen** [comment]
@shatterboom thanks for your feedback!

> The order of the setter parameters depends on the order of the fields in the component. It is dangerous to reorder fields, especially if they have the same type.

In java the closest thing of named parameters I can think of is the Builder pattern or passing an argument object. We're forced to suffix variable names, ie: ```e.personFirstname("Jeff").personAge(30);```. It's always going to be a bit more verbose.

Coming from `e = builder.with(Person.class).build(); mPerson.get(e).firstName="bla";` I think the slightly more verbosity can be survived.

> After adding/removing fields to a component, you need to modify all the calls to this "general" setter.

True. Hadn't really considered the expectations for the general setter, especially with single field components!

We do work around this limitation. The API assumes the user decides what he wants to expose as the general setter. So you'd get (simplified a bit):

```java
class Fuel .. {
     public int volume, temperature;
     public FuelType type;
     public void set(FuelType type, int volume, int temperature) { .. } 
     public void set(FuelType type) { .. } 
}
```

Would produce
`e.fuel(type,volume,temperature);`
`e.fuel(type);`
`e.fuelType(FuelType.JUNKDOG).fuelVolume(10).fuelTemperature(10);`
but not `e.fuel(volume)`, `e.fuel(volume,temperature)` etc.

> Entitas handles flag/empty component elegantly :

I'm jealous of C# properties!

**Comment by shatterboom** [comment]
> We do work around this limitation. The API assumes the user decides what he wants to expose as the general setter.

That makes sense. 
> I'm jealous of C# properties!

Actually, in the case of flag components Entitas doesn't generate the usual Add/Replace/Remove methods. Instead it generates a getter/setter like [so](https://github.com/sschmid/Entitas-Shmup/blob/develop/Assets/Sources/Generated/OutOfScreenComponentGeneratedExtension.cs#L15). I don't see any reasons why Java couldn't do the same :) `CustomPrefix("flag")` is the c# somewhat equivalent to annotations.

**Comment by gjroelofs** [comment]
Looks quite interesting; just as a note: fluent API has pretty much replaced all normal code in our project as programmers can't be bothered to use the more verbose alternative. (We're using a hybrid Artemis/Entitas framework in C#) 

If the option is provided, people will tend to use the path of least resistance in programming.
Therefore I'd refrain from using a precaching lookup implementation that grabs all Components (as this will then propagate throughout the codebase and becomes a pain to remove afterwards)

The performance of streaming the generated component IDs into the code directly is on comparable levels to that of `ComponentMapper` and has been tested in other projects to work. (Alternatively one could add in the `ComponentMappers` to the `E` class.

I agree with @shatterboom 's remarks on the dangers of refactoring. Although, truth be told that once the programmer is aware of the danger, it is often kept in mind and we've not had that much of an issue with it.

In our project we've got a long standing issue to integrate the Roslyn compiler so we can get around these issues; but the time to implement the solution still outweighs the cost of just doing the manual refactor with IDE tools.

For the sake of prototyping; our approach has been to define/generate specific DSL for certain types of Components. (E.g.: `ValueComponent` holding a single variable of a single type, `RangeComponent` holding a minimum, current and maximum float variable.)

**Comment by DaanVanYperen** [comment]
> Looks quite interesting; just as a note: fluent API has pretty much replaced all normal code in our project as programmers can't be bothered to use the more verbose alternative. (We're using a hybrid Artemis/Entitas framework in C#)

Would imagine, given your writeup of #348 almost a year ago! Don't know if you guys do any tech talks but would love to see what you've cooked up! 

> I'd refrain from using a precaching lookup *snip* (Alternatively one could add in the ComponentMappers to the E class.

Agreed on the precaching, we have ComponentMapper sitting on a shelf so makes sense to use that for a quick win.

> I agree with @shatterboom 's remarks on the dangers of refactoring. Although, truth be told that once the programmer is aware of the danger, it is often kept in mind and we've not had that much of an issue with it.

Don't know about @junkdog but I still need to get a feel for the limitations with heavily changing generated code in IntellIJ and Eclipse, except for some Hibernate criteria stuff ;)

> For the sake of prototyping; our approach has been to define/generate specific DSL for certain types of Components. (E.g.: ValueComponent holding a single variable of a single type, RangeComponent holding a minimum, current and maximum float variable.)

Interesting. Making it extendable based on things like supertype shouldn't be too hard.

**Comment by DaanVanYperen** [comment]
@junkdog functionally complete and ready for review and merge #460. Just needs a performance pass and some more testing.

**Comment by DaanVanYperen** [comment]
Implemented, just waiting for final review. see https://github.com/junkdog/artemis-odb/wiki/Fluid-Entities
