### ISSUE TITLE
Question: Why do (transient) components require a public no-args constructor?

### ISSUE THREAD

**Issue by CreamyCookie** [junkdog/artemis-odb#470]
Here's my current situation. (written in Kotlin):

``` kotlin
private val FAKE_WORLD = World(Vector2(0f,0f), true)

// This will generate a no args constructor that uses `FAKE_WORLD`
@Transient
class DynamicBody(box2dWorld: World = FAKE_WORLD) : Component() {
    val body: Body

    init {
        // init body def etc...
        body = box2dWorld.createBody(bodyDef)
    }
}
```

AFAIK I can currently choose between
- creating a fake `world` as the default parameter (what I did above)
- making the `world` parameter nullable with a default parameter of null, and then only create a body if the world is not null, but then `body` would have to be nullable or lateinit.
- add a `intialize` or `setBox2DWorld` method and make `body` lateinit

These options don't seem very clean. Although the third is probably the cleanest..

Transient components will not be serialized. So, I wonder (besides possibly wanting to use Archetypes) why do they need to have a public no-args constructor? Is it good design to have a no-args constructor?

**Comment by piotr-j** [comment]
I dont do a single `new Component()` in my game, all goes thru mappers or via entity.edit().

**Comment by CreamyCookie** [comment]
@piotr-j Thanks. Yeah, I could have them nullable, but that would force me to use the `!!` operator all the time and thus sort of negate Kotlin's [Null Safety](https://kotlinlang.org/docs/reference/null-safety.html). In other words: I want them to be non-nullable so I don't have to worry about nullpointer exceptions.

**Comment by DaanVanYperen** [comment]
Do you plan to use pooling?

**Comment by CreamyCookie** [comment]
Yeah probably, but only on certain components. (e.g. a Position component used by particles) These would of course need a no-args constructor.

**Comment by tavomaciel** [comment]
You probably don't need pooling in this case since Box2D already pools the bodies (which are the most expensive part) in their side. I think you could live by simply defaulting to null and lateiniting stuff here.

**Comment by CreamyCookie** [comment]
@tavomaciel Oh.. I forgot about this issue report. Yes, that's what I ended up doing! :)
