### ISSUE TITLE
IntBag does not implement serializable

### ISSUE THREAD

**Issue by DaanVanYperen** [junkdog/artemis-odb#471]

**Comment by junkdog** [comment]
Does it need to?

**Comment by DaanVanYperen** [comment]
I'd like to use it in components flagged with Serializable. Working on networking.

**Comment by junkdog** [comment]
https://github.com/eishay/jvm-serializers/wiki#full-object-graph-serializers

Wouldn't kryo serializers be a better option? java's own serialization mechanism is pretty wordy.

I'd personally prefer to setup  a repo with optimized kryo serializers. a serializer + test per type. maybe some utility wrapping pertaining to debugging. Thoughts?

**Comment by DaanVanYperen** [comment]
It's coming from trying to follow conventions for odb-contrib, not making any assumptions on what people prefer to use.

Did we solve GC with kryo? not very relevant for persistence, but for networking it's a different story.

**Comment by DaanVanYperen** [comment]
I'll deal with it on my side!
