### ISSUE TITLE
Impossible to get components of int entity outside systems

### ISSUE THREAD

**Issue by theagentd** [junkdog/artemis-odb#472]
Hello, I'm trying to do this:

`Archetype archetype = new ArchetypeBuilder().add(Position.class).build(world);
int entity = world.create(archetype);

//Initialize position of entity
Position p = ...; // <--- the problem
p.x = spawnX;
p.y = spawnY;`

It seems to be impossible to actually get a single component from an int entity outside of a system. The only workaround I've found for this is:
`Position p = (Position) world.getComponentManager().getComponentsFor(entity, new Bag<>()).get(0);`
which is suboptimal to say the least.

The weird thing is that
    `public Bag<Component> getComponentsFor(int entityId, Bag<Component> fillBag)`
in ComponentManager is public, but 
    `protected Component getComponent(int entityId, ComponentType type)`
is protected. This second function is called internally by the Entity, so I can't access it with an int entity, only if I use the Entity wrapper.

Am I just missing something obvious? I've looked through the wiki but I can only find information related to ComponentMapper.

**Comment by piotr-j** [comment]
Mappers are the way to get components outside of manual creation with edit(). 
You can do that outside of a system:
```world.getMapper(Transform.class).get(entityId);```
Or if its a specific class, you can inject the mappers into it with ```world.inject(this, false);```

**Comment by DaanVanYperen** [comment]
What's causing you to need to interact with entities outside of systems? Having a system dedicated to initializing a scene or passing variables along to an external framework costs almost nothing.

**Comment by theagentd** [comment]
@DaanVanYperen THANK YOU! That is what I needed!

@piotr-j It's basically for my initial setup before the game starts.
