### ISSUE TITLE
Serialization: Save and load "work", but no entities are created after load

### ISSUE THREAD

**Issue by manabreak** [junkdog/artemis-odb#474]
I'm trying to figure out how the serialization process works. I'm using the LibGDX json serializer, and so far so good, I can serialize my objects to a JSON file ([gist here](https://gist.github.com/manabreak/3f7c159adc04d26843a9f9d706263986)).

However, when I load this JSON, no entities actually get created. Is it possible that the loading fails quietly or something? I tried to step through the loading process with the debugger, but couldn't find anything out of place. The custom serializers are initiated correctly and the referenced objects are created just fine, it's just that the entity count is zero after the loading.

Here's my serialization wrapper system:

```java
@Override
    protected void initialize() {
        backend = new JsonArtemisSerializer(world);
        backend.prettyPrint(true);
        backend.register(Mesh.class, new MeshSerializer());
        backend.register(Texture.class, new TextureSerializer(assets));
        backend.register(Transform.class, new TransformSerializer());
        manager.setSerializer(backend);
    }

    public void save(String filename) {
        System.out.println("Saving to '" + filename + "'...");

        EntitySubscription es = world.getAspectSubscriptionManager().get(Aspect.all());
        try {
            FileOutputStream fos = new FileOutputStream(filename);
            SaveFileFormat format = new SaveFileFormat(es);
            manager.save(fos, format);
            fos.close();
            System.out.println("Done!");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public void load(String filename) {
        System.out.println("Loading from '" + filename + "'...");

        try {
            InputStream is = new FileInputStream(filename);
            manager.load(is, SaveFileFormat.class);
            is.close();
            System.out.println("Done!");

            EntitySubscription es = world.getAspectSubscriptionManager().get(Aspect.all());
            int entities = es.getActiveEntityIds().length();
            System.out.println("Entities now: " + entities);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
```

The output of calling `load()` is:

```
Loading from 'testing.json'...
Done!
Entities now: 0
```

**Comment by junkdog** [comment]
Try running `world.process()` before printing entity count. Entities are inserted/removed in-between system processing, so need to trigger a run.

**Comment by junkdog** [comment]
```java
manager.load(is, SaveFileFormat.class);
```

the above returns an instance of SaveFileFormat - if you need to interact with the entities before they're intercepted by artemis.

**Comment by manabreak** [comment]
Ah, my mistake. It indeed needed the `world.process()` call first. The reason why the component didn't seem to spawn in the world is in my custom mesh serializer.
