### ISSUE TITLE
E("prefab/player.json").pos(5,5); AAAAAAAAAAAAAHHHHHHHHHHHHHH

### ISSUE THREAD

**Issue by junkdog** [junkdog/artemis-odb#475]

**Comment by junkdog** [comment]
@DaanVanYperen hmm, if 2.1.0 is to be released sometime today, I suggest we postpone this until 2.2.0. the `E(path-to-json)` assumes a single entity, which is a bit of an awkward restriction.

**Comment by DaanVanYperen** [comment]
duplicate #461
