### ISSUE TITLE
Ludum Dare

### ISSUE THREAD

**Issue by DaanVanYperen** [junkdog/artemis-odb#476]
Just a heads up, ludum dare is this weekend! A (snapshot) repo release with fluids would be appreciated. Let me know if the timing is bad!

**Comment by junkdog** [comment]
hi! Snapshot matches the latest commit.

Would be better to have an actual version out. I'll need to look into #452, but #475 might be good to include. It implies a release tomorrow however.

**Comment by junkdog** [comment]
kill all snapshots http://repo1.maven.org/maven2/net/onedaybeard/artemis/artemis-odb/2.1.0/

**Comment by DaanVanYperen** [comment]
:cookie: :cookie: :cookie: :cookie:
