### ISSUE TITLE
[Fluid] Updating fluid interface automatically

### ISSUE THREAD

**Issue by DaanVanYperen** [junkdog/artemis-odb#480]
*Two issues*
- Generating `E` takes a manual compile. This breaks IDE auto-completion and validation until a compile is done. Ideally this would happen automatically.
- `E` generation is a pre-compile code generation step of the module containing the odb systems. Ideally the whole fluid rebuild would be scoped to the components, without recompiling systems (to avoid half-built system errors and keep performance up).

*Options*
- I assume there is a way to (supply a preference for intelliJ/eclipse) to auto compile the components module of a project on changes. 
- With Gradle rolling the fluid interface codegen into the component module shouldn't be a problem.
- For Maven adding a second module (`component` <- `fluid` <- `system`) might be the way to go, or perhaps there are some frameworks that do post-compile compilation properly we can borrow from?

Thoughts @junkdog? How can we achieve simple/stable build process and convenience.

**Comment by junkdog** [comment]
> I assume there is a way to (supply a preference for intelliJ/eclipse) to auto compile the components module of a project on changes.

> Generating E takes a manual compile. This breaks IDE auto-completion and validation until a compile is done. Ideally this would happen automatically.

hmm, culprit here feels like intellij's design. off the top off my head - it's a hack, but I suppose we could generate the interface in a watching background process, put the generated file in the correct target folder (i think intellij auto-reloads updated sources)

I'll need to look closer, but incremental compilation is a global toggle, afaik. 

> For Maven adding a second module (component <- fluid <- system) might be the way to go, or perhaps there are some frameworks that do post-compile compilation properly we can borrow from?

why is a second module needed for the maven case?

> How can we achieve simple/stable build process and convenience.

I have

**Comment by DaanVanYperen** [comment]
Oops crap I edited your post. :(

**Comment by DaanVanYperen** [comment]
> Why is a second module needed for the maven case?

Conventional wisdom AFAIK when dealing with a second compilation pass in Maven seems to be: don't do it, your fighting the design. Could be wrong though.

**Comment by junkdog** [comment]
:+1: I was hoping it was maybe a classloader issue with the plugin, which is fixable.

**Comment by DaanVanYperen** [comment]
Using your build tool `gradle desktop:run` instead of IDE isn't the worst. Putting this in the freezer for now.
