### ISSUE TITLE
[Fluid] Flag components cause unstable API on E

### ISSUE THREAD

**Issue by DaanVanYperen** [junkdog/artemis-odb#481]
The Fluid API treats empty components as booleans `class Player` -> `E::isPlayer()`. When iterating over a design it's fairly common to eventually add fields to a component. This causes an undesirable change in contract `E::isPlayer` becomes `E::hasPlayer()`.

Might just be most predictable to always expose both methods `E::isPlayer()` `E::hasPlayer()` to keep things stable while letting the user pick the preferred call. Alternatively we could deal with this in the form of annotations `@Fluid(flag=true)`/`@Flag`. My preference is the first as it fits the timesaving goal better.

**Comment by junkdog** [comment]
> My preference is the first as it fits the timesaving goal better.

I agree. What about instead of, `class Player` -> `E::isPlayer()`, change to `E::flagPlayer()`? it avoids semantic clashes with `has`, but is maybe not as nice.

**Comment by DaanVanYperen** [comment]
> agree. What about instead of, class Player -> E::isPlayer(), change to E::flagPlayer()? it avoids semantic clashes with has, but is maybe not as nice.

I think we can leave is/has as a default, and give users the option to rename it 'flag' in the plugin settings. Believe that's already an option, if not easy enough to add!

**Comment by DaanVanYperen** [comment]
2016, closing.
