### ISSUE TITLE
[Fluid] Convenient entity matching

### ISSUE THREAD

**Issue by DaanVanYperen** [junkdog/artemis-odb#482]
Quick notes. Sorry for mess!

(From a jam perspective) aspects are currently a quite laborious aspect of ODB. it's a pain writing out the predicates for a system or queries to the subscription manager. There's some areas we could improve things:

**Query singletons**

Believe there are opportunities to solve the following query in a more succinct manner. 
```java
E(world.getAspectSubscriptionManager().get(Aspect.all(BathroomLevel.class)).getEntities().get(0))
```

Don't know about others but having to inspect or alter a singleton that falls outside the scope of my system aspects is a fairly common thing. Delegating to a specialized passive system might be the proper way to do it, but the verbosity of resolving the singleton remains.

Something like `E(BathroomLevel.class)` could do the trick.

**Query + iterating lists**

Same with this query:

```java
        IntBag actives = world.getAspectSubscriptionManager().get(Aspect.all(Hammer.class)).getEntities();
        int[] ids = actives.getData();
        for (int i = 0, s = actives.size(); s > i; i++) {
```

We could follow a `jQuery` style batch-operations `All(Hammer.class).visible(true).do(myOperation)` or perhaps the more practical `for(E e : All(Hammer))`, can't really weigh the performance costs of having an iterator. I guess a per-composition iterator wouldn't be too costly or limiting?

**Constructors**
Will not do.
~~IntellIJ quick-creating a constructor forcefully maps the Aspect.Builder as a parameter.~~

```java
public class MyExampleSystem extends BaseEntitySystem {
    public MyExampleSystem(Aspect.Builder aspect) {
        super(aspect);
    }
}
```

Bit of a hack but I've been using a no-arg constructor (with `Aspect.all()`) in the hierarchy to save time in this regard.

**Comment by junkdog** [comment]
```java
E(world.getAspectSubscriptionManager().get(Aspect.all(BathroomLevel.class)).getEntities().get(0))
```

how about

```java
// assuming E can wrap some more things
E(Aspect.all(BathroomLevel.class)).first()
```

and other FP-like things (without the indirection that comes with functional interfaces)

**Comment by schosin** [comment]
We already have the TagManager and it's already used for fluid entities. 
Why not something like ```E("bathroom")```?

**Comment by junkdog** [comment]
`E(aspect)` is a little prohibitive in tight loops too; as the look-up is rather expensive.

> Why not something like E("bathroom")

I think it's for acting on the subscription listener.

**Comment by schosin** [comment]
I guess I ignored the title. Just read the "access singletons" part and TagManager came to my mind.
Haven't gotten fluid entities to work yet, but even 
```E(tagManager.getEntity("bathroomLevel")``` 
looks better than 
```E(world.getAspectSubscriptionManager().get(Aspect.all(BathroomLevel.class)).getEntities().get(0))``` in my opinion when accessing singletons. Maybe as a seperate feature request, just ```E("bathroomLevel")```?

**Comment by junkdog** [comment]
> looks better than
> `E(world.getAspectSubscriptionManager().get(Aspect.all(BathroomLevel.class)).getEntities().get(0))`

what about `E(Aspect.all(BathroomLevel.class)).first()`?

**Comment by Namek** [comment]
@junkdog is there a problem to omit `Aspect.all` here?

**Comment by DaanVanYperen** [comment]
High value ticket for me, I'd love a convenient and fast API to retrieve by tag/group/composition and operate on sets.

**Comment by DaanVanYperen** [comment]
To keep things extendable and easy to grok settled on:

```java
        for (E gun : E.withGroup("player-guns")) {
            gun.firing(true);
        }
```

If anyone has a better naming suggestion i'm all for it.  was considering ```E.group(..)```, ```E.allWithGroup(..)```, perhaps ```E.entitiesWithGroup(..)``` since `E` tends to get statically imported.
