### ISSUE TITLE
How to add an existing component to an entity

### ISSUE THREAD

**Issue by Serris** [junkdog/artemis-odb#493]
How can I take a component and move it to another entity?

I'm trying to add a couple of components loaded from a file to an entity. I don't know what components will be loaded from the file, so I'd need a generic way to attach a component to an entity.

Anyone know how to do this?

**Comment by piotr-j** [comment]
Is this a trick question? `world.edit(int).add(Component)`

**Comment by Serris** [comment]
nope, not a trick question. Thank you for explaining.

maybe documenting the EntityEdit object and how to get it from the world in the wiki would be a good idea, right now I can't really find any info on it.
I suggest the entity page

**Comment by sreich** [comment]
It is a wiki after all, feel free to edit it as you learn along, so future users don't run into the same confusions
