### ISSUE TITLE
Add documentation for invocation strategy update entity states

### ISSUE THREAD

**Issue by sreich** [junkdog/artemis-odb#494]
Could you add documentation for the invocation strategy that describes why (believe since 2.0) it wants updateEntityStates to be called twice (before and after), yet I don't see why.

**Comment by DaanVanYperen** [comment]
Looks like it's mainly meant to ensure the strategy starts and ends with a sane state. Pre-process the world can be affected by initialization and custom logic. Post-process same.

Before world called updateEntityStates equivalent code on process (see 93aaf4dedb4f7d145776f65a8101fdb4e0cc358b).
