### ISSUE TITLE
KryoArtemisSerializer setRegistrationRequired set to false despite the Doc comment saying the opposite

### ISSUE THREAD

**Issue by CreamyCookie** [junkdog/artemis-odb#501]
In the [KryoArtemisSerializer](https://github.com/junkdog/artemis-odb/blob/25fa9284dfb5c891deff08d671acc92a22812501/artemis-serialization/artemis-kryo/src/main/java/com/artemis/io/KryoArtemisSerializer.java#L17) the Doc comment mentions:

>  \* {@link Kryo#setRegistrationRequired(boolean)} is set to {@code true} by default for security purposes. It can be changed by accessing Kryo instance via {@link #getKryo()}

but [later](https://github.com/junkdog/artemis-odb/blob/25fa9284dfb5c891deff08d671acc92a22812501/artemis-serialization/artemis-kryo/src/main/java/com/artemis/io/KryoArtemisSerializer.java#L17) it is actually set to `false`.

**Comment by DaanVanYperen** [comment]
Corrected the docs. Not sure what the security risks are given this implementation.
