### ISSUE TITLE
Generic component types in systems lead to MundaneWireException

### ISSUE THREAD

**Issue by manabreak** [junkdog/artemis-odb#505]
This might be something that's not even intended from Artemis' side, but anyway: I'm trying to implement a generic base class for certain kinds of manager systems. This would mean I'd need two generic component types to be passed, but this will lead to NPE when the generic types are passed to `ComponentMapper` fields.

As far as I looked, it seems that the generic type that's used with a `ComponentMapper` leads to the `ComponentType` being `null`. Tracing back, the `ComponentMapper` field doesn't have the generic type information during runtime anymore (type erasure, p'haps?).

This would be a nice addition to the reflection and injection features, but feel free to close this one if it's just plain impossible. :)

The code that causes the exception is as such:

    public abstract class ReferenceManager<R extends ReferenceComponent<C>, C extends Component> extends BaseSystem implements EntitySubscription.SubscriptionListener {

        private final Aspect.Builder builder;
        private ComponentMapper<R> refs;
        private ComponentMapper<C> components;

        private ReferenceManager(Class<R> refClass, Class<C> component) {
            //noinspection unchecked
            builder = Aspect.all(refClass).exclude(component);
        }

        @Override
        protected void initialize() {
            world.getAspectSubscriptionManager().get(builder).addSubscriptionListener(this);
        }

        @Override
        public void inserted(IntBag entities) {
            for (int i = 0, c = entities.size(); i < c; ++i) {
                int id = entities.get(i);
                R ref = refs.get(id);
                C component = components.create(id);
                ref.apply(component);
            }
        }

        // Empty / NOP overrides omitted
    }

**Comment by manabreak** [comment]
I actually solved the issue by doing this:

    @SkipWire private ComponentMapper<R> refs;
    @SkipWire private ComponentMapper<C> components;
    private final Class<R> refClass;
    private final Class<C> componentClass;

    public ReferenceManager(Class<R> refClass, Class<C> componentClass) {
        this.refClass = refClass;
        this.componentClass = componentClass;
    }

    @Override
    protected void initialize() {
        refs = world.getMapper(refClass);
        components = world.getMapper(componentClass);
    }

This seems to do the trick. However, I was wondering if it would be possible to get the actual generic type during the injection phase?

**Comment by junkdog** [comment]
> Tracing back, the ComponentMapper field doesn't have the generic type information during runtime anymore (type erasure, p'haps?).
>
> This would be a nice addition to the reflection and injection features, but feel free to close this one if it's just plain impossible. :)

Yeah, it's related to type-erasure. I haven't looked into it for some time, but I don't think it's doable without resorting to trickery (codegen or something similar).

**Comment by DaanVanYperen** [comment]
This is a bit of an edge case. Think your solution is the way to go. I'll park this in the freezer for now!
