### ISSUE TITLE
2 Year Old "FIXME" in Master Branch

### ISSUE THREAD

**Issue by jawaff** [junkdog/artemis-odb#511]
There should be absolutely no "TODO", "FIXME", or "breaking changes" merged into the master branch. This particular comment was put there by @junkdog 2 years ago and has probably been forgotten -- which is why merging it into the master branch while it was unfinished was a terrible idea. I just happened to stumble upon it.

https://github.com/junkdog/artemis-odb/blob/fceb3a998d89c39177465086b17e4afa9a4d7ca4/artemis-core/artemis/src/main/java/com/artemis/EntityEdit.java#L39

**Comment by Wafflemon** [comment]
Maybe this comment no longer applies anymore. It should be removed if it no longer applies.

**Comment by DaanVanYperen** [comment]
Solved in dev branch.
