### ISSUE TITLE
Provide immutable bitvector where applicable.

### ISSUE THREAD

**Issue by jawaff** [junkdog/artemis-odb#512]
If something isn't allowed, then the api shouldn't allow it to occur. That's why we have specific techniques to prevent incorrect usages (https://stackoverflow.com/questions/9743513/defensive-copy-from-effective-java) A library cannot be considered robust and have little things like this. I don't read through the entire code base of every library I use, so I would definitely miss something like this -- as would others. It's like a pot hole that can easily be patched up, but instead has a warning sign. 

I'd recommend having the BitVector implement an interface that restricts its usage to whatever was intended. You can then just return the BitVector as that restricted data type. It's simple and it prevents people from shooting themselves in the foot and then having to hunt down a really hard to track bug.

https://github.com/junkdog/artemis-odb/blob/fed4a973a91b6b3cfa77f562ea1b4a3d33391830/artemis-core/artemis/src/main/java/com/artemis/EntitySubscription.java#L58

**Comment by DaanVanYperen** [comment]
Odb typically has a focus on performance over idiomatic java. This means as a baseline things like this slip under the radar (assuming there is no method call motivation for the current setup). If you want to fast track this and similar issues feel free to submit a PR!

**Comment by DaanVanYperen** [comment]
Spring cleaning to bring a bit of focus. Give me a poke if you want this reopened!
