### ISSUE TITLE
Improve collections API

### ISSUE THREAD

**Issue by jawaff** [junkdog/artemis-odb#513]
It looks like the collections in this library were inspired by the standard collection interfaces, but they don't implement them. The Java language is a lot more powerful when you utilize its standard interfaces. That allows you to utilize built-in utilities instead of having to write your own. There's nothing saying that you can't extend the standard interfaces either. We have a lot of tools at our disposal that aren't able to be used at all in this library. By design, this library restricts the usage of good practices.

If I wanted to swap out the implementation for a data structure in this library, then I'd have to fork this library and change it for the entire library -- ewww. For example, maybe I want an IntBag that contains a cache and retrieves updates from a remote source. I wouldn't be able to do that with the way that everything is tied together currently, but I would have been able to if Artemis was written against interfaces instead of implementations. Interfaces don't prevent developers from using efficient or speedy implementations. There's absolutely no reason to just plain not use interfaces. 

This library would be able to have better test coverage if interfaces were used and dependency injection was allowed as well. You could for example make a mocked version of some interface so that it triggers something to happen in the implementation that you're testing. The mocked interface could even have a way to check to see if the event was triggered. A robust library should have good test coverage. It's just what is expected of professionals.

https://github.com/junkdog/artemis-odb/blob/fed4a973a91b6b3cfa77f562ea1b4a3d33391830/artemis-core/artemis/src/main/java/com/artemis/utils/IntBag.java#L15

**Comment by voidburn** [comment]
Wholeheartedly agree!

**Comment by GMWolf** [comment]
Simply having IntBag be iterable would already make subscriptions far nicer to use!

**Comment by junkdog** [comment]
I'd box them as `Integer` unfortunately, so you get one level of indirection for each `int`, instead of having <=16 contiguous int:s per cache line.

**Comment by GMWolf** [comment]
> I'd box them as Integer unfortunately, so you get one level of indirection for each int, instead of having =<16 contiguous int:s per cache line.

I edited my post, I assume whilst you were writing this.
IntBag, Bag and BitVector should implement the Collections interface.
But I agree that the framework should reference those directly rather than using generic collections, for performance reasons.

**Comment by junkdog** [comment]
> I edited my post, I assume whilst you were writing this.

Yeah :) I'm heading  out now, have some meetings and errands to attend to. I'll be back later this evening.

Polymorphic calls are, like you said, an issue too (even with the JVM:s fancy tricks). Not sure how it affects android.

**Comment by GMWolf** [comment]
But making Bag and IntBag implement Collection, or at least Iterable would not introduce any polimorphic calls.
It would however let other code reuse Bags more effectively. (I use Bag a lot and not having it be Iterable is a nuisance)

**Comment by voidburn** [comment]
IntBag has caused me a few silly bugs until I looked at the implementation
and figured how to iterate it correctly.

I don't mind it now, but it could look a bit more like libgdx's IntArray in
terms of API surface. It should not dump the responsibility of iterating it
correctly, based on context, onto the user. Any improvements on this front
would just make usability better and more intuitive!

**Comment by GMWolf** [comment]
> IntBag has caused me a few silly bugs until I looked at the implementation
> and figured how to iterate it correctly.

Oh the number of times I have iterated over Bag.Data... 
Now I know but I can see this as a barrier to entry.

**Comment by DaanVanYperen** [comment]
Relates to https://github.com/libgdx/libgdx/issues/2359

**Comment by DaanVanYperen** [comment]
Closing, no sponsor and open since 2017. Putting in the freezer, maybe we can revisit when value types are a thing.
