### ISSUE TITLE
[Fluid] Frictionless autocomplete component classes.

### ISSUE THREAD

**Issue by DaanVanYperen** [junkdog/artemis-odb#515]
Fluid generate a class that contains static final references to all component class literals. Experimental. 

```java
/** Generated using fluid entity plugin. */
public final class C {
  public static final Class<Aim> Aim = Aim.class;
  public static final Class<Angle> Angle = Angle.class;
  // -- snip //
  public static final Class<Wave> Wave = Wave.class;
}
```
Main goal is frictionless autocomplete filtered by component.

![](https://i.imgur.com/rxlDdDl.gif)

Literals are required in annotations so can't combine with #514. (Unless someone knows a cool trick? ;))

**Comment by junkdog** [comment]
just throwing ideas around:  maybe also generate something akin to `static final int` type id fields inside `C`; int constants propagate - as you said, `C` could provide id to class lookup.

**Comment by GMWolf** [comment]
Looking around, It seems that you can use static final fields for annotations. The one limitation I have come across is with arrays: They must be defined as a literal in the annotation parameters.
So it should (i think) work fine with #514 .

**Comment by DaanVanYperen** [comment]
@Junkdog Didn't think of that! My main concern is the core-only users. Right now they can use the annotations as well.
@GMWolf code as is results in 'annotation value must be a class literal` https://stackoverflow.com/questions/8604316/annotation-attribute-must-be-a-class-literal-why-constants-should-be-fine-too. Still hoping for a workaround.
