### ISSUE TITLE
🎄🎄🎄 Almost 400 stars. Happy Holidays! 🎄🎄🎄 

### ISSUE THREAD

**Issue by DaanVanYperen** [junkdog/artemis-odb#516]
![image](https://user-images.githubusercontent.com/6305602/34341629-a8a5b8da-e99b-11e7-97e8-424dc6feb75c.png)

**Comment by junkdog** [comment]
_I still haven't self-:star:..._ :thinking:

**Comment by schosin** [comment]
There you go!

**Comment by DaanVanYperen** [comment]
Woohoo!
