### ISSUE TITLE
Multi-Threading Issue with world.create()

### ISSUE THREAD

**Issue by XariZaru** [junkdog/artemis-odb#522]
Not sure if I'm just doing bad practice, but when packets are sent in from the client, I create entities and associate them to the channel context they're coming in from.

What I noticed, however, is that if my handler receives 2 packets almost simultaneously, world.create() ends up creating entities with two of the same IDs i.e (0 for both instances).

Unless I synchronize using a lock Object, it won't work. However, this does raise the issue that two entities can be created with the same ID. Is there a way to circumvent this?

**Comment by GMWolf** [comment]
seems to me like you will have to use a lock somewhere.
you could go into the entity manager and lock the entity id's, but it's probably better if you just always lock access to artemis.

**Comment by GMWolf** [comment]
Yeah that would probably work. Remember other parts of Artemis may also break if not syncronized.

Another approach is to leave Artemis on its own thread, and use something like a syncronized event queue.

**Comment by DaanVanYperen** [comment]
Spring cleaning!
