### ISSUE TITLE
System's removed called for an entity that doesn't satisfy the aspect conditions and was never inserted

### ISSUE THREAD

**Issue by CreamyCookie** [junkdog/artemis-odb#524]
I'm having a weird problem, and before making this a real bug report, I first wanted to check if maybe anyone has an idea what could be causing this on my side:

I have a `BaseEntitySystem` with the aspect `Identity`. It contains this:

```kotlin
    override fun removed(entityId: Int) {
        println(this.subscription.aspectBuilder)
        println(this.subscription.entities)
        println(entityId)
    }
```

which prints

```
Aspect[all=(Identity), one=(), exclude=()]
IntBag(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13)
14
```

as a result of me calling  `world.delete` on the entity with the id `14`. The weird thing is that that entity is rightfully never `inserted`, since it does not contain the `Identity` component. (And thus it returns `null` when using the mapper in order to retrieve its `Identity`.)

How could this happen?

**Comment by CreamyCookie** [comment]
Okay, I've now stepped through artemis code and [this line]() is causing

**Comment by CreamyCookie** [comment]
Okay, I've now stepped through artemis code and found [the place](https://github.com/junkdog/artemis-odb/blob/396ba4b04b8c920069afaeeb04791134f56f6487/artemis-core/artemis/src/main/java/com/artemis/AspectSubscriptionManager.java#L85) that causes this odd behavior: 

```java
// note: processAll != process
subscriptions.get(0).processAll(changed, deleted);

for (int i = 1, s = subscriptions.size(); s > i; i++) {
	subscriptions.get(i).process(changed, deleted);
}
```

The method `processAll` is called on the first subscription, which happens to be my `IdentitySystem` (which subscribes to the `Identity` aspect). `processAll` calls `deletedAll` which (contrary to `delete`) doesn't check whether this subscription's `activeEntityIds` contains the deleted entity. As a result, the listeners, in my case that's only the `IdentitySystem`, is notified via `listener.removed`.

@DaanVanYperen Sorry, I hope you don't mind the ping. Any idea why this is happening? Is `subscriptions.get(0)` supposed to be some special internal `SubscriptionListener` that somehow got replaced?

**Comment by DaanVanYperen** [comment]
@CreamyCookie @matozoid - Sorry for the late reply. @junkdog is still alive and doing well. RL has put us both on a bad cadence last year. 

I set aside some time every Ludum Dare to create a new game and update what I can and there is [plenty]() pending. I'll see if we can set up nightly builds.

**Comment by CreamyCookie** [comment]
That is great to hear! 
Godspeed and a happy new year :)
