### ISSUE TITLE
[FEATURE] Superclass Component Mapper 

### ISSUE THREAD

**Issue by HerrDerb** [junkdog/artemis-odb#525]
## Description
A `SuperclassComponentMapper` allows to get all components of the component type `<T extends Component` for an `entityId`.
The `SuperclassComponentMapper`  therefore will have an interface structure like `List<T extends Component> getAll(int)`

## Use case
I have one `PositionComponent` and n components which are relative positioned to the `PositionComponent` (Sprite, CollisionBox, HitBox, Items, Effects, etc.).  To know where my relative components are, I want to translate them in every cycle. For this I  am creating an abstract `RelativeComponent extends Component`. The `RelativeComponent` class has an interface `translate(float,float) `. I am processing all  `RelativeComponent` in a `RelativeComponentTranslatingSystem`. This system has a `SuperclassComponentMapper` that maps all `RelativeComponent`  of the given `entityId`. Then I simply can access the interface method `translate(float,float)` and can translate all necessary components in a generic way.
This keeps my system dynamic and easily extendable.

**Comment by GMWolf** [comment]
I don't think this is super good form when using an ECS.
Rather, when you use your relative components, retrieve the position component also, and do the offset then.
So for example, when processing your collisionBox component, it only makes sense in context with the position component, so you retrieve them both.

If you start adding inheritance to the components, you will gradually devolve back to an inheritance tree.

**Comment by HerrDerb** [comment]
This means that I would always need to worry about making the absolute position calculation in every system in which I process a relative positioned component, whereas this would be a rather generic process. 
Or in other words, the system processing a relative positioned component would have not only one concern any more, whereas a ECS is all bout separation of concerns.

**Comment by DaanVanYperen** [comment]
Transformations do get messy quick. @GMWolf's suggestion is the common solution. I think this is out of scope for core, if you want to submit a PR https://github.com/daanvanyperen/artemis-odb-contrib would probably be the best fit.
