### ISSUE TITLE
Cloning Components

### ISSUE THREAD

**Issue by XariZaru** [junkdog/artemis-odb#526]
So I am working on a project where we load data in as default values. For example, an Item whose default stats are 1 weapon attack and 1 speed. 

Any new item created will by default create components with all default values specified. Might have many different types of components.

My first instinct was to first load in the default information into respective components, then simply loop over and try to clone them to another entity ID. Is this possible?

**Comment by DaanVanYperen** [comment]
You can clone entities using serialization features.
https://github.com/junkdog/artemis-odb/wiki/libgdx-json

Alternatively there is a way to put your defaults in a file and clone them on demand (cached).
https://github.com/junkdog/artemis-odb/wiki/Prefabs
