### ISSUE TITLE
Do we have had some conclusion about entity caching?

### ISSUE THREAD

**Issue by heLomaN** [junkdog/artemis-odb#527]
Create & destroy entities frequently might cost a lot, especially in a game when it comes to a entity with mesh or textures. How should we handle this case?

I found some suggestions. The first one is to provide enable/disable interface to entity. The second one is caching heavy data in these entities. For example, mesh and texture can be cached.

I think the second one is more elegant, while the first one is more intuitive to implement. Besides, the entities are likely to have parent-child relationship, which makes enable/disable more costly. Unity3D seems to have taken the first solution, which in turn becomes to a performance bottleneck.

**Comment by GMWolf** [comment]
Entries themselves are not objects . They are shared indexes. So, integers.
Creating them is actually very, very cheap.


Components themselves can be pooled. There is a dedicated section on it in the wiki.

**Comment by DaanVanYperen** [comment]
Meshes and texture are out of scope of odb, so it's up to you. Depends on what your needs are.

If all your assets fit into memory you could preload them all in a dedicated system and refer to it from your components using a `String assetId`. Resolve it on demand in the render system. This suits most simple games with only a dozen actors on screen.

If you have huge amount of assets you could consider expanding upon someting like [SpriteManager](https://github.com/DaanVanYperen/artemis-odb-contrib/blob/master/contrib-jam/src/main/java/net/mostlyoriginal/api/manager/SpriteManager.java) (based on [AssetManager](https://github.com/DaanVanYperen/artemis-odb-contrib/blob/master/contrib-core/src/main/java/net/mostlyoriginal/api/manager/AssetManager.java)). In this example `SpriteManager` will look for entities with the `Sprite` component that are missing a `SpriteAsset` component, and load it. Should be relatively easy to extend with caching and loading it async.

Most operations in odb are so cheap I wouldn't worry too much about the engine itself until you have some crazy particle requirements.
