### ISSUE TITLE
Aspect filtered Events

### ISSUE THREAD

**Issue by GMWolf** [junkdog/artemis-odb#528]
Events systems are great by themselves, but they are better when integrated with the entity component system.

Being able to dispatch entity events, and then subscribe to those events based on an entities aspect proves to be very powerful.

For example,e you could have a BulletHit event, and then subscribe to every BulletHit event on objects with a health component, but no Armor component.

I have made a quick implementation of such a system in my [EEEL plugin](https://github.com/GMWolf/artemis-odb-eeel). (example at bottom or readme)
But I think such a system could greatly benefit from being integrated into Artemis itself. (I mostly think others could code such a system better than I could :) )

example:

```java
///register listener
world.registerListener(this::onDamage, Aspect.all(Health.class, Active.class).exclude(Armor.class))
```

```java
onDamage(DamageEvent event, int entity) {
  //reduce health
 healthMapper.get(entity).reduce(event.amount); 
}
```

```java
///inflict 'entity' with 20 damage
world.dispatch(new DamageEvent(20), entity)
```

What is important is that onDamage only gets called on events relating to entities that match the supplied aspects.

This could also be done using annotations (at the cost of slow invocations)

**Comment by DaanVanYperen** [comment]
I love this. Depends on @junkdog if it fits core.

This'll probably fit a greenfield ECS best. Might be the missing piece to pivot away from rigid systems and into something more atomic and flexible. Wondering what already exists out there.  Thanks for this! got my cogs turning. 👍

**Comment by GMWolf** [comment]
So far, as I have been looking at other ECS and game codebases, I haven't seen any system that implements events like that.
As far as I can tell, EEEL is the first instance of events being dispatched with respects to entity aspects, outside of Components being used as event flags (Though, Components as events come with a slew of problems).

**Comment by DaanVanYperen** [comment]
Closing since this is a bit out of scope right now. Earmarking it if we ever start something fresh though!
