### ISSUE TITLE
Query API / Streaming bags?

### ISSUE THREAD

**Issue by DaanVanYperen** [junkdog/artemis-odb#532]
Aspects provide limited matching with good performance but limited flexibility. 

There might be a way to combine aspects, tags, groups etc into a more practical and unified grouping and searching for entities. 

Think similar to Aspect.Builder, short, concise, for queries like:
- Give me all enemies (matching one or more compositions).
- Give me all entities where component player has connectionId  (matching a predicate).
- Give me the singleton component that holds level metadata (not as list).

Play around with extendable API, stream like constructs like filter, map, attempt to make common queries (like for system subscriptions) cachable.

Related:
#444 - Composable Aspect.Builders 
#514 - Annotation driven aspects
#482 - Convenient entity matching
#515 - Frictionless autocomplete component classes

**Comment by GMWolf** [comment]
A stream like API would be really nice.
It could allow people to add their own filters / aggregators.

```java
Query.all(enemy.class, health.class).exclude(deactivated.class).filter(e -> armorMapper.get(e).type != Fireproof).orderBy(enemyID.class);
```

Custom operations could use something like this:
```
query.apply(customOperation);
```
Where customOperation is of type sequencialQueryOperation, or agregateQueryOperation.

The down side to stream like operations is the metamorphic calls.

Perhaps this could be improved by operating on Bags of ints, rather than individual ints.
Each stage would operate on the full set of entities. This would drastically reduce the number of metamorphic calls.

**Comment by schosin** [comment]
Ignoring groups/tags for the time being (just another filter basically), I assume the common use case to be:

1. Filter entities by aspect (all, one, exclude) -> probably initialized once most of the time
2. Intermediate stream operations (filter, map, ...)
3. Terminal stream operation (forEach, reduce, ...)

Given this, a Query Api could just wrap Aspect.Builder and offer methods to return IntStream/Stream<Entity>/Stream<E>.
`
// initialize(); - query() returns a Builder for the Aspect part of it
// not sure about Query as a name in this case
Query query = query().all(Foo.class, Bar.class).exclude(Baz.class).build(); 
// processSystem();
query.parallelStream().filter(this::myPredicate).forEach(this::process); // IntStream
query.entityParallelStream().filter(this::myPredicate).forEach(this::process); // Stream<Entity>
`

Such an implementation would be very simple (my test implementation is less than 80 LOC).
How much more performant could a custom implementation of a stream-like API be? Especially when compared to parallel streams. Filter would require copying the underlying IntBag and map would require a new Bag each time.

**Comment by DaanVanYperen** [comment]
Originally I was thinking of it more as extended aspects which provide subscriptions that are reusable and O(1) on fetch, though most of my given use cases are more about ad-hoc queries that would be non trivial to implement.

I'm all for an idiomatic approach if we can make it work. Some things to consider:
1. GC performance of streams. Been looking for material on functional interfaces and streams in game development. My impression was there's not much out there yet.
2. User lock out. GWT support seems good, think about 35% of all android devices support Stream API. https://developer.android.com/studio/write/java8-support. Don't know if there is a polyfill equivalent for older models. Any android devs out there? :)
3. Parallel streams would require some form of engine support.

If streams perform well adding stream to bags would probably make the most sense. Beyond that all we need is a slightly more user friendly way to grab subscriptions. I think DI might be part of the answer there.

**Comment by GMWolf** [comment]
Dependency Injection of subscriptions? That does sound like a great idea, but the aspect would somehow need to be represented using generics.
Or the fields could be annotated
```java
@all(foo.class, bar.class)
@exclude(c.class)
EntitySubscription foobar;
```
I think that could work really nicely. (I think I steal that for EEEL)

To reduce GC impact on streams, the same IntBag could be passed from stage to stage, with each stream operator being carried out fully on the whole  IntBag. Then GC will only trigger when the IntBag needs to grow.

**Comment by DaanVanYperen** [comment]
#514 (Annotation aspects) is finished so subscription DI would be 40 LoC away.

> Filter would require copying the underlying IntBag and map would require a new Bag each time.

> To reduce GC impact on streams, the same IntBag could be passed from stage to stage, with each stream operator being carried out fully on the whole IntBag. Then GC will only trigger when the IntBag needs to grow.

Java 8 streams will hit the GC definitely. Streams require judicious use to begin with. I'm not too worried about the GC for desktop and web games as long as we communicate this fact properly.

We always have the option to home-brew something that doesn't hit the GC as heavily, though it definitely would be more limited.

**Comment by DaanVanYperen** [comment]
Dependency Injection of subscriptions using annotations has been added in https://github.com/junkdog/artemis-odb/pull/543

What remains is the query / stream API. Should probably mature the idea a bit further in odb-contrib before committing to it on core.

**Comment by DaanVanYperen** [comment]
The DI of subscriptions works great. Closing this to spend time elsewhere!
