### ISSUE TITLE
Contribute to wiki

### ISSUE THREAD

**Issue by DaanVanYperen** [junkdog/artemis-odb#538]
Artemis-odb wiki and examples go very in depth on all the optional features, obscuring the simple core functionality for beginners. This scares potential users away to more barebone frameworks.

### Guidelines:
- introduce structure and flow.
- Make information easier to find and less overwhelming.
- tailor to user groups. 
- consolidate small pages with a common theme.
- Improve writing consistency.
- Redo meandering pages, fill in some gaps.

### Wiki consumers

- [ ] Users new to gamedev on java in general
- [x] Users new to ECS
- [ ] libGDX users
- [ ] Ashley users
- [x] Artemis-odb core users
- [ ] Artemis-odb fluid users
- [ ] Architects (API integration, editors, plugins, extension points).
- [ ] Users targeting other platforms (web/android/IOS)

### Improve wiki

(Sidebar text - page content).
- [x] Overview - 1 outline paragraph, features, quickstart guide (wiki front page), link to benchmarks
- [x] Concepts - Understand the basics - ECS in 1 paragraph, Overview of ECS in ODB terms (Entity, Component, System) 1 page.
- [x] Getting started - Step by step to help users navigate the documentation.
  - [x] Quick start - maven / gradle info, links to resources (quickstart repos)
  - [x] Make a simple game - in 20 minutes.
  - [x] Best practices - based on effective artemis odb
- [ ] More guides
  - [x] Performance - Weaving, Entity Transmuter, Pooling, Archetype, Prefabs.
  - [x] Custom game loop - Custom system invocation
  - [ ] Advanced concepts - Custom Objects, Subscriptions, Listeners
  - [ ] Web/IOS/Android/Kotlin - Details about supporting exotic platforms.
- [x] Plugins
   - [x] Serialization API
   - [x] Fluid API - Fast prototyping  
   - [x] Actions API - Orion and contrib
   - [x] Managed relationships 
   - [x] Events - 
   - [x] Debugger - 
   - [x] Singletons - 
   - [ ] Any plugins we are forgetting, there are loads.
- [ ] Games made with odb
- [ ] API reference
   - [ ] Architecture overview - Module graph
   - [ ] Lifecycle - World, Entity & Component lifecycle
   - [x] System hierarchy
   - [x] Javadoc

### TBD

Find a logical spot for:
  - [x] Gentleman link to Ashley
  - [ ] Annotations (probably flip around and start from feature to annotation, not the other way around).
  - [ ] World configuration (builder)
  - [ ] Entity Subscriptions and listeners
  - [x] Flesh out the quickstart repo (odb-gradle, etc)
  - [ ] Cookbook?

**Comment by DaanVanYperen** [comment]
https://github.com/DaanVanYperen/artemis-odb-examples juist fluid+gradle for now.

**Comment by DaanVanYperen** [comment]
Just using this as a scratch pad. 
#title: Simplified world 
#gutter: 30
#spacing: 60
[<frame>World (Simplified)|
[Entity] +-> * [<abstract>Component]
[Entity] * <- Processes [<abstract>BaseEntitySystem]
[Component] Exposes <-- [ComponentMapper] 
[BaseEntitySystem] -:> extends [<abstract>BaseSystem]
]

http://www.nomnoml.com/#view/%23title%3A%20Simplified%20world%20%0A%23gutter%3A%2030%0A%23spacing%3A%2060%0A%5B%3Cframe%3EWorld%20(Simplified)%7C%0A%5BEntity%5D%20%2B-%3E%20*%20%5B%3Cabstract%3EComponent%5D%0A%5BEntity%5D%20*%20%3C-%20Processes%20%5B%3Cabstract%3EBaseEntitySystem%5D%0A%5BComponent%5D%20Exposes%20%3C--%20%5BComponentMapper%5D%20%0A%5BBaseEntitySystem%5D%20-%3A%3E%20extends%20%5B%3Cabstract%3EBaseSystem%5D%0A%5D

![image](https://user-images.githubusercontent.com/6305602/58385795-3aff4100-7ff6-11e9-8b69-cf2114015ece.png)

**Comment by DaanVanYperen** [comment]
#title: Systems diagram
#gutter: 30
#spacing: 60
[<frame>World building|
   [MyGameLauncher] instances-> [World]
   [WorldConfiguration] configures-> [World]
   [WorldConfigurationBuild] Produces -> [WorldConfiguration]
]

![image](https://user-images.githubusercontent.com/6305602/58629394-b0139480-82dc-11e9-8384-971430da67b4.png)

**Comment by DaanVanYperen** [comment]
https://www.websequencediagrams.com/

title World processing

MyGameLoop->World: process()
World->System 1: process()
System 1->System 1: begin()
System 1->System 1: process(entity)
System 1->System 1: end()
World->System ..: process()
World->System N: process()

![image](https://user-images.githubusercontent.com/6305602/58630734-9c6a2d00-82e0-11e9-8a26-5e70b991bc0f.png)

**Comment by DaanVanYperen** [comment]
title Entity deletion lifecycle


loop
World->+System: process()
System->-System: delete(entity)
World->Subscription: update
Subscription->Subscription: forget entity
end
World->World: delete entity\n and components


![image](https://user-images.githubusercontent.com/6305602/58633143-e571af80-82e7-11e9-8fb2-3d2a72637a29.png)

**Comment by DaanVanYperen** [comment]
Got to pick which ones we want to use and which ones to ignore. graphs for everything is a bit overkill. 

title IteratingSystem lifecycle

![image](https://user-images.githubusercontent.com/6305602/58633672-6f6e4800-82e9-11e9-8551-6188d34a2ffa.png)


title World processing lifecycle

MyGameLoop->+World: process()
loop per system
World->System: process()
World->+Internal managers: process()
Internal managers->-Internal managers: update subscriptions
end
World->+Internal managers: process()
Internal managers->-Internal managers: recycle entities &\n components &\nupdate subscripions

![image](https://user-images.githubusercontent.com/6305602/58634111-c0cb0700-82ea-11e9-8ae7-a40c7215a153.png)

**Comment by DaanVanYperen** [comment]
Chart describing the best to worst way to decouple systems

#gutter: 60
#spacing: 60
[<frame>Coupling between systems|

  [No dependency] better than -> [Utility class] 
  [Utility class] better than -> [Singleton Component]
  [Utility class] -> [Event]
  [Singleton Component] better than -> [Utility/Managing System]
  [Event] better than -> [Utility/Managing System]
  [Utility/Managing System] Better than -> [Entity System]
  
]

![image](https://user-images.githubusercontent.com/6305602/58748422-c6565780-8478-11e9-8b90-123556061f70.png)

**Comment by DaanVanYperen** [comment]
Missing something about @All, @One etc and subscriptions in the wiki.

**Comment by junkdog** [comment]
The diagrams are pretty neat. We should maybe setup a module or script to automate compilation of updated diagrams.

**Comment by DaanVanYperen** [comment]
Feel the documentation is in a pretty good place. Closing this for now.
