### ISSUE TITLE
Nightly builds

### ISSUE THREAD

**Issue by DaanVanYperen** [junkdog/artemis-odb#545]
@junkdog Since releases come a bit slower now having a nightly build running would help peeps a lot. 
I can help set it up https://docs.travis-ci.com/user/cron-jobs/ if we can sort out credentials.

**Comment by junkdog** [comment]
Been meaning to do it, but never got around to it... On it.

**Comment by Mr00Anderson** [comment]
This would be useful. Will you require the nightly commit to build before merging or will the nightly possibly break? 

What help can I provide here to help get this done?

**Comment by DaanVanYperen** [comment]
It'll only release when tests pass. We use Travis for automated builds so shouldn't be too hard, except for maybe the authentication bit. Only @junkdog can release to repo so he has to set it up.

**Comment by junkdog** [comment]
Daily -SNAPSHOT deployment added in https://github.com/junkdog/artemis-odb/commit/f7539b2529c1a5f1de96986259b5b7e3a23806dd

(Sort of daily, I'll move my jenkins to the cloud sometime this or next month; for now it only runs when I'm not away somewhere)
