### ISSUE TITLE
[Fluid] Build configuration errors can cause fluid generator to silently ignore public fields.

### ISSUE THREAD

**Issue by DaanVanYperen** [junkdog/artemis-odb#556]
Build configuration errors can cause fluid generator to silently ignore public fields. 

### Observed
No warning and no public fields exposed on `E`, component methods ARE exposed. Expecting at least a warning during build.

### Resolution
Add error message during build.

### Notes
The old libgdx-artemis-quickstart example didn't include the odb provided `DefaultFieldProxyStrategy` from `artemis-fluid-core` on classpath.

Relateds to https://github.com/DaanVanYperen/libgdx-artemis-quickstart/issues/21 (that project has a fixed gradle).

**Comment by junkdog** [comment]
:cookie:
