### ISSUE TITLE
Documentation on setting up Fluid Entities

### ISSUE THREAD

**Issue by bryanbrunt** [junkdog/artemis-odb#557]
The current documentation on setting up fluid entities could be improved. It supposes that your project file is set up in a defined manner. Also, I'm not interested in using the libgdx-artemis-quickstart project.

For example, my main gradle file (main build.gradle) does not have a project(":core"). So the current documentation isn't useful.

I use the alternate libgdx setup program here:

https://github.com/czyzby/gdx-setup

Could the gradle page here be improved with a more minimalist approach to setting up fluid entities?

**Comment by DaanVanYperen** [comment]
Thanks for the post. Out of interest, what made you use the alternate setup?

**Comment by bryanbrunt** [comment]
1. assets is a separate project that isn't buried under android. This is somewhat ridiculous for libgdx to require an android project.
2. The main build.gradle file is much simplified. The individual project grade files have the majority of the logic for each project.

There's a list of benefits at the link above.

**Comment by DaanVanYperen** [comment]
Updated gradle documentation and made a gradle hello world with just the essentials.
