### ISSUE TITLE
[BUG] Aspect matching entities that don't have the component

### ISSUE THREAD

**Issue by JulienBe** [junkdog/artemis-odb#560]
Hey !
Ok first, I'm quite new to artemis, so it might just be me not understanding something. 
The issue is that the Aspect seem to match entity that don't have the required components.
Here is the code in question : 
```kotlin
class MutateTilesSys :  BaseEntitySystem(Aspect.all(CTileMap::class.java, CTileMutate::class.java, CTileDraw::class.java))  {

   lateinit var mTileMutate : ComponentMapper<CTileMutate>
// other mappers...
    override fun processSystem() {
        val actives = subscription.entities.data
        actives.forEach {
            println("$it : $mTileMutate - ${mTileMutate[it]}")
            mTileMutate.set(it, false)
        }
    }
```
it will print : 

```
0 : ComponentMapper[CTileMutate] - null
```

Artemis is version 2.2.0 

I also tried chaining Aspect.one but it doesn't help :s

I want to precise that I didn't messed with the entity bag contained in the system in any way

**Comment by junkdog** [comment]
hmm; that should work. i'm assuming you're not removing/adding anything from the `IntBag` and the system is invoked with `World::process`?

**Comment by JulienBe** [comment]
Nevermind I think I found my issue. 
I was creating a component manually in another place to add the CTileMutate component to the entity. So I guess it was there, but not for the component in this system :)
Sorry for the inconvenience !

**Comment by junkdog** [comment]
No inconvenience :)

as long as components are added/removed using `ComponentMapper`, artemis will ensure that compositionIds (driving EntitySubscriptions) propagate during `World::process`.

**Comment by junkdog** [comment]
Closing this for now, but feel free to re-open if you face more problems.
