### ISSUE TITLE
[FLUID] Fluid entities slow compilation on Linux

### ISSUE THREAD

**Issue by bryanbrunt** [junkdog/artemis-odb#562]
I just started prototyping a game with fluid entities.  My components project is nearly bare bones; very few components defined.  I'm using androidstudio and libgdx 1.9.9.

The problem is that the regeneration of the fluid components is greatly slowing down development on my Linux machine, Mint 18.3 with JDK 10.  Running the project can sometimes take 10 seconds for the initial screen to appear. Gradle is just chugging along during that time.

This problem doesn't occur on my Windows 10 machine.  
The problem doesn't occur on projects that don't use fluid entities.

Also, is there any way to conditionally prevent the recompilation of the fluid entities by the plugin?

**Comment by DaanVanYperen** [comment]
> The problem is that the regeneration of the fluid components is greatly slowing down development on my Linux machine, Mint 18.3 with JDK 10. Running the project can sometimes take 10 seconds for the initial screen to appear. Gradle is just chugging along during that time.

Heavy lifting in fluid entities is collecting the components from the classpath and a bit of reflection. But besides compiling on an Atom or lacking an SSD that shouldn't be too much of an issue if your project is bare bones. Did a quick issue scan on the reflection library we use, didn't spot anything performance related.

There are a lot of variables here. I would want to exclude Mint or hardware as a cause. Can you supply a minimally working example and some more info on your setup? (hardware specs of the Mint / Windows 10 machine. Anytthing on a virtual machine, etc)?

> Also, is there any way to conditionally prevent the recompilation of the fluid entities by the plugin?

Not built into the plugins, but I would expect Gradle can skip build steps. Something like `fluid.enabled=false`? Regrettably not a Gradle wizard.

**Comment by junkdog** [comment]
do you know which gradle task/tasks take more time on linux? my experience is typically that the java ecosystem performs best on linux. 

> Also, is there any way to conditionally prevent the recompilation of the fluid entities by the plugin?

how about removing the `fluid` dependency on `compileJava`, and have a custom task which depends on `fluid` instead. this way you only need to run your task when component types are changed.

**Comment by junkdog** [comment]
(@DaanVanYperen 

:wave: :wave: )

**Comment by DaanVanYperen** [comment]
Closing abandoned tickets.

**Comment by DaanVanYperen** [comment]
For anyone visiting this ticket. There is a way to speed up fluid compiles by limiting classpath scope for the plugin: #578
