### ISSUE TITLE
[Question] Examples that use drag and drop?

### ISSUE THREAD

**Issue by bryanbrunt** [junkdog/artemis-odb#563]
Is there an example that uses drag and drop?

I've looked through the ludum dare entries and none appear to use drag and drop.

**Comment by DaanVanYperen** [comment]
Without warranty (Jam game after all):
https://github.com/DaanVanYperen/odb-minion-factorium/tree/master/core/src/net/mostlyoriginal/game/system/drag

http://www.mostlyoriginal.net/games/minionfactorium/
(You can see it in action on level 2)
