### ISSUE TITLE
[Question] Game Init tutorial

### ISSUE THREAD

**Issue by Hiverize** [junkdog/artemis-odb#565]
it would be really helpful to have some code snippets on how to initially populate the game with entities (not fluid). The documentation is rather sparse on that. Can that be part of the world building process? Once I have some entities, I get the idea on how to spawn more in game through a system that looks at, say, a "moreEnemies"-component. But what is best practice for game initialisation? Along that same line of thought, when does the initialize() function of a system get called? Once when the world is built? Or only when there are entities that have a matching component?

**Comment by junkdog** [comment]
> The documentation is rather sparse on that.

Agreed, it could certainly be expanded.

> Can that be part of the world building process?

There's no one right way of doing. What I usually do is to load all entities from json (level/scene data) and entities from prefabs. In a libgdx context; each `Screen` has its own `World`; high-level functionality like loading assets is taken care of by the Screen instance (either directly or through delegation).

You basically have 3 options, and they can be mixed freely:
- load from json or kryo
- fluid
- programmatically define entities

Each have their own set of pros and cons - which I guess should also go into the documentation (_makes mental note_).

> when does the initialize() function of a system get called

Only called once - during `World` instantiation, right before the dependency injection phase.

**Comment by junkdog** [comment]
(sorry, had to cut it a bit short - running on a time deficit)

**Comment by Hiverize** [comment]
Thank you for the quick answer. I'll try the programmatic way and have a look at the bunny (json) later.
