### ISSUE TITLE
[Question] Archtype compositionId

### ISSUE THREAD

**Issue by Mr00Anderson** [junkdog/artemis-odb#569]
Is there any reason the Archetype.compositionId is package private? 

https://github.com/junkdog/artemis-odb/blob/11111ba27794737e34bed3c10f96451d00d9e09b/artemis-core/artemis/src/main/java/com/artemis/Archetype.java#L12

I see that I can get an entities compositionId, which is why I would like to access the ArcheType compositionId. At initialization I will be mapping the ArcheType compositionId to a Entity Type name so that I can group my entities when displaying them by using the returned compositionId from the entity and looking it up.

**Comment by DaanVanYperen** [comment]
Exposed in https://github.com/junkdog/artemis-odb/commit/aa15f1eb3877ff0e21f169a935d19957287a6ca7

**Comment by junkdog** [comment]
👍

Converted tabs->spaces - maybe we should just do it for the entire project.
Better now than later; it's already somewhat mixed.
