### ISSUE TITLE
[FEATURE] extend any class with `@Graft.*` API

### ISSUE THREAD

**Issue by junkdog** [junkdog/artemis-odb#576]
Extend existing classes by grafting bytecode from *Transplant* classes. Transplants are plain java classes; annotations define interactions with the target class.

A custom classloader is responsible for applying the transformations at load-time. The classloader is setup either using a javaagent or prior to referencing any targeted classes.

Sprung from #570, refer to it for the discussion leading up to this.

## Use-cases
- Functionality for editors: callbacks and tighter tooling integration
- Additional debugging capabilities: logging, record stack traces, additional callbacks
- Extending existing functionality for final or otherwise non-extendable classes
- The odd bug fix in imported dependencies

## Example Transplant for ComponentMapper

```java
@Graft.Target(ComponentMapper.class)
public class ComponentMapperTransplant<A> {

    @Graft.Mock // only needed for compilation
    private World world;

    @Graft.Fuse // inject into original method; 
    public A create(int entityId) {
        LifecyclePlugin.dispatcher.onComponentPreCreate(world, entityId);
        A result = create(entityId); // create(entity) refers to original method
        LifecyclePlugin.dispatcher.onComponentPostCreate(world, entityId);
        return result;
    }
}
```

## API 

- **`@Graft.Target`** specifies which class to transplant to.
- **`@Graft.Fuse`** transplants bytecode over to `@Graft.Target`, translating any references to `ComponentMapperTransplant` -> `ComponentMapper`.
- **`@Graft.Mock`** to keep the compiler happy when you need to reference fields or methods in the target class. Mocked references point to target class after transplant.
- Any non-annotated methods or fields are copied over as-is.

Nice to have:
- ~~**`@Graft.Replace`**: Like `@Graft.Fuse` but removes the original method.~~ Better to resolve it when applying `@Graft.Fuse`.
- **`@Graft.Remove`**: Remove field or method from target class.

## Caveats
- You're working against internal implementation; there are no semver guarantees
- No retrofitting of interfaces or parent type on target class
- Annotations aren't fused (is there a use-case?)
- No `@Graft.Fuse` for constructors; nice to have, but not initially
- No GWT support
- No android support (possible but not planned)

**Comment by DaanVanYperen** [comment]
Just as an aside, doesn't it make more sense to have this as a separate project that we pull in?

**Comment by junkdog** [comment]
I thought about it, then decided against it - more well defined scope when only artemis is considered - but now I'm undecided again.

**Comment by DaanVanYperen** [comment]
Can always incubate it as Artemis module and package it separately later.

**Comment by junkdog** [comment]
https://github.com/junkdog/graftt - an extra 't' to avoid any name confusion, but annotation names stay the same.

Might be useful outside of artemis, so I guess skipping the temptation to do shortcuts is recouped pretty quickly.

**Comment by DaanVanYperen** [comment]
I like the API a lot, really has a kotlin-y modern vibe to it. Sure it'll grow beyond what we'll use it for.

**Comment by junkdog** [comment]
PSA: a lot of stuff at work and outside work for the remainder of the week; prob won't have time to do any work on it before the weekend

**Comment by junkdog** [comment]
Given:

```java
public class SingleClassMethod {
    public final void yo() {
        yolo();
    }

    private void yolo() {
        yoloCalled = true;
    }

    public boolean yoloCalled = false;
    public static boolean invokedWithTransplant  = false;
}

```

and

```
@Graft.Target(SingleClassMethod.class)
public class SingleClassMethodTransplant {
    @Graft.Fuse
    private void yolo() {
        SingleClassMethod.invokedWithTransplant = true;
        yolo(); // SingleClassMethod::yolo
    }
}
```

the first test now passes:

```kotlin
    @Test
    fun `fuse no args methods`() {
        val donor = classNode<SingleClassMethodTransplant>()

        val receiver = resultOf { donor }
            .andThen(::readTargetType)
            .andThen(::loadClassNode)

        resultOf(receiver) { donor }
            .map(ClassNode::graftableMethods)
            .map { fns -> fns.map { Transplant.Method(donor.name, it) } }
            .map { fns -> fns.forEach { receiver.unwrap().fuse(it) } }
            .onFailure { fail(it.toString()) }

        val modified: ClassNode = receiver.unwrap()
        assertEquals(VerificationStatus.Ok, verify(modified))

        instantiate(modified).apply {
            assertMethodExists("yolo")
            assertMethodExists("yolo\$original")

            invokeMethod("yo")
            assertFieldValue("invokedWithTransplant", true)
            assertFieldValue("yoloCalled", true)
        }
    }
```

**Comment by junkdog** [comment]
deployed 0.1.0-SNAPSHOT to maven central :)

thinking a 0.1.0 release is best done once we've confirmed that all transplants work as intended.

**Comment by junkdog** [comment]
Closing as [junkdog/graftt](graftt) is its own project
