### ISSUE TITLE
[Question] [Feature?] Interval system without aspect?

### ISSUE THREAD

**Issue by nanonull** [junkdog/artemis-odb#581]
Hey!

Just wondering is there some system to execute at given interval but without entity aspect out of box?

What I want to achieve:
```
public class BattleSystem extends SomeSystem? {
    BattleSystem (float interval){
        super(interval);
    }

    @Override
    protected void processSystem() {        
        // my logic here
    }
}
```

What I have now, example:
```
public class BattleSystem extends BaseSystem {
    private float deltaAcc;
    private static final float INTERVAL = 1 / 60f;

    @Override
    protected void processSystem() {
        deltaAcc += world.getDelta();
        if (deltaAcc < INTERVAL) {
            return;
        }
        deltaAcc -= INTERVAL;
        
        // my logic here
    }
}
```

**Comment by DaanVanYperen** [comment]
Nothing like that in odb as far as I'm aware. You'd typically just roll your own abstract class for things like this. `MyIntervalBaseSystem` with your `deltaAcc` logic in `checkProcessing`.

Not sure if it fits odb core but you could consider a PR to https://github.com/DaanVanYperen/artemis-odb-contrib/
