### ISSUE TITLE
[Question] "System was disabled/enabled" event

### ISSUE THREAD

**Issue by Namek** [junkdog/artemis-odb#587]
Hi folks! I'm working on the new Artemis Entity Tracker which job is to inspect whole `World` of entities but not do any changes to it. So, when observed game disables some system or manager I want to know about it and show it in GUI. AFAIK there is no such event. A way to achieve this is to implement custom `SystemInvocationStrategy` and provide it with custom `World` (because setter is `protected`). This is the way to provide custom `setEnabled()` which would notify about every change. However, I don't want this solution because user may have already created his own World and do whatever he needed. I don't want to alter that.

I have an alternative solution, based on Java Reflection mehanism. I get the field `SystemInvocationStrategy.disabled` and I have all I want, except, it's not event-based but polling-based.

Is there any alternative to achieve this in the event way?

**Comment by junkdog** [comment]
Hi there!

> Is there any alternative to achieve this in the event way?

So, incidentally, #570 would require opening up multiple classes to be feasible - it also revolved around tooling, and as such would make use of _unusual access_ points in the API. I'd rather avoid opening up classes too much as it makes maintenance/future refactoring much more difficult.

As a workaround, [graftt](https://github.com/junkdog/graftt/) allows rewriting classes - based on plain compiled code templates - before they reach the classloader. It was originally conceived as a means of injecting new callbacks and defensive checks into deep into internal code ;)

I can help you with the graftt transplants if you're interested. 

Does your entity tracker connect to platforms other than desktop?

**Comment by junkdog** [comment]
Another option is to wrap the `SystemInvocationStrategy` in your own SIC, delegate all invocations to the wrapped implementation.

**Comment by Namek** [comment]
> Another option is to wrap the SystemInvocationStrategy in your own SIC, delegate all invocations to the wrapped implementation.

That's an interesting idea, thanks! For now I check thinks periodically, I'll be biting it if that's a perf problem.

> Does your entity tracker connect to platforms other than desktop?

It's basically over TCP, so the device doesn't matter. That was the goal - both PC and Android should be able to serve data for the UI client. I'll notify you (over Twitter?) when it's ready-ish for basic usage. May take up to few weeks. Thankfully, I'm unemployed for some time now, so I can dig my teeth into this project.

Sneak peek of Artemis Entity Tracker:


![artemis_entity_tracker_1](https://user-images.githubusercontent.com/31058/61997340-8b4f5980-b0a0-11e9-9b50-7cfab79a3c27.png)


![artemis_entity_tracker_2](https://user-images.githubusercontent.com/31058/61997285-99e94100-b09f-11e9-85f6-78ab7d007235.png)

**Comment by junkdog** [comment]
> Sneak peek of Artemis Entity Tracker:

Cool!
