### ISSUE TITLE
[Question] Listening to Changes in Entity

### ISSUE THREAD

**Issue by IkeOTL** [junkdog/artemis-odb#588]
I'm using SubscriptionListener to listen for composition changes in entities. However, SubscriptionListener doesn't listen for change events.

For example:
```
entity00.create(MotionComponent.class);
```
SubscriptionListener  see this.
Later, at some point...

again
```
entity00.create(MotionComponent.class);
```
SubscriptionListener  does not see this.

How can I intercept the replacing of the old MotionComponent?

**Comment by junkdog** [comment]
This doesn't fire unless you first remove MotionComponent + let the AspectSubscriptionManager run (happens in-between systems and around `World::process`).

artemis only triggers on changing compositionId:s. This is not the case when the sought component already exists, as it won't update the compositionId - as the cId only represent the set of component types for a given entity.

**Comment by IkeOTL** [comment]
Yeah, I'm aware of that. But is there a way to listen to a change like this?

My current solution is to have a dirty flag in the component, and reprocess it when the system processes.

**Comment by junkdog** [comment]
> is there a way to listen to a change like this?

Not directly. From artemis' POV there is no change as no component was added/removed.

> My current solution is to have a dirty flag

This is a pretty common approach. If you really want to trigger on composition changes, it is sometimes possible to achieve this using multiple component types, but it's really contextual whether this is a better than a dirty flag or not.

What's your use-case?

**Comment by DaanVanYperen** [comment]
Discussion has ended, closing. Feel free to reopen if needed.
