### ISSUE TITLE
[Question] Purpose of Bag#ensureCapacity(int)

### ISSUE THREAD

**Issue by a-ivanov** [junkdog/artemis-odb#590]
Underlying array grow behaviour is provided by such mutating methods as `Bag#safeGet(int)` `Bag#set(int, E)`, etc. Why do we need a separate method for capacity control? EntityManager and ComponentManager use the method exclusively and imho they don't need such functionality either, do they?

Thanks.

**Comment by junkdog** [comment]
It's to avoid growing the array unnecessarily, which can be a problem if you're dealing with a lot of new entities, especially if the JIT hasn't optimized everything yet.

To safe a few cycles, artemis uses `unsafeSet` whenever we know it's a safe operation (currently the case for ComponentMappers and ComponentRemovers).

```java
    /**
     * <em>Unsafe method.</em> Sets element at specified index in the bag,
     * without updating size. Internally used by artemis when operation is
     * known to be safe.
     *
     * @param index position of element
     * @param e     the element
     */
    public void unsafeSet(int index, E e) {
        data[index] = e;
    }
```
