### ISSUE TITLE
[BUG] inserted not called when entities added in system initialize

### ISSUE THREAD

**Issue by LaurenceWarne** [junkdog/artemis-odb#591]
<code>SubscriptionListener.inserted()</code> is not called if I create entities in the <code>initialize()</code> method of a system. This is the same problem highlighted in #248, but <code>EntityObserver</code> no longer exists. Is this intended and if so is there some kind of work around?

**Comment by junkdog** [comment]
We'll have to take a look. Pretty sure I've done it in the past. Just to make sure; calling `World::process` does not trigger the subscription listener?

**Comment by LaurenceWarne** [comment]
Ah yes! I had forgot to call that in my original test case. 

What had caught me out initially is if you create an entity in a system's <code>initialize()</code> method and then add a subscription listener in a subsequently added system's <code>initialize()</code> then <code>inserted()</code> will not be called for that susbscription for the added entity. 

I hacked together a test to demonstrate: <a href="https://gist.github.com/LaurenceWarne/68b07e6741856655cc35723e39995457">link</a>

So I just made sure the system which added the subscription was initialized first with <code>WorldConfigurationBuilder.Priority</code>.
