### ISSUE TITLE
request for release of 2.3.0

### ISSUE THREAD

**Issue by DaanVanYperen** [junkdog/artemis-odb#592]
@junkdog mind releasing 2.3.0? Good to make the GDX and GWT bump available to the public. I've fixed all the regressions in odb-contrib 2.3.0 and ready for release on that end.

#### Version: 2.3.0-SNAPSHOT

- **BREAKING CHANGES**
  - Web backend upgraded to GWT `2.8.2`.
  - Serialization modules that depend on libGDX now require `1.9.10`.
  - Make sure you clean your build when using Fluid entities.

- **Fluid entities** quality of life changes.
  - New `EntitySubscription` facade `ESubscription`, for convenient `E` iteration. 
  - Annotation driven aspects allow DI of `ESubscription` (requires registered `FluidEntityPlugin`)
  - Ability to exclude specific component methods from the fluid API. `@FluidMethod(exclude=true)`
  - `E` toString now reports entity id for easier debugging. ie: `E{id=10}`.    
- Gradle plugin now supports `classesDirs`, deprecated `classesDir`.
- Improve flexibility of logic behind annotations dependency injection. (no user impact).
- **FIX**: Avoiding an NPE in optimizer.EntitySystemType if meta.superClass is null.
- **FIX**: ObjectWeb ASM updated to 7.0 to avoid choking on more modern bytecode.
- **FIX**: Artemis-odb integration tests now run properly on JDK 9+.
- **FIX**: Fluid gradle plugin logging (now reports what artifacts it scans).

**Comment by junkdog** [comment]
I'm off on a trip; I'll do it during the weekend.

**Comment by DaanVanYperen** [comment]
You didn't mention which weekend! 😭

**Comment by DaanVanYperen** [comment]
o___________________________________________________________________________________________________________o

**Comment by junkdog** [comment]
temporal race condition, but 2.3.0 is now released, during *a* weekend

**Comment by DaanVanYperen** [comment]
:cookie: :cookie: :cookie: :cookie: :cookie:

**Comment by junkdog** [comment]
*Munch-munch*
