### ISSUE TITLE
Some potential NullPointerException bugs

### ISSUE THREAD

**Issue by JulyChen728** [junkdog/artemis-odb#595]
Hi all,
Our bug scanner has reported some NPE bugs.

1.The first bug is at [IntBagIterator.java#L73](https://github.com/junkdog/artemis-odb/tree/artemis-odb-2.2.0/artemis-core/artemis/src/main/java/com/artemis/utils/IntBagIterator.java#L73) , since the parameter `intBag` is checked for whether being `null` or not at line [74](https://github.com/junkdog/artemis-odb/tree/artemis-odb-2.2.0/artemis-core/artemis/src/main/java/com/artemis/utils/IntBagIterator.java#L74) , a NPE bug may take place when parameter `intBag` invokes its method `size()` at line 73. 

2.The second bug is caused by the `return null` in method [allComponents()](https://github.com/junkdog/artemis-odb/tree/artemis-odb-2.2.0/artemis-core/artemis/src/main/java/com/artemis/injection/AspectFieldResolver.java#L114) . A possible call chain is [AspectFieldResolver.java#L55](https://github.com/junkdog/artemis-odb/tree/artemis-odb-2.2.0/artemis-core/artemis/src/main/java/com/artemis/injection/AspectFieldResolver.java#L55) . And a NPE bug may take place in method [add()](https://github.com/junkdog/artemis-odb/tree/artemis-odb-2.2.0/artemis-core/artemis/src/main/java/com/artemis/ArchetypeBuilder.java#L63) since the parameter `types` may be `null`. 

3.The third bug is caused by the `return null` in method [removeLast()](https://github.com/junkdog/artemis-odb/tree/artemis-odb-2.2.0/artemis-backend-gwt/artemis-gwt/src/main/java/com/artemis/backends/gwt/emu/com/artemis/utils/Bag.java#L105) . A possible call chain is [BatchChangeProcessor.java#L70](https://github.com/junkdog/artemis-odb/tree/artemis-odb-2.2.0/artemis-core/artemis/src/main/java/com/artemis/BatchChangeProcessor.java#L70) =>[BatchChangeProcessor.java#L58](https://github.com/junkdog/artemis-odb/tree/artemis-odb-2.2.0/artemis-core/artemis/src/main/java/com/artemis/BatchChangeProcessor.java#L58) . And a NPE bug may take place at [BatchChangeProcessor.java#L61](https://github.com/junkdog/artemis-odb/tree/artemis-odb-2.2.0/artemis-core/artemis/src/main/java/com/artemis/BatchChangeProcessor.java#L61) since the variable `edit` may be `null`.

4.The forth bug is caused by the `return null` in method [getAnnotation()](https://github.com/junkdog/artemis-odb/tree/artemis-odb-2.2.0/artemis-core/artemis/src/main/java/com/artemis/utils/reflect/Field.java#L148) in `Field.java`. A possible call chain is [InjectionCache.java#L98](https://github.com/junkdog/artemis-odb/tree/artemis-odb-2.2.0/artemis-core/artemis/src/main/java/com/artemis/injection/InjectionCache.java#L98) . And a NPE bug may take place at [InjectionCache.java#L99](https://github.com/junkdog/artemis-odb/tree/artemis-odb-2.2.0/artemis-core/artemis/src/main/java/com/artemis/injection/InjectionCache.java#L99) since the variable `wire` may be `null`.

5.The fifth bug is caused by the `return null` in method [getAnnotation()](https://github.com/junkdog/artemis-odb/tree/artemis-odb-2.2.0/artemis-core/artemis/src/main/java/com/artemis/utils/reflect/ClassReflection.java#L188) in `ClassReflection.java`. A possible call chain is [InjectionCache.java#L64](https://github.com/junkdog/artemis-odb/tree/artemis-odb-2.2.0/artemis-core/artemis/src/main/java/com/artemis/injection/InjectionCache.java#L64) . And a NPE bug may take place in method [setWireAnnotation()](https://github.com/junkdog/artemis-odb/tree/artemis-odb-2.2.0/artemis-core/artemis/src/main/java/com/artemis/injection/InjectionCache.java#L78) since the parameter `wireAnnotation` may be `null`.

6.The sixth bug is caused by the `return null` in method [getElementType()](https://github.com/junkdog/artemis-odb/tree/artemis-odb-2.2.0/artemis-core/artemis/src/main/java/com/artemis/utils/reflect/Field.java#L121) . A possible call chain is [InjectionCache.java#L131](https://github.com/junkdog/artemis-odb/tree/artemis-odb-2.2.0/artemis-core/artemis/src/main/java/com/artemis/injection/InjectionCache.java#L131) =>[ArtemisFieldResolver.java#L61](https://github.com/junkdog/artemis-odb/tree/artemis-odb-2.2.0/artemis-core/artemis/src/main/java/com/artemis/injection/ArtemisFieldResolver.java#L61) =>[ArtemisFieldResolver.java#L62](https://github.com/junkdog/artemis-odb/tree/artemis-odb-2.2.0/artemis-core/artemis/src/main/java/com/artemis/injection/ArtemisFieldResolver.java#L62) =>[World.java#L410](https://github.com/junkdog/artemis-odb/tree/artemis-odb-2.2.0/artemis-core/artemis/src/main/java/com/artemis/World.java#L410) =>[ComponentManager.java#L56](https://github.com/junkdog/artemis-odb/tree/artemis-odb-2.2.0/artemis-backend-gwt/artemis-gwt/src/main/java/com/artemis/backends/gwt/emu/com/artemis/ComponentManager.java#L56) =>[ComponentTypeFactory.java#L54](https://github.com/junkdog/artemis-odb/tree/artemis-odb-2.2.0/artemis-core/artemis/src/main/java/com/artemis/ComponentTypeFactory.java#L54) =>[ComponentTypeFactory.java#L63](https://github.com/junkdog/artemis-odb/tree/artemis-odb-2.2.0/artemis-core/artemis/src/main/java/com/artemis/ComponentTypeFactory.java#L63) =>[InvalidComponentException.java#L11](https://github.com/junkdog/artemis-odb/tree/artemis-odb-2.2.0/artemis-core/artemis/src/main/java/com/artemis/InvalidComponentException.java#L11) =>[InvalidComponentException.java#L21](https://github.com/junkdog/artemis-odb/tree/artemis-odb-2.2.0/artemis-core/artemis/src/main/java/com/artemis/InvalidComponentException.java#L21). A NPE bug may take place in method [getSimpleName()](https://github.com/junkdog/artemis-odb/tree/artemis-odb-2.2.0/artemis-core/artemis/src/main/java/com/artemis/utils/reflect/ClassReflection.java#L37) since the parameter `c` may be `null`.

Thanks.

**Comment by ITWOI** [comment]
Hi, we have reported the bugs a while ago would you please take a look and confirm if they are real bugs. We have been conducting an experiment to measure the accuracy of our static checker. We would be deeply appreciated if you can provide some feedback!

**Comment by DaanVanYperen** [comment]
Bit late but thanks for the ticket! Static checker is tripping over some bits that could probably be refactored for clarity but wouldn't provide much value to our users. I've fixed the things that are actual bugs.

>> 1.The first bug is at IntBagIterator.java#L73 , since the parameter intBag is checked for whether being null or not at line 74 , a NPE bug may take place when parameter intBag invokes its method size() at line 73.

Fixed

2.The second bug is caused by the return null in method allComponents() . A possible call chain is AspectFieldResolver.java#L55 . And a NPE bug may take place in method add() since the parameter types may be null.

Fixed

> 3.The third bug is caused by the return null in method removeLast() . A possible call chain is BatchChangeProcessor.java#L70 =>BatchChangeProcessor.java#L58 . And a NPE bug may take place at BatchChangeProcessor.java#L61 since the variable edit may be null.

False positive. `BatchChangeProcessor:entityEdit` has a bounds check via `pool.isEmpty` and should always return a valid value, unless the pool somehow contains a null itself?

> 4.The forth bug is caused by the return null in method getAnnotation() in Field.java. A possible call chain is InjectionCache.java#L98 . And a NPE bug may take place at InjectionCache.java#L99 since the variable wire may be null.

False positive. InjectionCache::getCachedField checks if the annotation exists, before actually calling getAnnotation.

> 5.The fifth bug is caused by the return null in method getAnnotation() in ClassReflection.java. A possible call chain is InjectionCache.java#L64 . And a NPE bug may take place in method setWireAnnotation() since the parameter wireAnnotation may be null.

False positive. IntellIJ gets tripped up by this as well. InjectionCache::getCachedClass getWireType(clazz) does the check.

> 6.The sixth bug is caused by the return null in method getElementType() . A possible call chain is InjectionCache.java#L131 =>ArtemisFieldResolver.java#L61 =>ArtemisFieldResolver.java#L62 =>World.java#L410 =>ComponentManager.java#L56 =>ComponentTypeFactory.java#L54 =>ComponentTypeFactory.java#L63 =>InvalidComponentException.java#L11 =>InvalidComponentException.java#L21. A NPE bug may take place in method getSimpleName() since the parameter c may be null.

False positive. ArtemisFieldResolver::resolve does a type check which guarantees generics are present.
