### ISSUE TITLE
[BUG] GitHub not accepting/identifying the LICENSE (as BSD-2-clause)

### ISSUE THREAD

**Issue by hoijui** [junkdog/artemis-odb#601]
(old, closed, but same issue: https://github.com/junkdog/artemis-odb/issues/464)

While GitHub detects [LICENSE](https://github.com/junkdog/artemis-odb/blob/develop/LICENSE) (BSD-2-clause) as the main LICENSE file, it apparently also sees [LICENSE.libgdx](https://github.com/junkdog/artemis-odb/blob/develop/LICENSE.libgdx) (APLv2), and thus it decides to not know what the license is; compare these two:

* https://github.com/junkdog/artemis-odb/blob/develop/LICENSE
* https://github.com/kazimierz-256/EventCalculusWebApp/blob/master/LICENSE

> NOTE: I checked on my fork: If I remove the LICENSE.libgdx file, GitHub detects BSD-2-clause; see:
https://github.com/hoijui/artemis-odb/blob/develop/LICENSE

**Comment by hoijui** [comment]
I don't know what the proper solution would be.. :/

**Comment by hoijui** [comment]
GitHub recommends to have only one LICENSE file with one license in it, and talk about the other license related stuff (like licenses of dependencies or secondary licenses) in the README:

https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#detecting-a-license

**Comment by hoijui** [comment]
(side comment; quite unrelated)

maybe also put this in the README?

[![License](https://img.shields.io/badge/License-BSD%202--Clause-orange.svg)](https://opensource.org/licenses/BSD-2-Clause)

`[![License](https://img.shields.io/badge/License-BSD%202--Clause-orange.svg)](https://opensource.org/licenses/BSD-2-Clause)`

**Comment by hoijui** [comment]
I found a related stack* question. the first two answers seem very good:
https://softwareengineering.stackexchange.com/questions/304874/declaring-multiple-licences-in-a-github-project/371526

**Comment by junkdog** [comment]
thanks for the head's up and info! i'll fix it after work/sometime this week.

**Comment by DaanVanYperen** [comment]
Thanks @hoijui! :cookie:
That was an absolute pain to fix but it works.
