### ISSUE TITLE
[Question] Is artemis thread safe ? 

### ISSUE THREAD

**Issue by genaray** [junkdog/artemis-odb#606]
Im using Database-Operations in my game which kinda block the ecs flow... so i thought about letting those database systems run in a extra thread... this way the other systems arent forced to wait till the operations finished.

So is it possible to run a artemis system or certain lines in that system in a new thread ?

**Comment by DaanVanYperen** [comment]
Accessing elements of one ```World``` from multiple threads is not safe. 

Asynchronous processes triggered from systems should be fine as long as you pass through the data you need and don't access the Artemis API from that thread. So no accessing subscriptions, systems, components(?), etc. It should be a fairly common use case (for things like pathfinding).

Maybe you can find some examples/help on the ecs channel on discord: https://libgdx.badlogicgames.com/community.html
