### ISSUE TITLE
[FEATURE] Add a WorldConfigurationBuilder#register to wire custom dependencies

### ISSUE THREAD

**Issue by qwbarch** [junkdog/artemis-odb#611]
**WorldConfigurationBuilder** is missing a builder method for **WorldConfiguration#register**, which allows one to wire custom dependencies before the world is initialized.

**Comment by qwbarch** [comment]
If this feature request is accepted, would it be okay if I do it?

**Comment by genaray** [comment]
I support this approach ^

**Comment by qwbarch** [comment]
Didn't realize this earlier but one could simply use:
```kotlin
World(
    WorldConfigurationBuilder()
        .with(System1(), System2())
        .build()
        .register("foo", "foo")
        .register("bar", "bar")
)
```
I forgot **WorldConfigurationBuilder** returns a **WorldConfiguration**...
